import test from 'node:test';import assert from 'node:assert/strict';
import {VectorDocument,starterSvg} from '../packages/core/document.js';import {exportSvg} from '../packages/core/export.js';import {audit,quality} from '../packages/core/agent.js';import {assertSvg} from '../packages/converter/svg.js';
test('composition namespaces references, preserves native animation and reopens both components',()=>{const m=new VectorDocument(starterSvg);const svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><defs><linearGradient id="paint"><stop stop-color="#ff0000"/></linearGradient></defs><path id="tail" d="M0 0L50 50" stroke="url(#paint)"><animate id="a" attributeName="opacity" values="0;1" dur="1s"/></path></svg>';m.apply([{type:'scene.insert',svg,id:'first',name:'Uno',width:100,height:100},{type:'scene.insert',svg,id:'second',name:'Dos',x:150,width:100,height:100}]);assertSvg(m.toSVG());assert.equal(m.element('first-tail').getAttribute('stroke'),'url(#first-paint)');assert.equal(m.element('second').getAttribute('x'),'150');const reopened=new VectorDocument(exportSvg(m,{profile:'editable'}).svg);assert.equal(reopened.element('first-tail').getElementsByTagName('animate').length,1);assert.equal(reopened.element('tail').getAttribute('fill'),'#c38253');});
test('composition and canvas rollback atomically on unsafe CSS or duplicate ID',()=>{const m=new VectorDocument(starterSvg),before=m.toSVG();assert.throws(()=>m.apply([{type:'canvas',width:1000,height:500},{type:'scene.insert',svg:'<svg xmlns="http://www.w3.org/2000/svg"><style>@font-face{font-family:x;src:local(x)}</style></svg>',name:'bad'}]),/Unsupported composition CSS/);assert.equal(m.toSVG(),before);assert.throws(()=>m.apply([{type:'scene.insert',svg:starterSvg,id:'tail',name:'bad'}]),/exists/);});
test('motion presets copy, stretch, reverse and delete without silent track overwrites',()=>{const m=new VectorDocument(starterSvg);m.apply([{type:'motion.preset',id:'tail',kind:'float',amplitude:20},{type:'track.copy',target:'tail',to:'body',property:'y'},{type:'track.edit',target:'body',property:'y',action:'stretch',amount:.5}]);assert.deepEqual(m.project.tracks.find(t=>t.target==='body')!.keys.map(k=>k.time),[0,1.25,2.5]);const before=m.toSVG();assert.throws(()=>m.apply([{type:'track.edit',target:'body',property:'y',action:'shift',amount:10}]),/numeric/);assert.equal(m.toSVG(),before);assert.throws(()=>m.apply([{type:'motion.preset',id:'tail',kind:'float'}]),/overwrite/);m.apply([{type:'track.edit',target:'body',property:'y',action:'reverse'},{type:'track.edit',target:'tail',property:'y',action:'delete'}]);assert.equal(m.project.tracks.length,1);assertSvg(exportSvg(m,{profile:'standalone'}).svg);});
test('diagnostics report loop seam and quality guidance preserves chosen default',()=>{const m=new VectorDocument(starterSvg);m.apply([{type:'keyframe',target:'tail',property:'y',time:0,value:0},{type:'keyframe',target:'tail',property:'y',time:5,value:10}]);assert.ok(audit(m).findings.some(f=>f.code==='MAI_LOOP_SEAM'));assert.equal(quality('motion').defaultUnchanged,'high-color-preserved');assert.equal(quality('fidelity').preset,'high-color-preserved');assert.throws(()=>quality('automatic'));});

test('component CSS selectors, URLs and keyframes are isolated across repeated SVG',()=>{const m=new VectorDocument(starterSvg);const svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><style>@keyframes float{0%{opacity:0}100%{opacity:1}} #p,.shape{fill:url(#paint);animation:float 2s infinite}</style><defs><linearGradient id="paint"><stop stop-color="#ff0000"/></linearGradient></defs><path id="p" class="shape" d="M0 0L100 100" style="animation-name:float"/></svg>';m.apply([{type:'scene.insert',svg,id:'one',name:'One'},{type:'scene.insert',svg,id:'two',name:'Two'}]);const out=m.toSVG();assertSvg(out);assert.match(out,/@keyframes one-float/);assert.match(out,/:where\(#one\)/);assert.match(out,/animation-name:one-float/);assert.match(out,/url\(#two-paint\)/);});
import {renderSvg,closeRenderer} from '../packages/server/render.js';import sharp from 'sharp';
test('scoped CSS renders its component without recoloring sibling geometry',async()=>{const m=new VectorDocument('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 100"><path id="outside" class="shape" fill="#00ff00" d="M150 0H250V100H150Z"/></svg>');m.apply([{type:'scene.insert',id:'inside',name:'CSS',width:100,height:100,svg:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><style>.shape{fill:#ff0000!important}</style><path class="shape" d="M0 0H100V100H0Z"/></svg>'}]);try{const image=await renderSvg(exportSvg(m,{profile:'standalone'}).svg);const raw=await sharp(image.png).ensureAlpha().raw().toBuffer();assert.deepEqual([...raw.subarray((50*300+50)*4,(50*300+50)*4+4)],[255,0,0,255]);assert.deepEqual([...raw.subarray((50*300+200)*4,(50*300+200)*4+4)],[0,255,0,255]);}finally{await closeRenderer();}});
