import {OPERATION_TYPES} from '../core/model.js';
import {readFileSync} from 'node:fs';
const PLAN_SCHEMA=JSON.parse(readFileSync(new URL('./schemas/agent-plan.v1.schema.json',import.meta.url),'utf8'));
const PLAN_EXAMPLE=JSON.parse(readFileSync(new URL('./schemas/examples/candy-direction.plan.json',import.meta.url),'utf8'));
// Single source of truth for the agent surface. CLI, HTTP API and MCP are generated from these definitions.
// The agent interprets human intent; these tools only execute structured, validated, reversible actions.
export type Schema={type?:'object'|'string'|'number'|'integer'|'boolean'|'array';oneOf?:Schema[];const?:unknown;exclusiveMinimum?:number;minLength?:number;maxLength?:number;pattern?:string;description?:string;properties?:Record<string,Schema>;required?:string[];items?:Schema;enum?:(string|number)[];minimum?:number;maximum?:number;minItems?:number;maxItems?:number;additionalProperties?:Schema|boolean;default?:unknown};
export type Tool={availability?:{status:'stable'|'experimental';note?:string};outputSchema?:Schema;destructive?:boolean;name:string;mcp:string;cli:string;kind:'query'|'proposal'|'mutation'|'render'|'session';summary:string;when:string;input:Schema;returns:string;sideEffects:string;reversible:'n/a'|'undoToken'|'dismiss'|'no';preview:'none'|'recommended'|'returned';identityImpact:'none'|'reported'|'guarded';examples:{args:Record<string,unknown>;why:string}[]};
const o=(properties:Record<string,Schema>,required:string[]=[]):Schema=>({type:'object',properties,required,additionalProperties:false});
const str=(description:string,extra:Partial<Schema>={}):Schema=>({type:'string',description,...extra});
const num=(description:string,minimum?:number,maximum?:number):Schema=>({type:'number',description,...(minimum!==undefined?{minimum}:{}),...(maximum!==undefined?{maximum}:{})});
const bool=(description:string):Schema=>({type:'boolean',description});
const map=(description:string,value:Schema):Schema=>({type:'object',description,additionalProperties:value});
const arr=(description:string,items:Schema,maxItems=500):Schema=>({type:'array',description,items,maxItems});
const rev=num('Revision observed in your last read. 409 REVISION_CONFLICT means a human or another agent edited meanwhile: re-inspect, never retry blind.',0);
const ref=str('Part address: semantic path ("candy.flask.smoke"), node id, role ("mouth", "eyes") or raw SVG id prefixed with # ("#mai-shape-12").');
const point=o({x:num('x in document units'),y:num('y in document units')},['x','y']);
const box=o({x:num('left'),y:num('top'),width:num('width',0),height:num('height',0)},['x','y','width','height']);
const pt=o({x:num('x'),y:num('y')},['x','y']);
// Regions are a closed union: each kind declares exactly its coordinates.
const region:Schema={description:'Document-space region',oneOf:[o({kind:{type:'string',const:'ellipse'},cx:num('center x'),cy:num('center y'),rx:{type:'number',exclusiveMinimum:0},ry:{type:'number',exclusiveMinimum:0}},['kind','cx','cy','rx','ry']),o({kind:{type:'string',const:'rect'},x:num('left'),y:num('top'),width:{type:'number',exclusiveMinimum:0},height:{type:'number',exclusiveMinimum:0}},['kind','x','y','width','height']),o({kind:{type:'string',const:'polygon'},points:{type:'array',items:pt,minItems:3,maxItems:2000}},['kind','points'])]};
// Core operations are discriminated by type; the core validates each operation's fields and rolls back on error.
const operation:Schema={type:'object',description:'Core operation (packages/core/model.ts Operation). Fields beyond `type` are validated by the core inside the transaction.',required:['type'],properties:{type:{type:'string',enum:[...OPERATION_TYPES]}}};
const choiceOption:Schema={type:'object',additionalProperties:false,required:['id','label','description'],properties:{id:{type:'string',pattern:'^[a-zA-Z][\\w-]{0,60}$'},label:{type:'string',minLength:1,maxLength:100},description:{type:'string',minLength:1,maxLength:1000},ops:{type:'array',items:operation,minItems:1,maxItems:500},spec:{type:'object',description:'Combinable spec: {params:{"param@slot":value}, time?, layer?, base?:Operation[], slots?:{slot:Operation[]}, modifiers?:{slot:{id,params?,direction?}}}',additionalProperties:false,properties:{params:{type:'object',additionalProperties:{type:'number'}},time:{type:'number',minimum:0},layer:{type:'string'},base:{type:'array',items:operation},slots:{type:'object',additionalProperties:{type:'array',items:operation}},modifiers:{type:'object',additionalProperties:{type:'object'}}}},highlight:{type:'array',items:{type:'string'},maxItems:5000}}};
const choiceRequest:Schema={type:'object',additionalProperties:false,required:['id','prompt','recommended','reason','options'],properties:{id:{type:'string',pattern:'^[a-zA-Z][\\w-]{0,60}$'},prompt:{type:'string',minLength:1,maxLength:1000},recommended:{type:'string'},reason:{type:'string',minLength:1,maxLength:1000},time:{type:'number',minimum:0},kind:{type:'string',maxLength:60},previewRegion:o({x:{type:'integer',minimum:0},y:{type:'integer',minimum:0},width:{type:'integer',minimum:1},height:{type:'integer',minimum:1}},['x','y','width','height']),previewScale:{type:'number',enum:[1,2]},options:{type:'array',items:choiceOption,minItems:2,maxItems:6}}};
const levels=arr('Protection levels (strictest wins): locked, protected (rigid only), deformable (expression warps), style-preserved, topology-preserved, color-preserved, silhouette-preserved, free',str('level',{enum:['locked','protected','deformable','style-preserved','topology-preserved','color-preserved','silhouette-preserved','free']}),8);
const previewArg=o({times:arr('Seconds to render (max 8)',num('',0),8),region:box,part:ref,scale:num('Device scale 0.25–4',.25,4)},[]);
const mutation=(props:Record<string,Schema>,required:string[]):Schema=>o({...props,expectedRevision:rev,dryRun:bool('Validate and report changes on a copy without committing (no revision change).'),preview:previewArg,label:str('History label shown to the human')},[...required,'expectedRevision']);
export const SLOTS=['mouth','eyes','brows','ears','face'];
export const TOOLS:Tool[]=[
 // ── Discovery and inspection ─────────────────────────────────────────────────────────────
 {name:'capabilities',mcp:'mai_capabilities',cli:'capabilities',kind:'query',summary:'List every tool with schemas, side effects, reversibility, preview and identity behaviour.',when:'Once per session before planning; again if a tool returns UNKNOWN_TOOL.',input:o({tool:str('Return only this tool')}),returns:'{tools:[…], workflow, conventions}',sideEffects:'none',reversible:'n/a',preview:'none',identityImpact:'none',examples:[{args:{},why:'Discover the vocabulary.'}]},
 {name:'scene.inspect',mcp:'inspect_scene',cli:'inspect',kind:'query',summary:'Semantic scene graph with real IDs and addresses (never raw path data), parameters, layers, modifiers, choices, comments and suggested next steps.',when:'Start of every task and after any 409 or human edit.',input:o({depth:{type:'integer',minimum:1,maximum:12,description:'Tree depth'}}),returns:'{asset, revision, canvas, parts:[{id,address,role,label,status,protection,ids,bounds,landmarks,animated,expression,modifiers,children}], parameters, layers, modifiers, choice, comments, next}',sideEffects:'none',reversible:'n/a',preview:'none',identityImpact:'none',examples:[{args:{},why:'Understand what exists before editing.'}]},
 {name:'scene.semantics',mcp:'list_parts',cli:'semantics',kind:'query',summary:'All semantic parts with addresses, roles, protection, landmarks, regions, confidence and relations.',when:'Before targeting a part; to see what is still only proposed.',input:o({}),returns:'{parts:[…], relations:[…]}',sideEffects:'none',reversible:'n/a',preview:'none',identityImpact:'none',examples:[{args:{},why:'Find the address of the smoke.'}]},
 {name:'scene.selection',mcp:'get_selection',cli:'selection',kind:'query',summary:'What the human currently has selected in the editor, resolved to semantic parts.',when:'When the human says "this", "esto", "esa parte".',input:o({}),returns:'{ids, parts, bounds}',sideEffects:'none',reversible:'n/a',preview:'none',identityImpact:'none',examples:[{args:{},why:'Resolve a deictic reference.'}]},
 {name:'scene.timeline',mcp:'get_timeline',cli:'timeline',kind:'query',summary:'Duration, fps, loop, layers (mute/solo), tracks per target/property/layer, markers, clips, parameter tracks, modifiers and secondary motion with current values.',when:'Before retiming or adjusting animation.',input:o({target:ref}),returns:'{duration,fps,loop,layers,tracks,markers,regions,clips,params,modifiers,secondary}',sideEffects:'none',reversible:'n/a',preview:'none',identityImpact:'none',examples:[{args:{target:'smoke'},why:'See what animates the smoke.'}]},
 {name:'scene.identity',mcp:'get_identity',cli:'identity',kind:'query',summary:'Protected parts, levels and what they allow, preservation mode (strict|balanced|free) with numeric budgets, expression features and identity findings.',when:'Before any change to a face or character; when the human says "no le cambies X".',input:o({}),returns:'{preservation, levels, parts, features, findings}',sideEffects:'none',reversible:'n/a',preview:'none',identityImpact:'none',examples:[{args:{},why:'Check what may deform.'}]},
 {name:'scene.history',mcp:'get_history',cli:'history',kind:'query',summary:'Transactions with labels and undo tokens; whether undo/redo is possible.',when:'When the human refers to earlier versions ("como estaba antes").',input:o({limit:{type:'integer',minimum:1,maximum:100}}),returns:'{revision, entries:[{revision,token,label,time}], canUndo, canRedo}',sideEffects:'none',reversible:'n/a',preview:'none',identityImpact:'none',examples:[{args:{limit:10},why:'Find a previous state.'}]},
 {name:'choices.inspect',mcp:'inspect_choices',cli:'choices inspect',kind:'query',summary:'Current choice board: options (id, position 1..n, label, description), per-slot parameters, combinable slots, preview PNG paths you can open, human notes and history.',when:'Whenever the human talks about options ("la primera", "los ojos de la tercera").',input:o({}),returns:'{id,status,revision,options:[{id,position,label,slots,previewPath}],combinableSlots,notes}',sideEffects:'none',reversible:'n/a',preview:'returned',identityImpact:'none',examples:[{args:{},why:'Map "la primera" to option A.'}]},
 {name:'export.capabilities',mcp:'export_capabilities',cli:'export capabilities',kind:'query',summary:'Export targets and which features of this scene each can represent; unsupported features are explained with options (never silent degradation).',when:'Before exporting or promising a format.',input:o({target:str('Only this target')}),returns:'{features, targets:[{id,status,unsupported,options}]}',sideEffects:'none',reversible:'n/a',preview:'none',identityImpact:'none',examples:[{args:{target:'lottie'},why:'Check Lottie fidelity.'}]},
 {name:'part.resolve',mcp:'resolve_part',cli:'resolve',kind:'query',summary:'Resolve a part address to semantic nodes and SVG IDs, or return AMBIGUOUS_TARGET / NOT_FOUND with candidates and suggestions.',when:'Before acting on a part named by the human.',input:o({ref},['ref']),returns:'{nodes, ids, addresses}',sideEffects:'none',reversible:'n/a',preview:'none',identityImpact:'none',examples:[{args:{ref:'candy.flask.smoke'},why:'Get IDs of the smoke.'}]},
 {name:'comments.list',mcp:'list_comments',cli:'comments',kind:'query',summary:'Human comments pinned to canvas regions/parts/timecodes with screenshot paths and replies.',when:'When inbox reports comment.created, or at session start.',input:o({status:str('open | answered | resolved',{enum:['open','answered','resolved']})}),returns:'{comments:[{id,text,time,targets,parts,region,screenshot:{path},replies}]}',sideEffects:'none',reversible:'n/a',preview:'returned',identityImpact:'none',examples:[{args:{status:'open'},why:'Read pending art direction.'}]},
 {name:'inbox.wait',mcp:'wait_inbox',cli:'inbox',kind:'session',summary:'Long-poll human events (comments, choice notes, choices made, editor edits) after a cursor.',when:'After proposing options or asking the human something in the editor.',input:o({after:{type:'integer',minimum:0},wait:num('Seconds to wait (max 600)',0,600),types:arr('Event types',str('type'),20)}),returns:'{cursor, events:[{seq,type,data,_next}]}',sideEffects:'none',reversible:'n/a',preview:'none',identityImpact:'none',examples:[{args:{after:0,wait:300},why:'Wait for the human to pick.'}]},
 {name:'audit',mcp:'run_audit',cli:'audit',kind:'query',summary:'Deterministic detectors: broken refs, empty masks/clips, NaN, raster, scripts, orphan rig/tracks, impossible morphs, loop seams, warp folds, unprotected features, budgets per delivery profile.',when:'After structural edits and before export.',input:o({profile:str('Delivery profile budget',{enum:['editable','archive','high-quality','web','web-light','animation','mobile','game','sprite','icon']})}),returns:'{summary, findings:[{code,severity,message,repair,target}]}',sideEffects:'none',reversible:'n/a',preview:'none',identityImpact:'none',examples:[{args:{profile:'game'},why:'Check budgets before handing to the game.'}]},
 {name:'critique',mcp:'critique_motion',cli:'critique',kind:'query',summary:'Deterministic motion craft checks (pops, jerk, loop seams, squash, stiff secondary, identity drift) plus a rubric for YOUR visual judgement of rendered frames.',when:'After animating; report metrics and visual judgement separately.',input:o({samples:{type:'integer',minimum:8,maximum:600}}),returns:'{deterministic:{findings,scores}, visual:{rubric}}',sideEffects:'none',reversible:'n/a',preview:'none',identityImpact:'none',examples:[{args:{},why:'Catch pops before showing the human.'}]},
 {name:'performance',mcp:'profile_performance',cli:'profile',kind:'query',summary:'Cost model: counts, animated points, engine frame time, hotspots by region and reasons the animation may be slow.',when:'When the human says it is slow or before choosing a delivery profile.',input:o({}),returns:'{counts, engine, hotspots, reasons}',sideEffects:'none',reversible:'n/a',preview:'none',identityImpact:'none',examples:[{args:{},why:'Answer "¿por qué va lenta?"'}]},
 // ── Proposals: boards and candidates (no revision change) ───────────────────────────────
 {name:'expression.propose',mcp:'propose_expression',cli:'expression propose',kind:'proposal',summary:'Render 2–6 interpretations of an emotion distributed over facial slots (mouth/eyes/brows/ears) as a choice board with previews.',when:'The human asks for an emotion or for options to choose from.',input:o({emotion:str('Parameter name: sadness, happiness, anger, fear, surprise, tiredness or any defined parameter'),intensity:num('0–1',0,1),count:{type:'integer',minimum:2,maximum:6},time:num('Preview/keyframe time in seconds',0),slots:arr('Slots to vary',str('slot'),8),preserve:arr('Slots that must stay original in every option',str('slot'),8),prompt:str('Question shown to the human'),recommended:str('Option id you recommend'),reason:str('Why you recommend it'),previewRegion:box,previewScale:{type:'number',enum:[1,2],description:'1 = logical size (default), 2 = crisp crops'},expectedRevision:rev},['emotion','intensity','expectedRevision']),returns:'{choice:{id,options:[{id,label,previewPath}]}}',sideEffects:'Writes the pending board and preview PNGs; the scene is unchanged.',reversible:'dismiss',preview:'returned',identityImpact:'none',examples:[{args:{emotion:'sadness',intensity:.7,count:3,time:1,expectedRevision:12},why:'Three readings of sadness before deciding.'}]},
 {name:'choice.propose',mcp:'propose_choice',cli:'choices propose',kind:'proposal',summary:'Propose any 2–6 alternatives built from explicit operations or combinable specs; previews are rendered on a copy.',when:'Ambiguous art decisions (pose, color, smoke direction, rig, simplification).',input:o({request:choiceRequest,expectedRevision:rev},['request','expectedRevision']),returns:'{choice}',sideEffects:'Writes the pending board.',reversible:'dismiss',preview:'returned',identityImpact:'none',examples:[{args:{request:{id:'smoke-dir',prompt:'¿Hacia dónde sale el humo?',recommended:'A',reason:'Sigue la inclinación del frasco',options:[{id:'A',label:'Derecha',description:'Sigue el frasco',ops:[{type:'modifier.update',id:'smoke-flow',direction:{x:.4,y:-1}}]},{id:'B',label:'Vertical',description:'Sube recto',ops:[{type:'modifier.update',id:'smoke-flow',direction:{x:0,y:-1}}]}]},expectedRevision:3},why:'Ask before changing direction.'}]},
 {name:'variant.combine',mcp:'combine_variants',cli:'variant combine',kind:'proposal',summary:'Derive a new option from the board: base option + slots taken from other options + slots preserved as original + intensity scaling. Renders a preview; set apply:true only when the human already decided.',when:'"la primera pero con los ojos de la tercera", "mezcla esas dos", "conserva la boca".',input:o({base:str('Base option id (map ordinals yourself: first → position 1)'),take:map('slot → option id, e.g. {"eyes":"C"}',str('option id')),preserve:arr('Slots that keep the ORIGINAL (unexpressed) geometry',str('slot',{enum:SLOTS}),8),scale:map('slot or "*" → intensity factor 0–4 (e.g. {"*":0.8} = 20% less)',num('factor',0,4)),apply:bool('Also apply it now (counts as the human choosing it). Requires expectedRevision.'),label:str('Short label'),expectedRevision:rev},['base','expectedRevision']),returns:'{option:{id,label,params,previewPath}, applied?:{revision,undoToken}}',sideEffects:'Adds an option to the board; with apply:true commits a transaction.',reversible:'undoToken',preview:'returned',identityImpact:'reported',examples:[{args:{base:'A',take:{eyes:'C'},preserve:['mouth'],expectedRevision:12},why:'Base A, eyes from C, original mouth.'}]},
 {name:'choice.regenerate',mcp:'regenerate_choices',cli:'choices regenerate',kind:'proposal',summary:'Replace a generated board with fresh interpretations, optionally keeping slots original or changing intensity.',when:'"ninguna me convence", "dame otras tres".',input:o({count:{type:'integer',minimum:2,maximum:6},keep:arr('Slots to keep original',str('slot'),8),intensity:num('0–1',0,1),expectedRevision:rev},['expectedRevision']),returns:'{choice}',sideEffects:'Rewrites the pending board.',reversible:'no',preview:'returned',identityImpact:'none',examples:[{args:{count:3,keep:['mouth'],expectedRevision:12},why:'New options without touching the mouth.'}]},
 {name:'choice.note',mcp:'note_choice',cli:'choices note',kind:'proposal',summary:'Record the human\'s exact words on the board (context for later turns and for the editor).',when:'Every time the human gives feedback about the board.',input:o({text:str('Verbatim human text'),author:str('user | agent',{enum:['user','agent']})},['text']),returns:'{note}',sideEffects:'Appends a note.',reversible:'no',preview:'none',identityImpact:'none',examples:[{args:{text:'Me gusta la primera pero con los ojos de la tercera',author:'user'},why:'Keep provenance.'}]},
 {name:'part.candidates',mcp:'find_part_candidates',cli:'part candidates',kind:'proposal',summary:'Promptable segmentation over vector geometry from a point/box/region: up to 6 candidate regions with confidence, path counts and bounds; optionally a choice board with highlighted previews so the human confirms.',when:'A part is unknown, ambiguous or NOT_FOUND ("anima el humo" but no smoke part exists).',input:o({point,box,region,negative:arr('Points that are NOT the part',point,20),scope:ref,propose:o({id:str('Node id to create'),role:str('Role'),label:str('Human label')},['id','role','label']),previewRegion:box,expectedRevision:rev}),returns:'{candidates:[{id,label,method,confidence,paths,bounds}], choice?}',sideEffects:'With propose: writes a board.',reversible:'dismiss',preview:'returned',identityImpact:'none',examples:[{args:{box:{x:474,y:52,width:163,height:172},propose:{id:'smoke',role:'smoke',label:'Humo'},expectedRevision:4},why:'Let the human pick which region is the smoke.'}]},
 // ── Mutations: one transaction each, undoable with undoToken ────────────────────────────
 {name:'choice.choose',mcp:'choose_option',cli:'choices choose',kind:'mutation',summary:'Apply a board option as a transaction (only after the human decided, in the editor or in their own words).',when:'The human picked an option.',input:mutation({option:str('Option id'),id:str('Board id (default: current)'),text:str('The human words that decided it')},['option']),returns:'{revision, undoToken, changes}',sideEffects:'Commits; board becomes chosen.',reversible:'undoToken',preview:'recommended',identityImpact:'reported',examples:[{args:{option:'D',text:'esa',expectedRevision:12},why:'Commit the combined option.'}]},
 {name:'choice.dismiss',mcp:'dismiss_choice',cli:'choices dismiss',kind:'mutation',summary:'Close the pending board without applying anything.',when:'The human postpones or rejects all options.',input:o({id:str('Board id'),expectedRevision:rev},['expectedRevision']),returns:'{choice}',sideEffects:'Board status dismissed.',reversible:'no',preview:'none',identityImpact:'none',examples:[{args:{expectedRevision:12},why:'Nothing chosen.'}]},
 {name:'part.label',mcp:'label_part',cli:'part label',kind:'mutation',summary:'Create/update a semantic part (persistent knowledge of the asset): role, label, SVG targets, parent, landmarks, region, protection.',when:'After the human confirms what a region is, or when you identify parts with certainty.',input:mutation({id:str('Node id (becomes part of addresses, e.g. "smoke")'),role:str('character, head, eye-left, eye-right, nose, mouth, ear-left, tail, flask, liquid, smoke, …'),label:str('Human label'),targets:arr('SVG ids',str('id'),5000),parent:str('Parent node id'),landmarks:map('name → {x,y}',point),region,protection:levels,status:str('confirmed | proposed',{enum:['confirmed','proposed']})},['id','role','label']),returns:'{part:{id,address}}',sideEffects:'Stores semantics in the asset metadata.',reversible:'undoToken',preview:'none',identityImpact:'none',examples:[{args:{id:'smoke',role:'smoke',label:'Humo del frasco',parent:'flask',targets:['candy-smoke'],expectedRevision:5},why:'Name the smoke once; next time use candy.flask.smoke.'}]},
 {name:'part.extract',mcp:'extract_part',cli:'part extract',kind:'mutation',summary:'Copy the real artwork inside a region into its own alpha-preserving, editable layer (pixel-identical at rest) and hide the source there; labels it as a part.',when:'A part is baked into a big trace (converted PNG) and must move or deform independently.',input:mutation({id:str('New layer/node id'),name:str('Layer name'),source:ref,region,role:str('Semantic role'),parent:str('Parent node id'),alpha:bool('Copy the alpha mask (default true)'),margin:num('Selection margin in px',0,200)},['id','name','source','region']),returns:'{part, paths, alphaPaths}',sideEffects:'Structural edit (new layer, clip, mask).',reversible:'undoToken',preview:'recommended',identityImpact:'reported',examples:[{args:{id:'smoke',name:'Humo original',source:'#mai-artwork',region:{kind:'rect',x:474,y:52,width:163,height:172},role:'smoke',parent:'flask',expectedRevision:5},why:'Animate the smoke that already exists.'}]},
 {name:'identity.preserve',mcp:'protect_identity',cli:'identity preserve',kind:'mutation',summary:'Protect parts with identity levels; by default also freezes their expression rig so they keep the original geometry.',when:'"conserva la boca", "no le cambies los ojos", before risky edits.',input:mutation({targets:arr('Part addresses',ref,64),levels,freezeExpression:bool('Freeze expression warps of these parts (default true unless levels allow deformation)')},['targets']),returns:'{changes:{parts,levels,frozen}}',sideEffects:'Stores protection; later operations that violate it fail with IDENTITY_BLOCKED.',reversible:'undoToken',preview:'none',identityImpact:'guarded',examples:[{args:{targets:['mouth'],expectedRevision:12},why:'Mouth stays exactly as drawn.'}]},
 {name:'identity.release',mcp:'release_identity',cli:'identity release',kind:'mutation',summary:'Remove protection and unfreeze expression of parts (explicit, logged).',when:'Only when the human allows changing a protected part.',input:mutation({targets:arr('Part addresses',ref,64)},['targets']),returns:'{changes}',sideEffects:'Protection removed.',reversible:'undoToken',preview:'none',identityImpact:'reported',examples:[{args:{targets:['mouth'],expectedRevision:13},why:'Human allowed reshaping the mouth.'}]},
 {name:'preservation.set',mcp:'set_preservation',cli:'identity mode',kind:'mutation',summary:'strict (≤8% landmark motion), balanced (≤20%), free (≤45%): caps every expression deformation relative to feature size.',when:'Human asks to keep features strictly or to exaggerate.',input:mutation({mode:str('strict | balanced | free',{enum:['strict','balanced','free']})},['mode']),returns:'{changes}',sideEffects:'Changes evaluation of all expressions.',reversible:'undoToken',preview:'recommended',identityImpact:'reported',examples:[{args:{mode:'strict',expectedRevision:7},why:'"sin cambiarlos tanto".'}]},
 {name:'expression.rig',mcp:'rig_expression',cli:'expression rig',kind:'mutation',summary:'Create an identity-preserving expression feature on a part: boundary pins + landmarks; role templates (mouth: left,right,center,lower; eye: inner,outer,upper,lower,iris; brow: inner,middle,outer; ear: base,tip) generate shape keys for sadness, happiness, anger, fear, surprise, tiredness, mouth-open/wide/round, look-x/y…',when:'Before expressions on a converted character; the part must contain real paths (part.extract first).',input:mutation({part:ref,role:str('mouth | eye-left | eye-right | brow-left | brow-right | ear-left | ear-right | custom role'),landmarks:map('name → {x,y} in document space',point),region,rigid:map('landmark → SVG ids that move rigidly with it (e.g. iris)',arr('ids',str('id'),500)),id:str('Feature id (default: part id)')},['part','role','landmarks']),returns:'{feature:{id,params,landmarks,paths,sizePx}}',sideEffects:'Stores rest geometry and keys.',reversible:'undoToken',preview:'recommended',identityImpact:'guarded',examples:[{args:{part:'mouth',role:'mouth',landmarks:{left:{x:331,y:234},right:{x:358,y:230},center:{x:341.5,y:227},lower:{x:346,y:232}},expectedRevision:8},why:'Make the original mouth expressive.'}]},
 {name:'expression.apply',mcp:'apply_expression',cli:'expression apply',kind:'mutation',summary:'Set expression parameters (global "sadness" or slot-scoped "sadness@mouth") statically or as keyframes on the expression layer; values blend additively with blink/lipsync layers.',when:'After a choice, or for direct requests ("un poco menos triste" → you compute the new values).',input:mutation({params:map('parameter → value (0–1, look-x/y −1–1)',num('value',-1,1)),time:num('Keyframe time (omit for static)',0),layer:str('Layer id (default expression)'),easing:str('linear | ease-in-out | ease-in | ease-out | overshoot | anticipate | step | cubic-bezier(a,b,c,d)')},['params']),returns:'{changes:{param:{from,to}}}',sideEffects:'Parameter defaults or keyframes.',reversible:'undoToken',preview:'recommended',identityImpact:'guarded',examples:[{args:{params:{'sadness@mouth':.5,'sadness@eyes':.8},expectedRevision:12},why:'Sad mostly in the eyes.'}]},
 {name:'animation.adjust',mcp:'adjust_animation',cli:'animate adjust',kind:'mutation',summary:'Adjust how a part moves: speed, amplitude, turbulence, direction (flow modifiers), gain/stiffness/damping/delay (secondary motion), intensity (expression tracks), timing (retime its keyframes). Reports from→to per source.',when:'"el humo va muy rápido, bájalo 30%", "que la cola rebote menos", "más pesado".',input:mutation({target:ref,property:str('speed | amplitude | turbulence | direction | intensity | timing | gain | stiffness | damping | delay',{enum:['speed','amplitude','turbulence','direction','intensity','timing','gain','stiffness','damping','delay']}),scale:num('Multiply current value (0.7 = 30% less)',0,20),set:num('Absolute value'),add:num('Add to current value'),direction:point},['target','property']),returns:'{changes:{source:{property:{from,to}}}}',sideEffects:'Updates modifiers/secondary/tracks of the part.',reversible:'undoToken',preview:'recommended',identityImpact:'reported',examples:[{args:{target:'candy.flask.smoke',property:'speed',scale:.7,expectedRevision:12},why:'Smoke 30% slower.'}]},
 {name:'fluid.animate',mcp:'animate_fluid',cli:'fluid animate',kind:'mutation',summary:'Turn EXISTING artwork (smoke, steam, water, fire, lava, hair, cloth, grass…) into flowing motion: curl-noise flow field + traveling waves anchored at the emitter, preserving the original silhouette and alpha. Technique geometry (exact, editable) or filter (feTurbulence/feDisplacementMap, light export).',when:'"que el humo se vea fluido", "anima el agua". Never replaces the drawing with a template.',input:mutation({target:ref,region,source:ref,preset:str('smoke | steam | fog | cloud | water | wave | river | rain | wind | fire | lava | magic | electricity | dust | snow | cloth | hair | grass',{enum:['smoke','steam','fog','cloud','water','wave','river','rain','wind','fire','lava','magic','electricity','dust','snow','cloth','hair','grass']}),technique:str('geometry | filter',{enum:['geometry','filter']}),quality:str('draft | balanced | high',{enum:['draft','balanced','high']}),anchor:point,direction:point,params:map('amplitude, scale, speed, swirl, wave, waveLength, anchorRadius, growth, cycles (fractions of the part size except cycles)',num('value')),id:str('Modifier id')},['preset']),returns:'{modifier:{id,targets,preset,technique}, part}',sideEffects:'Adds a non-destructive modifier (and extracts the region if given).',reversible:'undoToken',preview:'recommended',identityImpact:'reported',examples:[{args:{target:'candy.flask.smoke',preset:'smoke',expectedRevision:9},why:'Make the drawn smoke flow.'}]},
 {name:'motion.spring',mcp:'add_spring',cli:'motion spring',kind:'mutation',summary:'Physically inspired secondary motion: a part follows a driver with spring, damping, inertia, delay, overshoot (no manual keyframes). Presets: tail, ears, hair, cloth, antenna, accessory, plant.',when:'"que la cola siga el salto con retraso suave".',input:mutation({target:ref,driver:ref,preset:str('tail | ears | hair | cloth | antenna | accessory | plant',{enum:['tail','ears','hair','cloth','antenna','accessory','plant']}),property:str('rotation | x | y',{enum:['rotation','x','y']}),driverProperty:str('x | y | rotation | scaleX | scaleY',{enum:['x','y','rotation','scaleX','scaleY']}),pivot:point,overrides:map('stiffness, damping, gain, delay, limit',num('value')),id:str('Secondary id')},['target','driver']),returns:'{secondary}',sideEffects:'Adds secondary motion evaluated per frame.',reversible:'undoToken',preview:'recommended',identityImpact:'reported',examples:[{args:{target:'tail',driver:'candy',preset:'tail',driverProperty:'y',expectedRevision:10},why:'Tail follow-through on jumps.'}]},
 {name:'motion.preset',mcp:'add_motion',cli:'motion preset',kind:'mutation',summary:'Keyframe recipes on a part: float, spin, pulse, fade, breathe, bounce, sway; on additive layers they stack over existing motion.',when:'Quick base motion (breathing, idle).',input:mutation({target:ref,kind:str('float | spin | pulse | fade | breathe | bounce | sway',{enum:['float','spin','pulse','fade','breathe','bounce','sway']}),amplitude:num('Amplitude'),layer:str('Layer id (pose is additive)')},['target','kind']),returns:'{changes}',sideEffects:'Adds tracks.',reversible:'undoToken',preview:'recommended',identityImpact:'reported',examples:[{args:{target:'candy',kind:'breathe',layer:'pose',expectedRevision:10},why:'Slow breathing.'}]},
 {name:'morph.apply',mcp:'morph_path',cli:'morph',kind:'mutation',summary:'Morph a path into any other path: normalizes topology (cubic conversion, subdivision, start-point search, subpath matching) and keyframes it; reports self-intersections.',when:'Shape changes between incompatible paths.',input:mutation({target:ref,to:str('Path data or #id of another path'),time:num('End time',0),from:num('Start time',0),easing:str('easing')},['target','to','time']),returns:'{analysis, changes}',sideEffects:'Adds d keyframes.',reversible:'undoToken',preview:'recommended',identityImpact:'guarded',examples:[{args:{target:'#tear',to:'#tear-drop',time:1,expectedRevision:11},why:'Tear forms.'}]},
 {name:'timeline.set',mcp:'set_timeline',cli:'timeline set',kind:'mutation',summary:'Duration, fps, loop; retime factor (>1 faster) over a range; layer mute/solo/weight; markers.',when:'Global timing changes.',input:mutation({duration:num('seconds',.1,300),fps:num('fps',1,60),loop:bool('loop'),retime:num('Speed factor >1 faster',.05,20),start:num('Range start',0),end:num('Range end',0),layer:o({id:str('layer'),blend:str('override | additive',{enum:['override','additive']}),weight:num('0–1',0,1),mute:bool('mute'),solo:bool('solo'),locked:bool('locked')},['id']),marker:o({id:str('id'),time:num('s',0),label:str('label')},['id','time','label'])},[]),returns:'{changes}',sideEffects:'Timeline metadata.',reversible:'undoToken',preview:'none',identityImpact:'none',examples:[{args:{retime:.8,expectedRevision:12},why:'Everything 20% slower.'}]},
 {name:'ops.apply',mcp:'apply_operations',cli:'apply',kind:'mutation',summary:'Low-level escape hatch: 1–500 core operations (see packages/core/model.ts Operation) as one atomic transaction.',when:'Only when no high-level tool expresses the change.',input:mutation({ops:{...arr('Core operations',operation,500),minItems:1}},['ops']),returns:'{changes, undoToken}',sideEffects:'Commits the operations.',reversible:'undoToken',preview:'recommended',identityImpact:'guarded',examples:[{args:{ops:[{type:'pose',id:'candy-head',pose:{rotation:-3}}],expectedRevision:12},why:'Precise pose tweak.'}]},
 {name:'history.undo',mcp:'undo',cli:'undo',kind:'mutation',summary:'Undo the latest transaction; with token, only if that token is still the latest (prevents undoing someone else\'s edit).',when:'A result is wrong or the human says "deshazlo".',input:o({token:str('undoToken from a mutation result'),expectedRevision:rev},['expectedRevision']),returns:'{revision}',sideEffects:'Restores the previous state.',reversible:'no',preview:'none',identityImpact:'none',examples:[{args:{token:'rev:13',expectedRevision:13},why:'Revert my last change.'}]},
 {name:'history.redo',mcp:'redo',cli:'redo',kind:'mutation',summary:'Redo the last undone transaction.',when:'After an accidental undo.',input:o({expectedRevision:rev},['expectedRevision']),returns:'{revision}',sideEffects:'Re-applies.',reversible:'no',preview:'none',identityImpact:'none',examples:[{args:{expectedRevision:12},why:'Bring it back.'}]},
 {name:'comments.reply',mcp:'reply_comment',cli:'comments reply',kind:'mutation',summary:'Answer a human comment (optionally linking a choice board) and set its status.',when:'After acting on a comment.',input:o({id:str('Comment id'),text:str('Reply'),status:str('open | answered | resolved',{enum:['open','answered','resolved']}),choice:str('Board id')},['id','text']),returns:'{comment}',sideEffects:'Comment updated (no revision).',reversible:'no',preview:'none',identityImpact:'none',examples:[{args:{id:'c-1a2b',text:'Bajé el humo un 30 %; mira el preview.',status:'answered'},why:'Close the loop.'}]},
 // ── Agent IR v1: several intents, one atomic transaction ────────────────────────────────
 {name:'plan.execute',mcp:'execute_plan',cli:'execute',kind:'mutation',summary:'Execute a mai.agent-plan/v1: constraints (preserve parts against a snapshot/baseline) + commands (variant.apply, identity.preserve, animation.adjust) compiled on a draft, validated (structural/identity/perceptual gates), previewed, and committed as ONE transaction with one undoToken. mode "dry-run" changes nothing. requestId is an idempotency key.',when:'Whenever one human request maps to several changes ("la primera con los ojos de la tercera, conserva la boca y baja 30% el humo").',input:{type:'object',additionalProperties:false,required:['plan'],properties:{plan:PLAN_SCHEMA as Schema}},returns:'mai.agent-result/v1 {status: prepared|committed|running, committed, baseRevision, revision, snapshotId, transaction:{id,undoToken}, changes[], identity:{status,evaluatedParts,evaluatedTimes}, artifacts[], warnings[]}',sideEffects:'dry-run: draft snapshot + preview files. commit: one document transaction (scene + decisions + receipt in the journal).',reversible:'undoToken',preview:'returned',identityImpact:'guarded',examples:[{args:{plan:PLAN_EXAMPLE},why:'Illustrative IDs: read sessionId/documentId/snapshotId/board version/sourceId from scene.inspect and choices.inspect first.'}]},
 {name:'plan.status',mcp:'plan_status',cli:'execution',kind:'query',summary:'Receipt of a plan by requestId (after a timeout or restart): running, prepared, committed or unknown.',when:'Before retrying a plan whose response you did not receive.',input:o({requestId:str('requestId of the plan')},['requestId']),returns:'receipt',sideEffects:'none',reversible:'n/a',preview:'none',identityImpact:'none',examples:[{args:{requestId:'direction-candy-001'},why:'Did it commit?'}]},
 {name:'plan.cancel',mcp:'cancel_plan',cli:'execution cancel',kind:'session',summary:'Cancel a running plan before its commit (no effect after commit).',when:'The human changed their mind while previews render.',input:o({requestId:str('requestId')},['requestId']),returns:'{status}',sideEffects:'Stops the plan before commit.',reversible:'n/a',preview:'none',identityImpact:'none',examples:[{args:{requestId:'direction-candy-001'},why:'Stop.'}]},
 // ── Render and verification ─────────────────────────────────────────────────────────────
 {name:'preview.render',mcp:'render_preview',cli:'preview',kind:'render',summary:'Render the current scene (or a dry-run) at given times to PNG files you can open; optional crop to a region or part.',when:'After every meaningful change and before showing the human.',input:o({times:arr('Seconds (max 8)',num('',0),8),region:box,part:ref,scale:num('Device scale 0.25–4 (2 = crisp crops)',.25,4)}),returns:'{frames:[{time,path,width,height}]}',sideEffects:'Writes PNGs under .cache/previews.',reversible:'n/a',preview:'returned',identityImpact:'none',examples:[{args:{times:[0,1.5],part:'head'},why:'Look at the face.'}]},
 {name:'compare.frames',mcp:'compare_frames',cli:'compare',kind:'render',summary:'Perceptual comparison between the current state and the state before the last transaction (or the rest pose): MAE, SSIM, silhouette IoU per time and per part.',when:'To prove a change did not damage what should stay.',input:o({against:str('previous | rest',{enum:['previous','rest']}),times:arr('Seconds',num('',0),8),parts:arr('Part addresses to measure separately',ref,16)}),returns:'{frames:[{time,mae,ssim,iou,parts:{…}}]}',sideEffects:'Writes PNGs.',reversible:'n/a',preview:'returned',identityImpact:'none',examples:[{args:{against:'previous',times:[1],parts:['mouth']},why:'Mouth unchanged after editing smoke.'}]},
 {name:'identity.check',mcp:'check_identity',cli:'identity check',kind:'render',summary:'Identity verification with an explicit reference and real coverage: snapshot (the state you observed), baseline (approved original, hash-checked) or rig-rest (expression displacement only). Protected/frozen parts must match (MAE ≤ threshold), deformable parts must stay within the landmark budget, silhouette-preserved parts need rendered-mask IoU ≥ 0.9. Status pass | fail | not_evaluated (nothing measurable is never a pass).',when:'After expressions/animation on a character and before declaring done; regression against a baseline before delivery.',input:o({reference:{type:'object',description:'{kind:"snapshot",id} | {kind:"baseline",id} | {kind:"rig-rest"}',properties:{kind:str('snapshot | baseline | rig-rest',{enum:['snapshot','baseline','rig-rest']}),id:str('Snapshot id (scene.inspect.snapshotId) or baseline id')},required:['kind'],additionalProperties:false},parts:{...arr('Part addresses to evaluate',ref,32),minItems:1},times:{...arr('Seconds',num('',0),12),minItems:1},threshold:num('MAE limit for parts expected unchanged (default by preservation mode)',0,64)},['reference','parts','times']),returns:'{status, pass, reference, evaluatedParts, skipped, evaluated:[{part,time,expectation,status,mae,ssim,silhouetteIoU,landmarkDriftPx,budgetPx}]}',sideEffects:'Writes temporary renders.',reversible:'n/a',preview:'none',identityImpact:'none',examples:[{args:{reference:{kind:'snapshot',id:'snap-doc-r12-abc'},parts:['mouth','nose'],times:[0,1.5]},why:'Prove the mouth and nose did not change.'}]},
 {name:'baseline.capture',mcp:'capture_baseline',cli:'baseline capture',kind:'mutation',summary:'Register an immutable identity baseline: a project file (e.g. the approved conversion) or the current state, stored by sha256. Created baselines are "unreviewed" until a human approves them.',when:'Before a long editing session on a character, to compare later.',input:mutation({id:str('Baseline id'),label:str('Description'),file:str('Project-relative SVG path; omit to capture the current state')},['id']),returns:'{changes:{baseline,source,sha256}}',sideEffects:'Adds baseline metadata (and a snapshot file when capturing current state).',reversible:'undoToken',preview:'none',identityImpact:'none',examples:[{args:{id:'approved',file:'assets/vector/candy_alchemist_cat.svg',expectedRevision:3},why:'Compare against the approved conversion.'}]},
 {name:'export',mcp:'export_scene',cli:'export',kind:'render',summary:'Export editable (keeps MAI metadata) or standalone (SMIL, no scripts/raster) with explicit budgets; never degrades silently.',when:'Delivering.',input:o({profile:str('editable | standalone',{enum:['editable','standalone']}),output:str('Output file path inside the project'),expectedRevision:rev},['profile','expectedRevision']),returns:'{savedFile, report}',sideEffects:'Writes a file under exports/.',reversible:'n/a',preview:'none',identityImpact:'none',examples:[{args:{profile:'standalone',expectedRevision:14},why:'Deliver.'}]},
];
// Availability is evidence-based: experimental tools work but lack an external end-to-end benchmark or calibration.
const EXPERIMENTAL:Record<string,string>={'fluid.animate':'Flow fields on existing geometry; artistic tuning per asset pending.','motion.spring':'Secondary motion validated on fixtures, not on Candy rigs.','morph.apply':'Topology normalization tested on simple paths.','part.candidates':'Vector promptable segmentation is heuristic; confirm with the human.','expression.rig':'Templates calibrated on fixtures; landmark placement is manual.','critique':'Deterministic checks only; visual judgement is yours.','performance':'Cost model, not measured paint time.','export.capabilities':'Several targets are planned, not implemented.','expression.propose':'Interpretations are heuristic distributions; the human chooses.'};
// MCP destructiveHint: clients ask the human before these. Undo/redo are journaled and reverse each other, so they are not
// destructive (an agent must be able to undo its own transaction); raw ops can delete, dismiss/regenerate drop board options.
const DESTRUCTIVE=new Set(['identity.release','choice.dismiss','ops.apply','choice.regenerate']);
// Every response is an envelope; tools add their own fields. plan.execute returns mai.agent-result/v1.
export const ENVELOPE_SCHEMA:Schema={type:'object',required:['ok'],properties:{ok:{type:'boolean'},tool:{type:'string'},revision:{type:'integer'},error:{type:'object',required:['code','message'],properties:{code:{type:'string'},message:{type:'string'}}}}};
const RESULT_SCHEMA:Schema={type:'object',required:['ok'],properties:{ok:{type:'boolean'},protocol:{type:'string',const:'mai.agent-result/v1'},requestId:{type:'string'},status:{type:'string',enum:['prepared','committed','running','unknown','cancelling']},committed:{type:'boolean'},baseRevision:{type:'integer'},revision:{type:'integer'},snapshotId:{type:'string'},transaction:{type:'object',properties:{id:{type:'string'},undoToken:{type:'string'}}},changes:{type:'array'},identity:{type:'object'},artifacts:{type:'array'},warnings:{type:'array'},error:{type:'object'}}};
for(const t of TOOLS){t.availability=EXPERIMENTAL[t.name]?{status:'experimental',note:EXPERIMENTAL[t.name]}:{status:'stable'};t.destructive=DESTRUCTIVE.has(t.name);t.outputSchema=t.name.startsWith('plan.')?RESULT_SCHEMA:ENVELOPE_SCHEMA;}
export const toolByName=(name:string)=>TOOLS.find(t=>t.name===name||t.mcp===name);
export const CONVENTIONS={workflow:['inspect (scene.inspect / choices.inspect / scene.identity)','plan in your head: map human words → tools; ask only if a part is truly ambiguous','dryRun:true for risky or identity-touching changes','apply with expectedRevision','preview.render and look at the PNGs','identity.check / compare.frames / critique / audit','explain to the human what changed and show previews','iterate on feedback; undo with undoToken if wrong'],
 envelope:'Every response: {ok, tool, revision, …}. Mutations add {operation, target, changes, identityImpact, undoToken, transaction}. Errors: {ok:false, error:{code,message,candidates?,suggestions?,hint?}}.',
 errors:{REVISION_CONFLICT:'Someone edited meanwhile: re-inspect and re-plan.',AMBIGUOUS_TARGET:'Several parts match: show candidates or pick by context; never guess silently.',NOT_FOUND:'No such part: use suggestions or part.candidates.',IDENTITY_BLOCKED:'The change violates a protected part: change approach or ask before identity.release.',INVALID_ARGUMENT:'Fix arguments per schema.',NOT_COMBINABLE:'Board options lack specs: build a new board with explicit ops.',STALE_CHOICE:'Board was rendered for an older revision: regenerate.',UNDO_NOT_LATEST:'Your token is not the latest transaction; inspect history.'},
 identityImpact:{none:'No protected or expressive part touched.',rigid:'Only rigid moves of protected parts.',expression:'Expressive parts deform within the preservation budget.',changed:'Protected/expressive geometry or style changed (should be rare and intentional).'},
 language:'MAI never interprets natural language. You (the agent) map the human\'s words to these tools using inspect results, previews and history.'};
