import {writeFile,mkdir,readFile} from 'node:fs/promises';import {sha256} from '../server/snapshots.js';import {join} from 'node:path';import {randomUUID} from 'node:crypto';import sharp from 'sharp';
import {VectorDocument} from '../core/document.js';
import type {Operation,SemanticNode,ProtectionLevel} from '../core/model.js';
import {frameParams,frameState} from '../core/animation.js';
import {pathBoxes,LEVEL_MEANING,ALLOWED} from '../core/semantic.js';
import {regionBounds} from '../core/warp.js';
import {PRESERVATION,TEMPLATES,featureDisplacements} from '../core/expression.js';
import {FLUID_PRESETS} from '../core/modifiers.js';
import {SECONDARY_PRESETS} from '../core/secondary.js';
import {PROFILES} from '../core/profiles.js';
import {detect} from '../core/detectors.js';
import {critique} from '../core/critique.js';
import {profile} from '../core/profiler.js';
import {signals} from '../core/signals.js';
import {exportCapabilities} from '../core/compat.js';
import {categories,protectedNodes} from '../core/identity-guard.js';
import {candidates} from '../core/semantic.js';
import {analyzeMorph} from '../core/morph.js';
import {exportSvg} from '../core/export.js';
import {elements} from '../converter/svg.js';
import {renderSvg} from '../server/render.js';
import {metrics,raw} from '../server/perceptual.js';
import type {Snapshots} from '../server/snapshots.js';import type {Choices} from '../server/choices.js';import type {Comments} from '../server/comments.js';import type {Inbox} from '../server/inbox.js';
import {TOOLS,CONVENTIONS,toolByName,type Schema} from './registry.js';
import type {PlanExecutor,Plan} from './plan.js';
import {Ajv2020,type ValidateFunction} from 'ajv/dist/2020.js';
import {resolve,nodes,addressOf,nodeIds,slotOfRole,AgentError,requireConfirmed} from './address.js';
export type Workspace={plans?:()=>PlanExecutor;model:()=>VectorDocument;revision:()=>number;asset:()=>string;sessionId:()=>string;documentId:()=>string;snapshots:Snapshots;cache:string;root:string;selection:()=>string[];
 apply:(ops:Operation[],expectedRevision:number,label:string,source:string)=>Promise<{revision:number;transaction:{revision:number;id:string;label:string};reload:boolean;elapsedMs:number}>;
 undo:(expectedRevision:number,token?:string)=>Promise<unknown>;redo:(expectedRevision:number)=>Promise<unknown>;history:()=>{revision:number;entries:{revision:number;id:string;label:string;time:string}[];canUndo:boolean;canRedo:boolean};
 previous:()=>VectorDocument|undefined;queued:<T>(work:()=>Promise<T>)=>Promise<T>;broadcast:(change:Record<string,unknown>)=>void;choices:Choices;comments:Comments;inbox:Inbox;
 exportFile:(profile:'editable'|'standalone',expectedRevision:number)=>Promise<{savedFile:string;report:unknown}>};
type Result=Record<string,unknown>;
// Schema validation with a pinned standard validator (Ajv 8, JSON Schema 2020-12). One validator for every
// transport; errors carry JSON paths so the agent can fix its call.
const ajv=new Ajv2020({allErrors:true,strict:false});const compiled=new Map<Schema,ValidateFunction>();
export function validate(schema:Schema,value:unknown,path='args'):void{let v=compiled.get(schema);if(!v){v=ajv.compile(schema as object);compiled.set(schema,v);}
 if(v(value===undefined?{}:value))return;
 // For unions (oneOf), report the branch the caller meant: the one whose discriminator (`const`) matched.
 const raw=v.errors??[];const branch=(e:{schemaPath:string})=>/oneOf\/(\d+)/.exec(e.schemaPath)?.[1];const wrong=new Set(raw.filter(e=>e.keyword==='const').map(branch));const relevant=raw.filter(e=>e.keyword!=='oneOf'&&!(branch(e)!==undefined&&wrong.has(branch(e))));
 const errors=(relevant.length?relevant:raw).filter(e=>e.keyword!=='if').slice(0,8).map(e=>({path:`${path}${e.instancePath.replace(/\//g,'.')}`,message:e.message??'invalid',...(e.keyword==='additionalProperties'?{property:(e.params as {additionalProperty:string}).additionalProperty}:{}),...(e.keyword==='enum'?{allowed:(e.params as {allowedValues:unknown[]}).allowedValues}:{})}));
 const first=errors.find(e=>!/must match exactly one schema in oneOf/.test(e.message))??errors[0];throw new AgentError('INVALID_ARGUMENT',`${first.path}: ${first.message}${first.property?` (${first.property})`:''}`,{path:first.path,errors});}
const round=(n:number,d=3)=>Number(n.toFixed(d));
export class AgentService{
 constructor(readonly ws:Workspace){}
 async call(name:string,args:Record<string,unknown>={}):Promise<Result>{
  const tool=toolByName(name);if(!tool)throw new AgentError('UNKNOWN_TOOL',`Unknown tool ${name}`,{tools:TOOLS.map(t=>t.name)},404);validate(tool.input,args);
  const fn=(this as unknown as Record<string,(a:Record<string,unknown>)=>Promise<Result>>)[`t_${tool.name.replace(/\./g,'_')}`];if(!fn)throw new AgentError('NOT_IMPLEMENTED',`${tool.name} is declared but not implemented`,{},501);
  const out=await fn.call(this,args);return {ok:true,tool:tool.name,revision:this.ws.revision(),...out};
 }
 private m(){return this.ws.model();}
 private expected(args:Record<string,unknown>){const v=args.expectedRevision;if(typeof v!=='number')throw new AgentError('INVALID_ARGUMENT','expectedRevision is required for this tool');if(v!==this.ws.revision())throw new AgentError('REVISION_CONFLICT',`Revision conflict: expected ${v}, current ${this.ws.revision()}`,{current:this.ws.revision()},409);return v;}
 // Identity impact is computed from the compiled operations, not from the tool name.
 private impact(ops:Operation[]){const m=this.m(),prot=protectedNodes(m);const touched=new Set<string>();let rigidOnly=true;let expression=false;
  for(const op of ops){if(['param.set','expression.set','lipsync'].includes(op.type)||(op.type==='keyframe'&&op.property==='param')||(op.type==='track.edit'&&op.property==='param'))expression=true;const {targets,cats}=categories(op);
   for(const n of prot){const related=targets.some(t=>n.targets.some(p=>{const a=m.index.get(p),e=m.index.get(t);if(!a||!e)return false;let x:Node|null=e as unknown as Node;while(x){if(x===(a as unknown as Node))return true;x=x.parentNode;}return false;}));if(related){touched.add(n.id);if(cats.some(c=>!['rigid','visibility','none'].includes(c)))rigidOnly=false;}}}
  const features=(m.project.expression?.features??[]).filter(f=>!f.frozen).map(f=>f.id);const level=touched.size?(rigidOnly?'rigid':'changed'):expression&&features.length?'expression':'none';
  return {identityImpact:level,identityParts:[...touched],...(level==='expression'?{expressionBudget:`${m.project.preservation??'balanced'}: ≤${PRESERVATION[m.project.preservation??'balanced'].maxDisplacement*100}% del tamaño de cada rasgo`,affectedFeatures:features}:{})};}
 // Commit (or dry-run) compiled operations with the standard mutation envelope.
 private async commit(tool:string,args:Record<string,unknown>,ops:Operation[],extra:{target?:unknown;changes?:unknown;warnings?:string[];next?:string}={}){
  if(!ops.length)throw new AgentError('NOTHING_TO_DO','The request compiles to no operations',{hint:'Inspect the part: it may have no animation source or already have that value.'});
  const expectedRevision=this.expected(args);const impact=this.impact(ops);const label=String(args.label??`${tool}${extra.target?` · ${typeof extra.target==='string'?extra.target:''}`:''}`).slice(0,120);
  if(args.dryRun){const draft=new VectorDocument(this.m().toSVG());draft.apply(ops);const preview=args.preview?await this.renderFrames(draft,args.preview as Record<string,unknown>,'dry'):undefined;
   return {operation:tool,dryRun:true,committed:false,target:extra.target,changes:extra.changes,...impact,operations:ops.length,audit:detect(draft).summary,...(preview?{preview}:{}),warnings:extra.warnings??[],_next:'Si el resultado es correcto, repite la llamada sin dryRun.'};}
  const r=await this.ws.apply(ops,expectedRevision,label,'agent');const preview=args.preview?await this.renderFrames(this.m(),args.preview as Record<string,unknown>,'rev'):undefined;
  return {operation:tool,committed:true,target:extra.target,changes:extra.changes,...impact,undoToken:`rev:${r.transaction.revision}`,transaction:r.transaction,operations:ops.length,elapsedMs:r.elapsedMs,...(preview?{preview}:{}),warnings:extra.warnings??[],_next:extra.next??'Renderiza (preview.render) y verifica (identity.check / critique) antes de explicar el resultado.'};}
 private one(ref:unknown,kind:'group'|'path'|'any'='any',mutate=false){const r=resolve(this.m(),String(ref));if(mutate)requireConfirmed(r);const m=this.m();let ids=r.ids;if(kind==='group'){const g=ids.filter(id=>['g','svg','use'].includes(m.index.get(id)?.localName??''));ids=g.length?g:ids;}if(kind==='path')ids=ids.filter(id=>m.index.get(id)?.localName==='path');
  if(ids.length!==1)throw new AgentError(ids.length?'AMBIGUOUS_TARGET':'NOT_FOUND',`${String(ref)} resolves to ${ids.length} SVG elements; this tool needs exactly one ${kind==='any'?'element':kind}`,{ids:ids.slice(0,20),hint:'Use a more specific address or #id.'});return {id:ids[0],resolved:r};}
 // A region-only part (e.g. a head painted inside shared artwork) scopes the search through its nearest ancestor with one element.
 private scopeOf(ref:unknown){const r=resolve(this.m(),String(ref));if(r.ids.length||r.nodes.length!==1)return this.one(ref);const all=this.m().project.semantic?.nodes??[];let n:SemanticNode|undefined=r.nodes[0];const seen=new Set<string>();
  while(n?.parent&&!seen.has(n.id)){seen.add(n.id);n=all.find(x=>x.id===n!.parent);if(n?.targets.length===1)return {id:n.targets[0],resolved:r};}return this.one(ref);}
 private deep(ref:unknown,mutate=false){const r=resolve(this.m(),String(ref));if(mutate)requireConfirmed(r);const m=this.m();const ids=new Set<string>();for(const id of r.ids){ids.add(id);const e=m.index.get(id);if(e)for(const x of elements(e)){const i=x.getAttribute('id');if(i)ids.add(i);}}for(const n of r.nodes)for(const id of nodeIds(m,n,true))ids.add(id);return {ids,resolved:r};}
 private part(n:SemanticNode,depth=8):Result{const m=this.m(),p=m.project,boxes=pathBoxes(m),deep=nodeIds(m,n,true);const bs=deep.map(id=>boxes.get(id)).filter(Boolean) as {x0:number;y0:number;x1:number;y1:number}[];
  const rb=n.region?regionBounds(n.region):undefined;const bounds=rb?{x:round(rb.x,1),y:round(rb.y,1),width:round(rb.width,1),height:round(rb.height,1)}:bs.length?{x:round(Math.min(...bs.map(b=>b.x0)),1),y:round(Math.min(...bs.map(b=>b.y0)),1),width:round(Math.max(...bs.map(b=>b.x1))-Math.min(...bs.map(b=>b.x0)),1),height:round(Math.max(...bs.map(b=>b.y1))-Math.min(...bs.map(b=>b.y0)),1)}:n.region?{region:n.region}:undefined;const set=new Set(deep);
  return {id:n.id,address:addressOf(m,n),role:n.role,label:n.label,status:n.status,...(n.confidence!==undefined?{confidence:n.confidence}:{}),protection:n.protection??[],ids:n.targets.slice(0,12),idCount:n.targets.length,paths:deep.filter(id=>m.index.get(id)?.localName==='path').length,bounds,landmarks:Object.keys(n.landmarks??{}),animated:[...new Set(p.tracks.filter(t=>set.has(t.target)).map(t=>`${t.property}${t.layer?'@'+t.layer:''}`))],expression:(p.expression?.features??[]).filter(f=>f.node===n.id||f.paths.some(x=>set.has(x))).map(f=>({id:f.id,role:f.role,frozen:!!f.frozen,params:Object.keys(f.keys)})),modifiers:(p.modifiers??[]).filter(x=>x.targets.some(t=>set.has(t))).map(x=>({id:x.id,kind:x.kind,preset:x.preset,technique:x.technique??'geometry',enabled:x.enabled,speedFactor:x.params.speedFactor??1})),secondary:(p.secondary??[]).filter(s=>set.has(s.target)).map(s=>s.id),
   // Animation sources usable as plan sourceId (animation.adjust).
   sources:[...(p.modifiers??[]).filter(x=>x.targets.some(t=>set.has(t))).map(x=>({sourceId:x.id,kind:'modifier',technique:x.technique??'geometry',speedFactor:x.params.speedFactor??1})),...(p.secondary??[]).filter(s=>set.has(s.target)).map(s=>({sourceId:s.id,kind:'secondary'})),...p.tracks.filter(t=>set.has(t.target)&&t.keys.length>1&&t.property!=='param').map(t=>({sourceId:`track:${t.target}:${t.property}${t.layer?':'+t.layer:''}`,kind:'track',from:t.keys[0].time,to:t.keys.at(-1)!.time}))],
   children:depth>1?nodes(m).filter(c=>c.parent===n.id).map(c=>this.part(c,depth-1)):[]};}
 // ── Queries ──────────────────────────────────────────────────────────────────────────────
 async t_capabilities(a:Result){const tools=a.tool?TOOLS.filter(t=>t.name===a.tool||t.mcp===a.tool):TOOLS;if(!tools.length)throw new AgentError('UNKNOWN_TOOL',`Unknown tool ${a.tool}`);
  return {schemaVersion:2,tools,conventions:CONVENTIONS,vocabulary:{expressionTemplates:Object.fromEntries(Object.entries(TEMPLATES).map(([k,t])=>[k,{landmarks:t.landmarks,params:Object.keys(t.keys)}])),preservation:PRESERVATION,protectionLevels:LEVEL_MEANING,fluidPresets:Object.fromEntries(Object.entries(FLUID_PRESETS).map(([k,v])=>[k,v.describe])),springPresets:Object.fromEntries(Object.entries(SECONDARY_PRESETS).map(([k,v])=>[k,v.describe])),deliveryProfiles:Object.fromEntries(Object.values(PROFILES).map(p=>[p.id,{when:p.when,maxPaths:p.maxPaths,maxBytes:p.maxBytes,technologies:p.technologies}])),easings:['linear','ease-in-out','ease-in','ease-out','overshoot','anticipate','step','cubic-bezier(x1,y1,x2,y2)'],slots:['mouth','eyes','brows','ears','face']}};}
 async t_scene_inspect(a:Result){const m=this.m(),p=m.project,boxes=pathBoxes(m),all=nodes(m);const labeled=new Set(all.flatMap(n=>nodeIds(m,n,true)));const params=frameParams(p,0);
  const top=[...m.doc.documentElement.childNodes].filter(n=>n.nodeType===1).map(n=>n as Element).filter(e=>!['defs','metadata','title','style'].includes(e.localName)).map(e=>({id:e.getAttribute('id'),name:e.getAttribute('data-mai-name')??undefined,tag:e.localName,paths:[e,...elements(e)].filter(x=>x.localName==='path').length}));
  const choice=this.ws.choices.inspect();const sig=signals(m,{choice:choice?.status??null,openComments:this.ws.comments.list.filter(c=>c.status==='open').length,inboxSeq:this.ws.inbox.seq});
  const snap=await this.ws.snapshots.save(m,this.ws.documentId(),this.ws.revision());
  return {sessionId:this.ws.sessionId(),documentId:this.ws.documentId(),snapshotId:snap.id,asset:this.ws.asset(),canvas:m.doc.documentElement.getAttribute('viewBox'),duration:p.duration,fps:p.fps,loop:p.loop,preservation:p.preservation??'balanced',parts:all.filter(n=>!n.parent||!all.some(x=>x.id===n.parent)).map(n=>this.part(n,Number(a.depth??8))),
   unlabeled:{paths:[...boxes.keys()].filter(id=>!labeled.has(id)).length,topLevel:top.slice(0,30)},parameters:Object.fromEntries(Object.entries(p.params??{}).map(([k,d])=>[k,{value:round(params[k]??d.default),min:d.min,max:d.max,animated:p.tracks.some(t=>t.property==='param'&&t.target===k)}])),
   layers:(p.layers??[]).map(l=>({id:l.id,blend:l.blend,weight:l.weight,mute:!!l.mute,solo:!!l.solo})),expressionFeatures:(p.expression?.features??[]).map(f=>({id:f.id,role:f.role,part:f.node,frozen:!!f.frozen,params:Object.keys(f.keys),sizePx:f.size})),modifiers:(p.modifiers??[]).map(x=>({id:x.id,kind:x.kind,preset:x.preset,technique:x.technique??'geometry',enabled:x.enabled,targets:x.targets.length,params:x.params})),secondary:(p.secondary??[]).map(s=>({id:s.id,kind:s.kind,target:s.target,driver:s.driver,property:s.property,gain:s.gain,stiffness:s.stiffness,damping:s.damping,delay:s.delay})),
   choice:choice?{id:choice.id,status:choice.status,options:choice.options.map(o=>({id:o.id,position:o.position,label:o.label}))}:null,comments:{open:this.ws.comments.list.filter(c=>c.status==='open').length,latest:this.ws.comments.list.slice(-3).map(c=>({id:c.id,text:c.text,parts:c.parts.map(x=>x.id),status:c.status}))},selection:this.ws.selection(),next:sig.next};}
 async t_scene_semantics(){const m=this.m();return {parts:nodes(m).map(n=>({...n,address:addressOf(m,n),targets:n.targets.slice(0,50),targetCount:n.targets.length})),relations:m.project.semantic?.relations??[]};}
 async t_scene_selection(){const m=this.m(),ids=this.ws.selection().filter(id=>m.index.has(id));const parts=nodes(m).filter(n=>{const set=new Set(nodeIds(m,n,true));return ids.some(id=>set.has(id));}).map(n=>({id:n.id,address:addressOf(m,n),role:n.role,label:n.label}));const boxes=pathBoxes(m);const bs=ids.flatMap(id=>[id,...elements(m.index.get(id)!).map(e=>e.getAttribute('id')??'')]).map(id=>boxes.get(id)).filter(Boolean) as {x0:number;y0:number;x1:number;y1:number}[];
  return {ids,parts,bounds:bs.length?{x:Math.min(...bs.map(b=>b.x0)),y:Math.min(...bs.map(b=>b.y0)),width:Math.max(...bs.map(b=>b.x1))-Math.min(...bs.map(b=>b.x0)),height:Math.max(...bs.map(b=>b.y1))-Math.min(...bs.map(b=>b.y0))}:null};}
 async t_scene_timeline(a:Result){const m=this.m(),p=m.project;const filter=a.target?this.deep(a.target).ids:null;const inScope=(id:string)=>!filter||filter.has(id.split('::')[0]);const params=frameParams(p,0);
  return {duration:p.duration,fps:p.fps,loop:p.loop,layers:p.layers??[],tracks:p.tracks.filter(t=>t.property==='param'||inScope(t.target)).map(t=>({target:t.target,property:t.property,layer:t.layer??'base',keys:t.keys.length,from:t.keys[0].time,to:t.keys.at(-1)!.time,values:t.property==='d'?'(path data)':t.keys.slice(0,12).map(k=>[k.time,k.value,k.easing])})),markers:p.markers??[],regions:p.regions??[],clips:p.clips??[],params:Object.fromEntries(Object.entries(p.params??{}).map(([k,d])=>[k,{...d,valueAt0:round(params[k]??d.default)}])),modifiers:(p.modifiers??[]).filter(x=>x.targets.some(inScope)).map(x=>({id:x.id,kind:x.kind,preset:x.preset,technique:x.technique??'geometry',enabled:x.enabled,params:x.params,direction:x.direction,anchor:x.anchor})),secondary:(p.secondary??[]).filter(s=>inScope(s.target))};}
 async t_scene_identity(){const m=this.m(),p=m.project,mode=p.preservation??'balanced';const crit=critique(m,{samples:24});
  return {preservation:{mode,...PRESERVATION[mode]},modes:PRESERVATION,levels:Object.fromEntries(Object.entries(LEVEL_MEANING).map(([k,v])=>[k,{meaning:v,allows:ALLOWED[k as ProtectionLevel]}])),protected:protectedNodes(m).map(n=>{const node=nodes(m).find(x=>x.id===n.id);return {id:n.id,address:node?addressOf(m,node):undefined,levels:n.levels,targets:n.targets.length};}),
   features:(p.expression?.features??[]).map(f=>({id:f.id,role:f.role,part:f.node,frozen:!!f.frozen,sizePx:f.size,budgetPx:round(PRESERVATION[mode].maxDisplacement*f.size,2),currentMaxDisplacementPx:round(Math.max(0,...Object.values(featureDisplacements(f,frameParams(p,0),mode)).map(d=>Math.hypot(d.dx,d.dy))),2)})),findings:crit.deterministic.findings.filter(x=>/IDENTITY|SILHOUETTE|SQUASH/.test(x.code))};}
 async t_scene_history(a:Result){const h=this.ws.history();return {...h,entries:h.entries.slice(-Number(a.limit??20)).map(e=>({...e,token:`rev:${e.revision}`}))};}
 async t_choices_inspect(){const c=this.ws.choices.inspect();if(!c)return {choice:null};const m=this.m();
  // Which semantic parts each combinable slot controls (via expression features), so plans name real parts.
  const slotParts=Object.fromEntries(c.combinableSlots.map(slot=>[slot,(m.project.expression?.features??[]).filter(f=>slotOfRole(f.role)===slot).map(f=>f.node??f.id)]));return {choice:{...c,slotParts,sessionId:this.ws.sessionId(),documentId:this.ws.documentId()}};}
 async t_export_capabilities(a:Result){return exportCapabilities(this.m(),a.target as string|undefined);}
 async t_part_resolve(a:Result){const r=resolve(this.m(),String(a.ref));return {ids:r.ids.slice(0,200),idCount:r.ids.length,via:r.via,parts:r.nodes.map(n=>this.part(n,1))};}
 async t_comments_list(a:Result){return {comments:this.ws.comments.public().filter(c=>!a.status||c.status===a.status)};}
 async t_inbox_wait(a:Result){const after=Number(a.after??0),events=await this.ws.inbox.wait(after,Number(a.wait??0)*1000,a.types as string[]|undefined);return {cursor:events.at(-1)?.seq??after,latest:this.ws.inbox.seq,events};}
 async t_audit(a:Result){return detect(this.m(),a.profile as string|undefined) as unknown as Result;}
 async t_critique(a:Result){return critique(this.m(),{samples:a.samples as number|undefined}) as unknown as Result;}
 async t_performance(){return profile(this.m()) as unknown as Result;}
 // ── Proposals ────────────────────────────────────────────────────────────────────────────
 async t_expression_propose(a:Result){return this.ws.queued(async()=>{this.expected(a);const r=await this.ws.choices.proposeExpression({emotion:String(a.emotion),intensity:Number(a.intensity),count:a.count as number|undefined,time:a.time as number|undefined,slots:a.slots as string[]|undefined,keep:a.preserve as string[]|undefined,previewRegion:a.previewRegion as never,previewScale:a.previewScale as 1|2|undefined,prompt:a.prompt as string|undefined,recommended:a.recommended as string|undefined,reason:a.reason as string|undefined},this.m(),this.ws.revision());this.ws.broadcast({patches:[]});await this.ws.inbox.push('choice.proposed',{id:r!.id,options:r!.options.map(o=>o.id)},'Espera la elección o un comentario del usuario.');return {choice:this.ws.choices.inspect(),_next:'Muestra las previews (previewPath) al usuario y espera su decisión; no elijas por él.'};});}
 async t_choice_propose(a:Result){return this.ws.queued(async()=>{this.expected(a);await this.ws.choices.propose(a.request as never,this.m(),this.ws.revision());this.ws.broadcast({patches:[]});await this.ws.inbox.push('choice.proposed',{id:this.ws.choices.current!.id},'Espera la elección del usuario.');return {choice:this.ws.choices.inspect(),_next:'Muestra las previews al usuario y espera su decisión.'};});}
 async t_variant_combine(a:Result){const c=this.ws.choices.current;if(!c)throw new AgentError('NO_CHOICE','There is no choice board');
  const combined=await this.ws.queued(async()=>{this.expected(a);const r=await this.ws.choices.combine(c.id,{base:String(a.base),take:a.take as Record<string,string>|undefined,preserve:a.preserve as string[]|undefined,scale:a.scale as Record<string,number>|undefined,label:a.label as string|undefined},this.m(),this.ws.revision());this.ws.broadcast({patches:[]});return r;});
  if(!a.apply)return {...combined,choice:{id:c.id,version:this.ws.choices.current?.version,options:this.ws.choices.inspect()!.options.map(o=>({id:o.id,label:o.label}))},_next:`Muestra ${combined.option.previewPath} al usuario; aplícala con choice.choose option=${combined.option.id} cuando la acepte.`};
  // Deprecated shortcut: accept the derived option in its own atomic transaction (prefer plan.execute with variant.apply).
  const chosen=await this.t_choice_choose({option:combined.option.id,expectedRevision:a.expectedRevision,text:a.label,preview:a.preview});return {...combined,applied:chosen,warnings:['variant.combine apply:true is deprecated: use plan.execute with variant.apply (one transaction with constraints and identity gate).']};}
 async t_choice_regenerate(a:Result){const c=this.ws.choices.current;if(!c)throw new AgentError('NO_CHOICE','There is no choice board');return this.ws.queued(async()=>{this.expected(a);const r=await this.ws.choices.regenerate(c.id,{count:a.count as number|undefined,keep:a.keep as string[]|undefined,intensity:a.intensity as number|undefined},this.m(),this.ws.revision());this.ws.broadcast({patches:[]});return {choice:r};});}
 async t_choice_note(a:Result){const c=this.ws.choices.current;if(!c)throw new AgentError('NO_CHOICE','There is no choice board');const note=await this.ws.choices.note(c.id,String(a.text),a.author==='agent'?'agent':'user');this.ws.broadcast({patches:[]});return {note};}
 async t_part_candidates(a:Result){const m=this.m();const scope=a.scope?this.scopeOf(a.scope):undefined;const list=candidates(m,{point:a.point as never,box:a.box as never,region:a.region as never,negative:a.negative as never,scope:scope?.id});
  if(!a.propose)return {candidates:list,_next:list.length>1?'Varias regiones posibles: propón con propose para que el usuario elija, o decide con contexto y explica por qué.':'Etiqueta el candidato con part.label o part.extract.'};
  if(list.length<2)return {candidates:list,choice:null,_next:'Solo un candidato: confírmalo con part.label.'};
  const pr=a.propose as {id:string;role:string;label:string};return this.ws.queued(async()=>{this.expected(a);const sorted=[...list].sort((x,y)=>y.confidence-x.confidence);
   await this.ws.choices.propose({id:`seg-${pr.id}`.replace(/[^\w-]/g,'-').slice(0,60),prompt:`¿Cuál de estas regiones es «${pr.label}»?`,recommended:sorted[0].id,reason:sorted[0].reason,kind:'segmentation',previewRegion:a.previewRegion as never,options:list.map(c=>({id:c.id,label:`${c.label} · ${c.paths} formas`,description:c.reason,highlight:c.targets.slice(0,3000),ops:[{type:'semantic.label',node:{id:pr.id,role:pr.role,label:pr.label,targets:c.targets.slice(0,5000),status:'confirmed',source:'user',confidence:c.confidence}},{type:'decision.log',decision:{kind:'segmentation',summary:`${pr.label} = candidato ${c.id} (${c.method}, ${c.paths} formas)`,source:'user'}}] as Operation[]}))},m,this.ws.revision());
   this.ws.broadcast({patches:[]});return {candidates:list,choice:this.ws.choices.inspect(),_next:'Muestra las previews y espera la confirmación del usuario.'};});}
 // ── Mutations ────────────────────────────────────────────────────────────────────────────
 async t_choice_choose(a:Result){const c=this.ws.choices.current;if(!c)throw new AgentError('NO_CHOICE','There is no choice board');const id=String(a.id??c.id);const option=this.ws.choices.selected(id,String(a.option),this.ws.revision(),this.m());
  // The acceptance travels in the same transaction as the option's operations: undo reverts both.
  const ops:Operation[]=[...option.ops,{type:'choice.accept',acceptance:{boardId:c.id,version:c.version,option:option.id,label:option.label,source:'user-direction',...(a.text?{text:String(a.text).slice(0,4000)}:{})}},{type:'decision.log',decision:{kind:c.kind??'choice',summary:`${c.prompt} → ${option.id} (${option.label})${a.text?` · «${String(a.text).slice(0,200)}»`:''}`,source:'user'}}];
  const r=await this.commit('choice.choose',a,ops,{target:id,changes:{option:option.id,label:option.label,params:option.spec?.params}});if(r.committed){this.ws.broadcast({patches:[]});await this.ws.inbox.push('choice.chosen',{id,option:option.id},'Opción aplicada; verifica y continúa.');}return r;}
 async t_choice_dismiss(a:Result){const c=this.ws.choices.current;if(!c||c.status!=='pending')throw new AgentError('NO_CHOICE','No pending board');this.expected(a);c.status='dismissed';await this.ws.choices.save();this.ws.broadcast({patches:[]});return {choice:this.ws.choices.inspect()};}
 async t_part_label(a:Result){const node={id:String(a.id),role:String(a.role),label:String(a.label),targets:(a.targets as string[]|undefined)??nodes(this.m()).find(n=>n.id===a.id)?.targets??[],...(a.parent?{parent:String(a.parent)}:{}),...(a.landmarks?{landmarks:a.landmarks}:{}),...(a.region?{region:a.region}:{}),...(a.protection?{protection:a.protection}:{}),status:(a.status as 'confirmed'|'proposed')??'confirmed',source:'agent'} as SemanticNode;
  const r=await this.commit('part.label',a,[{type:'semantic.label',node}],{target:node.id,changes:{part:node.id,role:node.role,targets:node.targets.length}});return {...r,part:{id:node.id,address:node.parent?`${addressOf(this.m(),nodes(this.m()).find(n=>n.id===node.parent)!)}.${node.id}`:node.id}};}
 async t_part_extract(a:Result){const source=this.one(a.source).id,id=String(a.id);const ops:Operation[]=[{type:'region.extract',id,name:String(a.name),source,region:a.region as never,alpha:a.alpha as boolean|undefined,margin:a.margin as number|undefined},{type:'semantic.label',node:{id,role:String(a.role??'other'),label:String(a.name),targets:[id],...(a.parent?{parent:String(a.parent)}:{}),region:a.region as never,status:'confirmed',source:'agent'}}];
  const r=await this.commit('part.extract',a,ops,{target:id,changes:{layer:id,source}});const m=this.m();return {...r,paths:m.index.has(id)?elements(m.index.get(id)!).filter(e=>e.localName==='path').length:undefined};}
 async t_identity_preserve(a:Result){return this.protect(a,true);}
 async t_identity_release(a:Result){return this.protect(a,false);}
 private async protect(a:Result,on:boolean){const m=this.m(),ops:Operation[]=[],changes:{part:string;levels:string[];frozen:string[]}[]=[];const levels=(a.levels as ProtectionLevel[]|undefined)??['protected'];
  const freeze=on?(a.freezeExpression as boolean|undefined)??!levels.some(l=>['deformable','free','topology-preserved','color-preserved','style-preserved','silhouette-preserved'].includes(l)):false;
  for(const ref of a.targets as string[]){const r=requireConfirmed(resolve(m,ref));if(!r.nodes.length){ops.push({type:on?'identity.protect':'identity.release',ids:r.ids});changes.push({part:ref,levels:on?['protected']:[],frozen:[]});continue;}
   for(const n of r.nodes){ops.push({type:'semantic.protect',id:n.id,protection:on?levels:[]});const set=new Set(nodeIds(m,n,true));const feats=(m.project.expression?.features??[]).filter(f=>f.node===n.id||f.paths.some(p=>set.has(p)));const frozen:string[]=[];
    for(const f of feats)if(on?freeze&&!f.frozen:f.frozen){ops.push({type:'expression.freeze',feature:f.id,frozen:on});frozen.push(f.id);}changes.push({part:addressOf(m,n),levels:on?levels:[],frozen});}}
  return this.commit(on?'identity.preserve':'identity.release',a,ops,{target:a.targets,changes});}
 async t_preservation_set(a:Result){const before=this.m().project.preservation??'balanced';return this.commit('preservation.set',a,[{type:'preservation',mode:a.mode as never}],{changes:{preservation:{from:before,to:a.mode}}});}
 async t_expression_rig(a:Result){const m=this.m(),r=requireConfirmed(resolve(m,String(a.part)));const node=r.nodes[0];const id=String(a.id??node?.id??'feature');const op:Operation={type:'expression.feature',feature:{id,role:String(a.role),...(node?{node:node.id}:{}),paths:r.ids,landmarks:a.landmarks as never,...(a.region??node?.region?{region:(a.region??node!.region) as never}:{}),...(a.rigid?{rigid:a.rigid as never}:{})}};
  const res=await this.commit('expression.rig',a,[op,...(node?Object.entries(a.landmarks as Record<string,{x:number;y:number}>).map(([k,p])=>({type:'landmark.set' as const,node:node.id,name:k,x:p.x,y:p.y})):[])],{target:a.part});const f=this.m().project.expression?.features.find(x=>x.id===id);return {...res,feature:f?{id:f.id,params:Object.keys(f.keys),landmarks:Object.keys(f.landmarks),paths:f.paths.length,sizePx:f.size}:undefined};}
 async t_expression_apply(a:Result){const p=this.m().project,params=a.params as Record<string,number>;const now=frameParams(p,Number(a.time??0));const changes=Object.fromEntries(Object.entries(params).map(([k,v])=>[k,{from:round(now[k]??0),to:v}]));
  const op:Operation=a.time===undefined?{type:'param.set',params}:{type:'expression.set',params,time:Number(a.time),layer:String(a.layer??'expression'),...(a.easing?{easing:a.easing as never}:{})};return this.commit('expression.apply',a,[op],{changes});}
 async t_animation_adjust(a:Result){const m=this.m(),p=m.project,{ids,resolved}=this.deep(a.target,true);const prop=String(a.property);const ops:Operation[]=[],changes:Record<string,Record<string,{from:unknown;to:unknown}>>={};
  const next=(from:number)=>{if(a.set!==undefined)return Number(a.set);if(a.add!==undefined)return round(from+Number(a.add),4);if(a.scale!==undefined)return round(from*Number(a.scale),4);throw new AgentError('INVALID_ARGUMENT','Provide scale, set or add');};
  const mods=(p.modifiers??[]).filter(x=>x.targets.some(t=>ids.has(t)));const secs=(p.secondary??[]).filter(s=>ids.has(s.target));
  const key:Record<string,string>={speed:'speedFactor',amplitude:'amplitude',turbulence:'swirl'};
  if(['speed','amplitude','turbulence'].includes(prop))for(const x of mods){const k=key[prop],from=x.params[k]??(k==='speedFactor'?1:0),to=next(from);ops.push({type:'modifier.update',id:x.id,params:{[k]:to}});changes[x.id]={[prop]:{from,to}};}
  if(prop==='direction')for(const x of mods){if(!a.direction)throw new AgentError('INVALID_ARGUMENT','direction needs {x,y}');ops.push({type:'modifier.update',id:x.id,direction:a.direction as never});changes[x.id]={direction:{from:x.direction,to:a.direction}};}
  const sk:Record<string,'gain'|'stiffness'|'damping'|'delay'>={gain:'gain',amplitude:'gain',stiffness:'stiffness',damping:'damping',delay:'delay'};
  if(sk[prop])for(const s of secs){const k=sk[prop],from=s[k],to=next(from);ops.push({type:'secondary.update',id:s.id,secondary:{[k]:to}});changes[s.id]={[k]:{from,to}};}
  if(prop==='speed'||prop==='timing'){const tracks=p.tracks.filter(t=>ids.has(t.target.split('::')[0])&&t.keys.length>1);for(const t of tracks){const factor=a.scale!==undefined?1/Number(a.scale):undefined;if(!factor)throw new AgentError('INVALID_ARGUMENT','Track retiming uses scale (0.7 = 30% slower)');const start=t.keys[0].time,end=t.keys.at(-1)!.time,newEnd=start+(end-start)*factor;if(newEnd>p.duration+1e-9)throw new AgentError('TIMELINE_OVERFLOW',`Retiming ${t.target}.${t.property} ×${a.scale} would end at ${round(newEnd)}s, beyond the ${p.duration}s timeline; nothing was applied`,{alternatives:['extend the timeline (timeline.set duration) first','choose a smaller change','adjust only another source (plan.execute with sourceId)']});ops.push({type:'track.edit',target:t.target,property:t.property,action:'stretch',amount:round(factor,5),...(t.layer?{layer:t.layer}:{})});changes[`${t.target}.${t.property}`]={duration:{from:round(end-start),to:round(newEnd-start)}};}}
  if(prop==='intensity'){const slots=new Set(resolved.nodes.map(n=>slotOfRole(n.role)));const tracks=p.tracks.filter(t=>t.property==='param'&&[...slots].some(s=>t.target.endsWith('@'+s)));for(const t of tracks){if(a.scale===undefined)throw new AgentError('INVALID_ARGUMENT','intensity uses scale');ops.push({type:'track.edit',target:t.target,property:'param',action:'scale',amount:Number(a.scale),...(t.layer?{layer:t.layer}:{})});changes[t.target]={intensity:{from:'×1',to:`×${a.scale}`}};}
   const statics=Object.entries(p.params??{}).filter(([k,d])=>d.default&&[...slots].some(s=>k.endsWith('@'+s))&&!tracks.some(t=>t.target===k));if(statics.length){const params=Object.fromEntries(statics.map(([k,d])=>[k,next(d.default)]));ops.push({type:'param.set',params});for(const [k,d]of statics)changes[k]={value:{from:d.default,to:params[k]}};}}
  if(!ops.length)throw new AgentError('NO_ANIMATION_SOURCE',`${String(a.target)} has nothing animated that responds to "${prop}"`,{found:{modifiers:mods.map(x=>x.id),secondary:secs.map(s=>s.id)},hint:'Add motion first: fluid.animate (existing smoke/water…), motion.spring (follow-through), motion.preset or expression.apply.'});
  return this.commit('animation.adjust',a,ops,{target:resolved.addresses[0]??a.target,changes});}
 async t_fluid_animate(a:Result){const ops:Operation[]=[];let targetId:string;let address=String(a.target??'');
  if(a.region){if(!a.source)throw new AgentError('INVALID_ARGUMENT','region needs source (the trace to copy from)');targetId=String(a.id??`${a.preset}-part`);ops.push({type:'region.extract',id:targetId,name:`${a.preset} original`,source:this.one(a.source).id,region:a.region as never},{type:'semantic.label',node:{id:targetId,role:String(a.preset),label:`${a.preset} (existente)`,targets:[targetId],region:a.region as never,status:'confirmed',source:'agent'}});address=targetId;}
  else{if(!a.target)throw new AgentError('INVALID_ARGUMENT','Provide target (part) or region+source');targetId=this.one(a.target,'group',true).id;}
  const id=String(a.id??`${targetId}-flow`);ops.push({type:'fluid.animate',id,targets:[targetId],preset:a.preset as never,...(a.technique?{technique:a.technique as never}:{}),...(a.quality?{quality:a.quality as never}:{}),...(a.anchor?{anchor:a.anchor as never}:{}),...(a.direction?{direction:a.direction as never}:{}),...(a.params?{params:a.params as never}:{})});
  const r=await this.commit('fluid.animate',a,ops,{target:address,changes:{modifier:id,preset:a.preset,technique:a.technique??'geometry'}});const mod=this.m().project.modifiers?.find(x=>x.id===id);return {...r,modifier:mod?{id:mod.id,targets:mod.targets.length,anchor:mod.anchor,direction:mod.direction,params:mod.params}:undefined};}
 async t_motion_spring(a:Result){const target=this.one(a.target,'group',true).id,driver=this.one(a.driver,'group').id;const preset=SECONDARY_PRESETS[(a.preset as keyof typeof SECONDARY_PRESETS)??'tail'];const o=(a.overrides??{}) as Record<string,number>;const ops:Operation[]=[];
  if(a.pivot)ops.push({type:'pose',id:target,pose:{pivotX:(a.pivot as {x:number}).x,pivotY:(a.pivot as {y:number}).y}});const s={id:String(a.id??`${target}-spring`),kind:'spring' as const,target,driver,property:(a.property as 'rotation')??'rotation',driverProperty:(a.driverProperty as 'y')??'y',stiffness:o.stiffness??preset.stiffness,damping:o.damping??preset.damping,gain:o.gain??preset.gain,delay:o.delay??preset.delay,limit:o.limit??preset.limit};ops.push({type:'secondary.add',secondary:s});
  return {...await this.commit('motion.spring',a,ops,{target:a.target,changes:{secondary:s}}),secondary:s};}
 async t_motion_preset(a:Result){const id=this.one(a.target,'group',true).id;return this.commit('motion.preset',a,[{type:'motion.preset',id,kind:a.kind as never,...(a.amplitude!==undefined?{amplitude:Number(a.amplitude)}:{}),...(a.layer?{layer:String(a.layer)}:{})}],{target:a.target,changes:{preset:a.kind,layer:a.layer??'base'}});}
 async t_morph_apply(a:Result){const id=this.one(a.target,'path',true).id,m=this.m();const to=String(a.to);const toD=to.startsWith('#')?m.index.get(to.slice(1))?.getAttribute('d')??'':to;const analysis=analyzeMorph(m.index.get(id)!.getAttribute('d')!,toD);
  return {...await this.commit('morph.apply',a,[{type:'morph.apply',id,to,time:Number(a.time),...(a.from!==undefined?{from:Number(a.from)}:{}),...(a.easing?{easing:a.easing as never}:{})}],{target:a.target,changes:{segments:analysis.segments,destructive:analysis.destructive},warnings:analysis.destructive?[analysis.advice]:[]}),analysis};}
 async t_timeline_set(a:Result){const p=this.m().project,ops:Operation[]=[],changes:Record<string,{from:unknown;to:unknown}>={};
  if(a.duration!==undefined||a.fps!==undefined||a.loop!==undefined){ops.push({type:'timeline',...(a.duration!==undefined?{duration:Number(a.duration)}:{}),...(a.fps!==undefined?{fps:Number(a.fps)}:{}),...(a.loop!==undefined?{loop:!!a.loop}:{})});for(const k of ['duration','fps','loop'] as const)if(a[k]!==undefined)changes[k]={from:p[k],to:a[k]};}
  if(a.retime!==undefined){ops.push({type:'timeline.retime',factor:Number(a.retime),...(a.start!==undefined?{start:Number(a.start)}:{}),...(a.end!==undefined?{end:Number(a.end)}:{})});changes.retime={from:1,to:a.retime};}
  if(a.layer){const l=a.layer as Record<string,unknown>,cur=(p.layers??[]).find(x=>x.id===l.id);ops.push({type:'layer.set',layer:{id:String(l.id),name:String(cur?.name??l.id),blend:(l.blend as 'additive')??cur?.blend??'additive',weight:Number(l.weight??cur?.weight??1),mute:l.mute as boolean|undefined??cur?.mute,solo:l.solo as boolean|undefined??cur?.solo,locked:l.locked as boolean|undefined??cur?.locked}});changes[`layer:${l.id}`]={from:cur??null,to:l};}
  if(a.marker){ops.push({type:'marker.set',marker:a.marker as never});changes.marker={from:null,to:a.marker};}
  return this.commit('timeline.set',a,ops,{changes});}
 async t_ops_apply(a:Result){return this.commit('ops.apply',a,a.ops as Operation[],{changes:{operations:(a.ops as Operation[]).map(o=>o.type)}});}
 async t_history_undo(a:Result){await this.ws.undo(this.expected(a),a.token as string|undefined);return {undone:a.token??'latest'};}
 async t_history_redo(a:Result){await this.ws.redo(this.expected(a));return {redone:true};}
 async t_comments_reply(a:Result){const c=await this.ws.comments.reply(String(a.id),{text:String(a.text),author:'agent',status:a.status as never,choice:a.choice as string|undefined,revision:this.ws.revision()});this.ws.broadcast({patches:[]});return {comment:{id:c.id,status:c.status,replies:c.replies.length}};}
 // ── Render and verification ──────────────────────────────────────────────────────────────
 private regionOf(m:VectorDocument,a:Record<string,unknown>){if(a.region)return a.region as {x:number;y:number;width:number;height:number};if(!a.part)return undefined;const r0=resolve(m,String(a.part));
  // Parts with a region (extracted features, heads…) are framed by it: clipped source paths can span the whole canvas.
  const regions=r0.nodes.filter(n=>n.region).map(n=>regionBounds(n.region!));if(regions.length){const pad=6,x=Math.min(...regions.map(b=>b.x))-pad,y=Math.min(...regions.map(b=>b.y))-pad;return {x,y,width:Math.max(...regions.map(b=>b.x+b.width))+pad-x,height:Math.max(...regions.map(b=>b.y+b.height))+pad-y};}
  const {ids}=this.deep(a.part);const boxes=pathBoxes(m);const bs=[...ids].map(id=>boxes.get(id)).filter(Boolean) as {x0:number;y0:number;x1:number;y1:number}[];if(!bs.length)return undefined;const pad=12;const x=Math.min(...bs.map(b=>b.x0))-pad,y=Math.min(...bs.map(b=>b.y0))-pad;return {x,y,width:Math.max(...bs.map(b=>b.x1))+pad-x,height:Math.max(...bs.map(b=>b.y1))+pad-y};}
 private async png(m:VectorDocument,time:number,region?:{x:number;y:number;width:number;height:number},scale=1){const r=await renderSvg(m.frame(time),0,'chromium',scale);let img=sharp(r.png);if(region){const left=Math.max(0,Math.floor(region.x*scale)),top=Math.max(0,Math.floor(region.y*scale)),width=Math.max(1,Math.min(r.width-left,Math.ceil(region.width*scale))),height=Math.max(1,Math.min(r.height-top,Math.ceil(region.height*scale)));img=sharp(await img.extract({left,top,width,height}).png().toBuffer());}return img.png().toBuffer();}
 async renderFrames(m:VectorDocument,a:Record<string,unknown>,tag:string){const times=(a.times as number[]|undefined)??[0];const dir=join(this.ws.cache,'previews');await mkdir(dir,{recursive:true});const region=this.regionOf(m,a);const frames=[];
  for(const t of times.slice(0,8)){if(t<0||t>m.project.duration)throw new AgentError('INVALID_ARGUMENT',`time ${t} outside 0–${m.project.duration}`);const png=await this.png(m,t,region,Number(a.scale??1));const meta=await sharp(png).metadata();const path=join(dir,`${tag}-r${this.ws.revision()}-${t.toFixed(2)}-${randomUUID().slice(0,6)}.png`);await writeFile(path,png);frames.push({time:t,path,width:meta.width,height:meta.height});}
  return {frames,region};}
 async t_preview_render(a:Result){return {...await this.renderFrames(this.m(),a,'preview'),_next:'Abre los PNG (path) y evalúalos visualmente antes de describir el resultado.'};}
 private undeformed(m:VectorDocument){const d=new VectorDocument(m.toSVG());const p=d.project;p.tracks=p.tracks.filter(t=>t.property!=='param');for(const k of Object.keys(p.params??{}))p.params![k].default=0;for(const x of p.modifiers??[])x.enabled=false;return d;}
 async t_compare_frames(a:Result){const m=this.m();const before=a.against==='rest'?this.undeformed(m):this.ws.previous();if(!before)throw new AgentError('NO_PREVIOUS','No previous state in history to compare with');const times=(a.times as number[]|undefined)??[0];const frames=[];
  for(const t of times){const [x,y]=await Promise.all([this.png(before,t),this.png(m,t)]);const A=await raw(x),B=await raw(y);const parts:Record<string,unknown>={};for(const ref of (a.parts as string[]|undefined)??[]){const box=this.regionOf(m,{part:ref});parts[ref]=box?metrics(A,B,box):'no bounds';}frames.push({time:t,...metrics(A,B),parts});}
  return {against:a.against??'previous',frames,interpretation:'mae en 0–255 (premultiplicado); ssim 1 = idéntico; métricas de cambio, no de calidad artística.'};}
 // Identity verification needs an explicit reference and real coverage. Nothing evaluated is never a pass.
 //  snapshot: regression against an immutable session snapshot ("como está" = what the agent observed);
 //  baseline: regression against an approved original (file or snapshot) verified by hash;
 //  rig-rest: expression displacement only (same frame without expression/modifiers), not a regression test.
 async reference(ref:{kind:string;id?:string}){const m=this.m();
  if(ref.kind==='rig-rest')return {doc:this.undeformed(m),label:'rig-rest (misma escena sin expresión ni modificadores)'};
  if(ref.kind==='snapshot'){if(!ref.id)throw new AgentError('INVALID_ARGUMENT','reference.id is required for snapshot');const r=await this.ws.snapshots.load(ref.id).catch(e=>{throw new AgentError('BASELINE_NOT_FOUND',String(e.message),{},404);});if(r.meta.documentId!==this.ws.documentId())throw new AgentError('DOCUMENT_MISMATCH',`Snapshot ${ref.id} belongs to another document`,{},409);return {doc:r.doc,label:`snapshot ${ref.id} (rev ${r.meta.revision})`};}
  if(ref.kind==='baseline'){const b=(m.project.baselines??[]).find(x=>x.id===ref.id);if(!b)throw new AgentError('BASELINE_NOT_FOUND',`Baseline ${ref.id} is not registered`,{baselines:(m.project.baselines??[]).map(x=>x.id)},404);
   let svg:string;if(b.source.kind==='file'){svg=await readFile(join(this.ws.root,b.source.path),'utf8').catch(()=>{throw new AgentError('BASELINE_NOT_FOUND',`Baseline file ${b.source.kind==='file'?b.source.path:''} is missing`,{},404);});}else svg=(await this.ws.snapshots.meta(b.source.snapshotId).catch(()=>{throw new AgentError('BASELINE_NOT_FOUND',`Baseline snapshot missing`,{},404);})).svg;
   if(sha256(svg)!==b.sha256)throw new AgentError('BASELINE_NOT_FOUND',`Baseline ${b.id} hash mismatch: the file changed since it was registered`,{},409);return {doc:new VectorDocument(svg),label:`baseline ${b.id} (${b.approval})`};}
  throw new AgentError('INVALID_ARGUMENT',`Unknown reference kind ${ref.kind}`);}
 async t_identity_check(a:Result){const m=this.m(),p=m.project,times=a.times as number[],refs=a.parts as string[],mode=p.preservation??'balanced';
  const threshold=Number(a.threshold??{strict:.75,balanced:1.5,free:3}[mode]);for(const t of times)if(t<0||t>p.duration)throw new AgentError('INVALID_ARGUMENT',`time ${t} outside 0–${p.duration}`,{path:'times'});
  const reference=await this.reference(a.reference as {kind:string;id?:string});const evaluated:Result[]=[],skipped:{part:string;reason:string}[]=[];
  const parts=refs.flatMap(ref=>{try{const r=resolve(m,ref);if(!r.nodes.length)return [{ref,node:undefined as SemanticNode|undefined}];return r.nodes.map(node=>({ref,node}));}catch(e){skipped.push({part:ref,reason:String((e as Error).message)});return [];}});
  const plan=parts.map(({ref,node})=>{const box=this.regionOf(m,{part:node?node.id:ref});if(!box){skipped.push({part:ref,reason:'no measurable region'});return undefined;}const set=node?new Set(nodeIds(m,node,true)):new Set<string>();const feature=(p.expression?.features??[]).find(f=>(node&&f.node===node.id)||f.paths.some(id=>set.has(id)));
   const levels=node?.protection??[];const kind=levels.some(l=>l==='locked'||l==='protected')||feature?.frozen?'unchanged':levels.includes('silhouette-preserved')?'silhouette':feature&&levels.includes('deformable')?'bounded':levels.length?'unchanged':'reported';return {part:node?addressOf(m,node):ref,box,feature,kind};}).filter(Boolean) as {part:string;box:{x:number;y:number;width:number;height:number};feature?:import('../core/model.js').ExpressionFeature;kind:string}[];
  if(plan.length){try{for(const t of times){const [x,y]=await Promise.all([this.png(reference.doc,t),this.png(m,t)]);const A=await raw(x),B=await raw(y);
    for(const q of plan){const r=metrics(A,B,q.box);const fp=frameParams(p,t);const drift=q.feature?Math.max(0,...Object.values(featureDisplacements(q.feature,fp,mode)).map(d=>Math.hypot(d.dx,d.dy))):0;const budget=q.feature?PRESERVATION[mode].maxDisplacement*q.feature.size:0;
     const status=q.kind==='unchanged'?(r.mae<=threshold?'pass':'fail'):q.kind==='silhouette'?(r.silhouetteIoU>=.9?'pass':'fail'):q.kind==='bounded'?(drift<=budget*1.001?'pass':'fail'):'reported';
     evaluated.push({part:q.part,time:t,expectation:q.kind,status,mae:r.mae,ssim:r.ssim,silhouetteIoU:r.silhouetteIoU,...(q.feature?{landmarkDriftPx:round(drift,2),budgetPx:round(budget,2)}:{}),threshold:q.kind==='unchanged'?threshold:q.kind==='silhouette'?.9:undefined});}}}
   catch(error){if(error instanceof AgentError)throw error;return {status:'not_evaluated',pass:false,reason:'RENDERER_UNAVAILABLE',message:String(error),reference:reference.label,evaluated:[],skipped};}}
  const gated=evaluated.filter(e=>e.status!=='reported');const status=!gated.length?'not_evaluated':gated.some(e=>e.status==='fail')?'fail':'pass';
  const crit=critique(m,{samples:Math.max(8,times.length*4)});const drift=crit.deterministic.findings.filter(f=>f.code==='MAI_IDENTITY_DRIFT');
  return {status:drift.length&&status==='pass'?'fail':status,pass:status==='pass'&&!drift.length,reference:reference.label,mode,requestedParts:refs,requestedTimes:times,evaluatedParts:[...new Set(gated.map(e=>e.part))],skipped,structural:{identityDrift:drift},evaluated,
   note:status==='not_evaluated'?'Ninguna parte con expectativa verificable se evaluó: no es aprobación.':'Métricas de región por tiempo; no constituyen aprobación artística.'};}
 async t_baseline_capture(a:Result){const id=String(a.id);let source:import('../core/model.js').Baseline['source'],hash:string;
  if(a.file){const path=String(a.file);if(path.startsWith('/')||path.includes('..'))throw new AgentError('INVALID_ARGUMENT','file must be a project-relative path',{path:'file'});const svg=await readFile(join(this.ws.root,path),'utf8').catch(()=>{throw new AgentError('NOT_FOUND',`File ${path} not found`,{},404);});source={kind:'file',path};hash=sha256(svg);}
  else{const snap=await this.ws.snapshots.save(this.m(),this.ws.documentId(),this.ws.revision());const meta=await this.ws.snapshots.meta(snap.id);source={kind:'snapshot',snapshotId:snap.id};hash=meta.sha256;}
  return this.commit('baseline.capture',a,[{type:'baseline.add',baseline:{id,label:String(a.label??id),source,sha256:hash,revision:this.ws.revision(),approval:'unreviewed',createdAt:new Date().toISOString()}}],{target:id,changes:{baseline:id,source,sha256:hash,approval:'unreviewed'}});}
 // ── Agent IR: one atomic transaction per intent ─────────────────────────────────────────────
 private planner(){const p=this.ws.plans?.();if(!p)throw new AgentError('SESSION_REQUIRED','plan.execute needs a running session',{},400);return p;}
 async t_plan_execute(a:Result){const r=await this.planner().execute(a.plan as Plan);return {...r,ok:r.ok!==false};}
 async t_plan_status(a:Result){return this.planner().status(String(a.requestId)) as Result;}
 async t_plan_cancel(a:Result){return this.planner().cancel(String(a.requestId)) as Result;}
 async t_export(a:Result){const r=await this.ws.exportFile(a.profile as 'editable'|'standalone',this.expected(a));return {...r,compatibility:exportCapabilities(this.m(),a.profile==='editable'?'editable':'standalone').targets[0]};}
}
export function capabilitiesOffline(){return {ok:true,tool:'capabilities',schemaVersion:2,tools:TOOLS,conventions:CONVENTIONS};}
export {frameState};
