import type {VectorDocument} from './document.js';
import {safeId} from './document.js';
import {elements,SVG_NS,parseSvg} from '../converter/svg.js';
import {segments,pathData,transformPath,topology,type Point} from './geometry.js';
import {regionBounds,regionPath,boundaryPins} from './warp.js';
import {buildFeature,TEMPLATES,templateOf} from './expression.js';
import {FLUID_PRESETS,MODIFIER_KINDS,pathsBounds,flowFilter} from './modifiers.js';
import {normalizePair} from './morph.js';
import {validateRegion,invalidateBoxes,pathBoxes,semanticOperation,LEVELS} from './semantic.js';
import {isEasing,filterId,frameState} from './animation.js';
import {DEFAULT_LAYERS,PROPERTIES,type Operation,type Project,type Modifier,type Keyframe,type Viseme,type FilterPrimitive,type Track} from './model.js';
const num=(n:unknown,min=-1e6,max=1e6,label='value')=>{if(typeof n!=='number'||!Number.isFinite(n)||n<min||n>max)throw Error(`Invalid ${label}`);return n;};
const paramName=(s:string)=>{if(typeof s!=='string'||!/^[a-z][\w.-]{0,60}(@[a-z][\w-]{0,40})?$/i.test(s)||['__proto__','constructor','prototype'].includes(s))throw Error(`Invalid parameter name ${s}`);return s;};
const ensureParam=(p:Project,name:string,min=0,max=1)=>{p.params??={};const base=name.split('@')[0];if(!p.params[name])p.params[name]={min:['look-x','look-y'].includes(base)?-1:min,max,default:0};};
export const DEFAULT_VISEMES:Record<Viseme,Record<string,number>>={rest:{},A:{'mouth-open':.75,'mouth-wide':.2},E:{'mouth-wide':.6,'mouth-open':.3},I:{'mouth-wide':.7,'mouth-open':.15},O:{'mouth-round':.8,'mouth-open':.5},U:{'mouth-round':1,'mouth-open':.2},MBP:{'lips-closed':1},FV:{'lips-closed':.5,'mouth-open':.1},L:{'mouth-open':.35},WQ:{'mouth-round':.9}};
const FILTER_TAGS:Record<FilterPrimitive['kind'],string>={blur:'feGaussianBlur',shadow:'feDropShadow','color-matrix':'feColorMatrix',turbulence:'feTurbulence',displacement:'feDisplacementMap',morphology:'feMorphology',blend:'feBlend',composite:'feComposite',offset:'feOffset',lighting:'feDiffuseLighting',flood:'feFlood',merge:'feMerge'};
const FILTER_ATTRS=new Set(['stdDeviation','dx','dy','flood-color','flood-opacity','type','values','baseFrequency','numOctaves','seed','stitchTiles','scale','xChannelSelector','yChannelSelector','operator','radius','mode','k1','k2','k3','k4','surfaceScale','diffuseConstant','lighting-color','x','y','width','height']);
export const DRIVER_ATTRS=['stdDeviation','baseFrequency','scale','dx','dy','radius','flood-opacity','k1','k2','k3','k4','opacity','stroke-width','fill-opacity','stroke-opacity','r','rx','ry','cx','cy'];
// Paths affected by a target: descendants plus the alpha-mask copies created by region.extract.
export function expandPaths(m:VectorDocument,ids:string[],includeMasks=true){const out:string[]=[];
 for(const id of ids){const e=m.index.get(id);if(!e)throw Error(`Target not found: ${id}`);const all=[e,...elements(e)];for(const x of all)if(x.localName==='path'&&x.getAttribute('id'))out.push(x.getAttribute('id')!);
  if(includeMasks)for(const x of all){const ref=/^url\(#([^)]+)\)$/.exec(x.getAttribute('mask')??'')?.[1];const mask=ref?m.index.get(ref):undefined;if(mask?.getAttribute('data-mai-region-alpha'))for(const p of elements(mask))if(p.localName==='path'&&p.getAttribute('id'))out.push(p.getAttribute('id')!);}}
 return [...new Set(out)];}
function defs(m:VectorDocument){const d=elements(m.doc).find(e=>e.localName==='defs'&&e.parentNode===m.doc.documentElement)??m.doc.createElementNS(SVG_NS,'defs');if(!d.parentNode)m.doc.documentElement.insertBefore(d,m.doc.documentElement.firstChild);return d;}
const freeId=(m:VectorDocument,id:string)=>{safeId(id);if(m.index.has(id))throw Error(`ID already exists: ${id}`);return id;};
function intersects(b:{x0:number;y0:number;x1:number;y1:number},r:{x:number;y:number;width:number;height:number}){return !(b.x1<r.x||b.x0>r.x+r.width||b.y1<r.y||b.y0>r.y+r.height);}
function inflateRegion(r:import('./model.js').Region,by:number):import('./model.js').Region{if(r.kind==='ellipse')return {...r,rx:r.rx+by,ry:r.ry+by};if(r.kind==='rect')return {kind:'rect',x:r.x-by,y:r.y-by,width:r.width+2*by,height:r.height+2*by};const c={x:r.points.reduce((s,p)=>s+p.x,0)/r.points.length,y:r.points.reduce((s,p)=>s+p.y,0)/r.points.length};return {kind:'polygon',points:r.points.map(p=>{const d=Math.hypot(p.x-c.x,p.y-c.y)||1;return {x:p.x+(p.x-c.x)/d*by,y:p.y+(p.y-c.y)/d*by};})};}
function setKey(p:Project,target:string,property:Track['property'],time:number,value:number|string,easing:Keyframe['easing']='linear',layer?:string){
 const l=layer&&layer!=='base'?layer:undefined;let track=p.tracks.find(t=>t.target===target&&t.property===property&&(t.layer??undefined)===l);if(!track){track={target,property,keys:[],...(l?{layer:l}:{})};p.tracks.push(track);}
 track.keys=track.keys.filter(k=>Math.abs(k.time-time)>1e-9);track.keys.push({time,value,easing});track.keys.sort((a,b)=>a.time-b.time);}
export function authoringOperation(m:VectorDocument,op:Operation,touched:Set<string>):boolean{const p=m.project;
 if(op.type.startsWith('semantic.')||op.type==='landmark.set'||op.type==='landmark.delete'){semanticOperation(m,op);return false;}
 switch(op.type){
  case 'preservation':if(!['strict','balanced','free'].includes(op.mode))throw Error('Preservation mode: strict | balanced | free');p.preservation=op.mode;return false;
  case 'decision.log':{const d=op.decision;if(typeof d.kind!=='string'||d.kind.length>60||typeof d.summary!=='string'||d.summary.length>2000||!['user','agent'].includes(d.source))throw Error('Invalid decision');(p.decisions??=[]).push({...d,at:new Date().toISOString()});p.decisions=p.decisions.slice(-500);return false;}
  case 'choice.accept':{const a=op.acceptance;if(!/^[a-zA-Z][\w-]{0,60}$/.test(a.boardId)||!Number.isInteger(a.version)||a.version<1||!/^[a-zA-Z][\w-]{0,60}$/.test(a.option)||!['user-direction','editor-choice'].includes(a.source)||(a.text!==undefined&&(typeof a.text!=='string'||a.text.length>4000)))throw Error('Invalid choice acceptance');if(a.supersedes!==undefined&&!/^[a-zA-Z][\w-]{0,60}$/.test(a.supersedes))throw Error('Invalid choice acceptance');const last=[...(p.acceptances??[])].reverse().find(x=>x.boardId===a.boardId&&x.version===a.version);if(last?a.supersedes!==last.option:a.supersedes!==undefined)throw Object.assign(Error(last?`This board version was already accepted (${last.option}); a new acceptance must supersede it explicitly`:'There is no acceptance to supersede'),{code:'STALE_CHOICE',status:409});(p.acceptances??=[]).push({...structuredClone(a),at:new Date().toISOString()});p.acceptances=p.acceptances.slice(-200);return false;}
  case 'baseline.add':{const b=op.baseline;safeId(b.id);if(!/^[a-f0-9]{64}$/.test(b.sha256)||typeof b.label!=='string'||b.label.length>200||!['unreviewed','human-approved'].includes(b.approval))throw Error('Invalid baseline');if(b.source.kind==='file'&&(typeof b.source.path!=='string'||b.source.path.includes('..')||b.source.path.startsWith('/')))throw Error('Baseline file must be a project-relative path');if((p.baselines??[]).some(x=>x.id===b.id))throw Error('Baselines are immutable: use a new id');(p.baselines??=[]).push(structuredClone(b));return false;}
  case 'region.extract':{
   const id=freeId(m,op.id);for(const suffix of ['art','clip','alpha','cut'])freeId(m,`${id}-${suffix}`);validateRegion(op.region);const source=m.element(op.source);
   const margin=num(op.margin??2,0,200,'margin'),b=regionBounds(op.region),box={x:b.x-margin,y:b.y-margin,width:b.width+2*margin,height:b.height+2*margin};const boxes=pathBoxes(m);
   const paths=elements(source).filter(e=>e.localName==='path'&&!m.inDefs(e)&&(()=>{const bb=boxes.get(e.getAttribute('id')??'');return bb?intersects(bb,box):false;})());
   if(!paths.length)throw Error('Region contains no source paths');if(paths.length>6000)throw Error(`Region has ${paths.length} paths; use a tighter region (max 6000)`);
   const group=m.doc.createElementNS(SVG_NS,'g');group.setAttribute('id',id);group.setAttribute('data-mai-name',String(op.name).slice(0,200));group.setAttribute('data-mai-region',JSON.stringify(op.region));
   const art=m.doc.createElementNS(SVG_NS,'g');art.setAttribute('id',`${id}-art`);group.appendChild(art);const d=defs(m);
   // Clip slightly larger than the cut: avoids anti-aliasing seams where both edges meet.
   if(op.clip!==false){const clip=m.doc.createElementNS(SVG_NS,'clipPath');clip.setAttribute('id',`${id}-clip`);clip.setAttribute('clipPathUnits','userSpaceOnUse');const cp=m.doc.createElementNS(SVG_NS,'path');cp.setAttribute('d',pathData(segments(regionPath(inflateRegion(op.region,.75)))));clip.appendChild(cp);d.appendChild(clip);art.setAttribute('clip-path',`url(#${id}-clip)`);}
   let alphaSource:Element|undefined;let anc:Node|null=source;while(anc&&anc.nodeType===1&&!alphaSource){const ref=/^url\(#([^)]+)\)$/.exec((anc as Element).getAttribute('mask')??'')?.[1];if(ref)alphaSource=m.index.get(ref);anc=anc.parentNode;}
   if(!alphaSource)for(const x of elements(source)){const ref=/^url\(#([^)]+)\)$/.exec(x.getAttribute('mask')??'')?.[1];if(ref){alphaSource=m.index.get(ref);break;}}
   if(alphaSource&&op.alpha!==false){const mask=m.doc.createElementNS(SVG_NS,'mask');for(const a of Array.from(alphaSource.attributes))if(a.name!=='id')mask.setAttribute(a.name,a.value);mask.setAttribute('id',`${id}-alpha`);mask.setAttribute('data-mai-region-alpha',id);let k=0;
    for(const x of elements(alphaSource)){if(x.localName!=='path')continue;const bb=boxes.get(x.getAttribute('id')??'');let keep=bb?intersects(bb,box):false;if(!bb){try{const pts=segments(x.getAttribute('d')??'').flatMap(s=>s.points);if(pts.length)keep=intersects({x0:Math.min(...pts.map(q=>q.x)),y0:Math.min(...pts.map(q=>q.y)),x1:Math.max(...pts.map(q=>q.x)),y1:Math.max(...pts.map(q=>q.y))},box);}catch{}}
     if(!keep)continue;const c=x.cloneNode(true) as Element;c.setAttribute('id',`${id}-a${++k}`);if(c.getAttribute('transform')){c.setAttribute('d',transformPath(c.getAttribute('d')!,c.getAttribute('transform')!));c.removeAttribute('transform');}mask.appendChild(c);}
    d.appendChild(mask);art.setAttribute('mask',`url(#${id}-alpha)`);}
   else if(alphaSource)art.setAttribute('mask',`url(#${alphaSource.getAttribute('id')})`);
   let i=0;for(const e of paths){const c=e.cloneNode(true) as Element;c.setAttribute('id',`${id}-p${++i}`);c.removeAttribute('data-mai-locked');const tr=[c.getAttribute('transform')??''];let a=e.parentNode as Element|null;while(a&&a!==source&&a.nodeType===1){if(a.getAttribute('transform'))tr.unshift(a.getAttribute('transform')!);a=a.parentNode as Element|null;}const t=tr.filter(Boolean).join(' ');if(t){c.setAttribute('d',transformPath(c.getAttribute('d')!,t));c.removeAttribute('transform');}art.appendChild(c);}
   if(op.hideSource!==false){const cut=m.doc.createElementNS(SVG_NS,'clipPath');cut.setAttribute('id',`${id}-cut`);cut.setAttribute('clipPathUnits','userSpaceOnUse');const cp=m.doc.createElementNS(SVG_NS,'path');cp.setAttribute('clip-rule','evenodd');cp.setAttribute('d',`M-100000 -100000H100000V100000H-100000Z ${pathData(segments(regionPath(op.region)))}`);cut.appendChild(cp);const old=source.getAttribute('clip-path');if(old)cut.setAttribute('clip-path',old);d.appendChild(cut);source.setAttribute('clip-path',`url(#${id}-cut)`);}
   // Insert above the source's top-level ancestor so it renders over the hidden area in the same stacking context.
   let anchor:Element=source;while(anchor.parentNode&&anchor.parentNode!==m.doc.documentElement&&(anchor.parentNode as Element).getAttribute('data-mai-alpha-group')==='true')anchor=anchor.parentNode as Element;anchor.parentNode!.insertBefore(group,anchor.nextSibling);
   // Later operations in the same transaction (e.g. semantic.label) must see the new layer.
   m.reindex();invalidateBoxes(m);touched.add(id);return true;}
  case 'param.define':{paramName(op.name);const d=op.def;num(d.min,-1e4,1e4,'min');num(d.max,-1e4,1e4,'max');num(d.default,d.min,d.max,'default');if(d.min>=d.max)throw Error('Parameter min must be < max');(p.params??={})[op.name]={min:d.min,max:d.max,default:d.default,...(d.label?{label:String(d.label).slice(0,100)}:{}),...(d.group?{group:String(d.group).slice(0,60)}:{})};return false;}
  case 'param.set':case 'expression.set':{let params:Record<string,number>={...op.params};
   if(op.type==='expression.set'&&op.preset){const preset=p.expression?.presets[op.preset];if(!preset)throw Error('Expression preset not found');const w=num(op.weight??1,0,1,'weight');params={...Object.fromEntries(Object.entries(preset).map(([k,v])=>[k,v*w])),...params};}
   if(!Object.keys(params).length||Object.keys(params).length>200)throw Error('Set 1–200 parameters');
   for(const [k,v]of Object.entries(params)){paramName(k);num(v,-1e4,1e4,'parameter value');ensureParam(p,k);
    if(op.time===undefined){p.params![k].default=Math.max(p.params![k].min,Math.min(p.params![k].max,v));}
    else{num(op.time,0,p.duration,'time');const easing=op.easing??'ease-in-out';if(!isEasing(easing))throw Error('Unknown easing');setKey(p,k,'param',op.time,v,easing,op.layer??(op.type==='expression.set'?'expression':undefined));}}
   return false;}
  case 'layer.set':{const l=op.layer;safeId(l.id);if(typeof l.name!=='string'||l.name.length>100||!['override','additive'].includes(l.blend))throw Error('Invalid layer');num(l.weight,0,1,'layer weight');p.layers??=structuredClone(DEFAULT_LAYERS);const i=p.layers.findIndex(x=>x.id===l.id);const clean={id:l.id,name:l.name,blend:l.blend,weight:l.weight,...(l.mute?{mute:true}:{}),...(l.solo?{solo:true}:{}),...(l.locked?{locked:true}:{})};if(i>=0)p.layers[i]=clean;else p.layers.push(clean);if(p.layers.length>32)throw Error('Too many layers');return false;}
  case 'marker.set':{safeId(op.marker.id);num(op.marker.time,0,p.duration,'marker time');p.markers=[...(p.markers??[]).filter(x=>x.id!==op.marker.id),{id:op.marker.id,time:op.marker.time,label:String(op.marker.label).slice(0,120),kind:op.marker.kind??'marker'}].sort((a,b)=>a.time-b.time);return false;}
  case 'marker.delete':p.markers=(p.markers??[]).filter(x=>x.id!==op.id);return false;
  case 'region.time':{const r=op.region;safeId(r.id);num(r.start,0,p.duration,'start');num(r.end,0,p.duration,'end');if(r.end<=r.start)throw Error('Region end must follow start');if(r.mode&&!['loop','ping-pong','hold','note'].includes(r.mode))throw Error('Unknown region mode');p.regions=[...(p.regions??[]).filter(x=>x.id!==r.id),{id:r.id,start:r.start,end:r.end,label:String(r.label).slice(0,120),mode:r.mode??'note'}];return false;}
  case 'region.time.delete':p.regions=(p.regions??[]).filter(x=>x.id!==op.id);return false;
  case 'clip.define':{const c=op.clip;safeId(c.id);num(c.start,0,p.duration,'clip start');num(c.end,0,p.duration,'clip end');if(c.end<=c.start)throw Error('Clip end must follow start');if(c.targets)c.targets.forEach(safeId);p.clips=[...(p.clips??[]).filter(x=>x.id!==c.id),{id:c.id,name:String(c.name).slice(0,120),start:c.start,end:c.end,...(c.targets?{targets:c.targets}:{})}];return false;}
  case 'clip.place':{const c=(p.clips??[]).find(x=>x.id===op.clip);if(!c)throw Error('Clip not found');const speed=num(op.speed??1,.05,20,'speed'),len=(c.end-c.start)/speed,at=num(op.at,0,p.duration,'time');if(at+len*(op.pingpong?2:1)>p.duration+1e-9)throw Error('Placed clip exceeds the timeline duration');
   const source=p.tracks.filter(t=>(!c.targets||c.targets.includes(t.target))&&t.keys.some(k=>k.time>=c.start&&k.time<=c.end));if(!source.length)throw Error('Clip contains no keyframes');
   for(const t of source){const target=op.targets?.[t.target]??t.target;if(target!==t.target&&t.property!=='param'&&!t.property.startsWith('bone')&&!t.property.startsWith('mesh'))m.editable(target);const keys=t.keys.filter(k=>k.time>=c.start&&k.time<=c.end);
    const place=(k:Keyframe,reverse:boolean,offset:number)=>{const local=(k.time-c.start)/speed;setKey(p,target,t.property,Number((at+offset+(reverse?len-local:local)).toFixed(6)),k.value,k.easing,op.layer??t.layer);};
    for(const k of keys)place(k,!!op.reverse,0);if(op.pingpong)for(const k of keys)place(k,!op.reverse,len);}
   return false;}
  case 'expression.feature':{const f=op.feature;safeId(f.id);if(typeof f.role!=='string'||!/^[a-z][a-z0-9-]{0,59}$/.test(f.role))throw Error('Invalid feature role');
   const ids=expandPaths(m,f.paths,false);if(!ids.length||ids.length>4000)throw Error('Expression feature needs 1–4000 paths');const rest:Record<string,string>={};
   for(const id of ids){const e=m.editable(id);if(e.getAttribute('transform')){m.operation({type:'attributes',id,attrs:{d:transformPath(e.getAttribute('d')!,e.getAttribute('transform')!)}},touched);e.removeAttribute('transform');}rest[id]=e.getAttribute('d')!;
    if(p.tracks.some(t=>t.target===id&&t.property==='d')||p.skins.some(s=>s.target===id)||(p.modifiers??[]).some(x=>x.targets.includes(id)&&x.kind!=='flow'))throw Error(`Path ${id} already has d animation, rig or modifier; expression features own their geometry`);}
   if(f.region)validateRegion(f.region);for(const [k,pt]of Object.entries(f.landmarks)){safeId(k);num(pt.x);num(pt.y);}const tmpl=templateOf(f.role);if(tmpl){const need=TEMPLATES[tmpl].axis;for(const n of need)if(!f.landmarks[n])throw Error(`Role ${f.role} requires landmarks ${TEMPLATES[tmpl].landmarks.join(', ')} (missing ${n})`);}
   if(f.rigid)for(const [lm,list]of Object.entries(f.rigid)){if(!f.landmarks[lm])throw Error('Rigid group needs a landmark');list.forEach(x=>{if(!ids.includes(x))throw Error('Rigid paths must belong to the feature');});}
   if(p.expression?.features.some(x=>x.id!==f.id&&x.paths.some(id=>ids.includes(id))))throw Error('A path can belong to one expression feature');
   const feature=buildFeature({...f,paths:ids,pins:f.pins??(f.region?boundaryPins(f.region,28):undefined)},rest);if(Object.values(feature.rest).reduce((n,d)=>n+segments(d).reduce((a,s)=>a+s.points.length,0),0)>80000)throw Error('Feature exceeds 80,000 points; use a tighter region');
   p.expression??={features:[],drivers:[],presets:{}};p.expression.features=[...p.expression.features.filter(x=>x.id!==f.id),feature];for(const k of Object.keys(feature.keys))ensureParam(p,k);return false;}
  case 'expression.key':{const f=p.expression?.features.find(x=>x.id===op.feature);if(!f)throw Error('Expression feature not found');paramName(op.param);for(const [lm,d]of Object.entries(op.landmarks)){if(!f.landmarks[lm])throw Error(`Unknown landmark ${lm}`);num(d.dx,-1e4,1e4);num(d.dy,-1e4,1e4);}f.keys[op.param]=structuredClone(op.landmarks);ensureParam(p,op.param);return false;}
  case 'expression.freeze':{const f=p.expression?.features.find(x=>x.id===op.feature);if(!f)throw Error('Expression feature not found');if(op.frozen)f.frozen=true;else delete f.frozen;return false;}
  case 'expression.remove':{if(!p.expression?.features.some(x=>x.id===op.feature))throw Error('Expression feature not found');p.expression.features=p.expression.features.filter(x=>x.id!==op.feature);return false;}
  case 'expression.driver':{const d=op.driver;safeId(d.id);paramName(d.param);const e=m.index.get(d.target);if(!e)throw Error('Driver target not found');const attr=d.property.startsWith('attr:')?d.property.slice(5):null;
   if(!(['x','y','rotation','scaleX','scaleY','opacity','d','fill'].includes(d.property)||(attr&&DRIVER_ATTRS.includes(attr))))throw Error('Unsupported driver property');if(!Array.isArray(d.points)||d.points.length<2||d.points.length>32)throw Error('Driver needs 2–32 points');
   for(const [x,v]of d.points){num(x,-1e4,1e4);if(d.property==='d'){if(typeof v!=='string'||topology(v)!==topology(String(d.points[0][1])))throw Error('Driver path values need identical topology');}else if(d.property==='fill'){if(typeof v!=='string'||!/^#[\da-f]{6}$/i.test(v))throw Error('Driver colors need #RRGGBB');}else num(v as number,-1e6,1e6);}
   if(!m.inDefs(e)&&['x','y','rotation','scaleX','scaleY'].includes(d.property)){m.editable(d.target);m.remember(d.target);}
   p.expression??={features:[],drivers:[],presets:{}};p.expression.drivers=[...p.expression.drivers.filter(x=>x.id!==d.id),{...d,points:d.points.map(([a,b])=>[a,b])}];ensureParam(p,d.param);return false;}
  case 'expression.driver.remove':if(p.expression)p.expression.drivers=p.expression.drivers.filter(x=>x.id!==op.id);return false;
  case 'expression.preset':{paramName(op.name.replace(/[^\w.-]/g,'_'));for(const [k,v]of Object.entries(op.params)){paramName(k);num(v,-1e4,1e4);}p.expression??={features:[],drivers:[],presets:{}};p.expression.presets[op.name]={...op.params};return false;}
  case 'fluid.animate':case 'modifier.add':{
   const spec=op.type==='fluid.animate'?{id:op.id,kind:'flow' as const,targets:op.targets,preset:op.preset,anchor:op.anchor,direction:op.direction,technique:op.technique,params:op.params??{}}:op.modifier;
   safeId(spec.id);if((p.modifiers??[]).some(x=>x.id===spec.id))throw Error('Modifier ID exists');if(!MODIFIER_KINDS.includes(spec.kind))throw Error('Unknown modifier kind');if(spec.preset&&!FLUID_PRESETS[spec.preset])throw Error('Unknown fluid preset');
   const ids=expandPaths(m,spec.targets);if(!ids.length||ids.length>8000)throw Error('Modifier needs 1–8000 paths');const rest:Record<string,string>={};let points=0;
   for(const id of ids){const e=m.index.get(id)!;if(e.getAttribute('transform'))throw Error(`Path ${id} has a transform; prepare it with region.extract first`);rest[id]=e.getAttribute('d')??'';points+=segments(rest[id]).reduce((a,s)=>a+s.points.length,0);if((p.expression?.features??[]).some(f=>f.paths.includes(id))&&spec.kind==='flow')throw Error(`${id} belongs to an expression feature; flow it through a separate region`);}
   if(points>250000)throw Error('Modifier exceeds 250,000 points');const preset=spec.preset?FLUID_PRESETS[spec.preset]:undefined;const params:Record<string,number>={...(preset?.params??{}),...spec.params};
   if(op.type==='fluid.animate')params.samples=params.samples??({draft:12,balanced:24,high:48}[op.quality??'balanced']);for(const [k,v]of Object.entries(params)){safeId(k);num(v,-1e5,1e5,`modifier parameter ${k}`);}
   const colorIds=ids.filter(id=>!m.inDefs(m.index.get(id)!)),bounds=pathsBounds(colorIds.map(id=>rest[id]));const dir=spec.direction??preset?.direction??{x:0,y:-1};
   const anchor=spec.anchor??(spec.preset?(dir.y<-.5?{x:bounds.x+bounds.width/2,y:bounds.y+bounds.height}:dir.y>.5?{x:bounds.x+bounds.width/2,y:bounds.y}:{x:bounds.x,y:bounds.y+bounds.height/2}):undefined);
   if(anchor){num(anchor.x);num(anchor.y);}num(dir.x,-1e3,1e3);num(dir.y,-1e3,1e3);
   const mod:Modifier={id:spec.id,name:(op.type==='modifier.add'&&op.modifier.name)||`${spec.preset??spec.kind} · ${spec.id}`,kind:spec.kind,enabled:op.type==='modifier.add'?op.modifier.enabled!==false:true,targets:ids,rest,params,...(spec.preset?{preset:spec.preset}:{}),...(anchor?{anchor}:{}),direction:dir,technique:spec.technique??'geometry',bounds:{x:Number(bounds.x.toFixed(2)),y:Number(bounds.y.toFixed(2)),width:Number(bounds.width.toFixed(2)),height:Number(bounds.height.toFixed(2))}};
   (p.modifiers??=[]).push(mod);if(mod.technique==='filter')installFilter(m,mod,spec.targets);return mod.technique==='filter';}
  case 'modifier.update':{const mod=(p.modifiers??[]).find(x=>x.id===op.id);if(!mod)throw Error('Modifier not found');if(op.params)for(const [k,v]of Object.entries(op.params)){safeId(k);mod.params[k]=num(v,-1e5,1e5,`modifier parameter ${k}`);}if(op.enabled!==undefined)mod.enabled=!!op.enabled;if(op.anchor){num(op.anchor.x);num(op.anchor.y);mod.anchor=op.anchor;}if(op.direction){num(op.direction.x,-1e3,1e3);num(op.direction.y,-1e3,1e3);mod.direction=op.direction;}if(op.name)mod.name=String(op.name).slice(0,120);
   let reload=false;if(op.technique&&op.technique!==mod.technique){if(op.technique==='filter'){mod.technique='filter';installFilter(m,mod,[groupOf(m,mod)]);}else{removeFilter(m,mod);mod.technique='geometry';}reload=true;}
   else if(mod.technique==='filter'&&(op.params||op.anchor||op.direction)){removeFilter(m,mod);installFilter(m,mod,[groupOf(m,mod)]);reload=true;}
   if(mod.technique==='filter'){const host=m.index.get(groupOf(m,mod));if(host)host.setAttribute('filter',mod.enabled?`url(#${filterId(mod)})`:'none');reload=true;}return reload;}
  case 'modifier.remove':{const mod=(p.modifiers??[]).find(x=>x.id===op.id);if(!mod)throw Error('Modifier not found');if(mod.technique==='filter')removeFilter(m,mod);p.modifiers=p.modifiers!.filter(x=>x!==mod);return mod.technique==='filter';}
  case 'modifier.order':{const list=p.modifiers??[],i=list.findIndex(x=>x.id===op.id);if(i<0)throw Error('Modifier not found');const [mod]=list.splice(i,1);list.splice(Math.max(0,Math.min(list.length,Math.round(op.index))),0,mod);return false;}
  case 'modifier.bake':{const mod=(p.modifiers??[]).find(x=>x.id===op.id);if(!mod)throw Error('Modifier not found');if(mod.technique==='filter')throw Error('Filter modifiers export natively; bake geometry modifiers only');const n=Math.round(num(op.samples??mod.params.samples??24,2,240,'samples'));
   if(mod.targets.some(id=>m.inDefs(m.index.get(id)!)))throw Error('Modifier drives alpha-mask paths; keep it live (export bakes it) instead of converting to keyframes');
   const frames=Array.from({length:n+1},(_,i)=>p.duration*i/n);const states=frames.map(t=>frameState(p,t));p.modifiers=p.modifiers!.filter(x=>x!==mod);
   for(const id of mod.targets)frames.forEach((t,i)=>setKey(p,id,'d',Number(t.toFixed(6)),states[i].attrs[id]?.d??mod.rest[id],'linear'));return false;}
  case 'secondary.add':case 'secondary.update':{const s=op.type==='secondary.add'?structuredClone(op.secondary):{...(p.secondary??[]).find(x=>x.id===op.id)!,...structuredClone(op.secondary)};if(op.type==='secondary.update'&&!(p.secondary??[]).some(x=>x.id===op.id))throw Error('Secondary motion not found');
   safeId(s.id);if(!['spring','look-at','follow'].includes(s.kind)||!['rotation','x','y'].includes(s.property))throw Error('Invalid secondary motion');if(s.driverProperty&&!['x','y','rotation','scaleX','scaleY'].includes(s.driverProperty))throw Error('Invalid driver property');
   m.editable(s.target);m.remember(s.target);if(s.kind==='look-at')paramName(s.driver);else m.element(s.driver);num(s.stiffness,0,10000,'stiffness');num(s.damping,0,1000,'damping');num(s.gain,-1000,1000,'gain');num(s.delay,0,10,'delay');num(s.limit,0,360,'limit');
   if(op.type==='secondary.add'&&(p.secondary??[]).some(x=>x.id===s.id))throw Error('Secondary motion ID exists');p.secondary=[...(p.secondary??[]).filter(x=>x.id!==s.id),s];if(s.kind==='look-at')ensureParam(p,s.driver);return false;}
  case 'secondary.remove':p.secondary=(p.secondary??[]).filter(x=>x.id!==op.id);return false;
  case 'secondary.bake':{const s=(p.secondary??[]).find(x=>x.id===op.id);if(!s)throw Error('Secondary motion not found');const n=Math.round(num(op.samples??Math.max(12,p.duration*p.fps/2),2,600,'samples'));const values=Array.from({length:n+1},(_,i)=>{const t=p.duration*i/n;return [t,frameState(p,t).poses[s.target]?.[s.property]??0] as const;});p.secondary=p.secondary!.filter(x=>x!==s);for(const [t,v]of values)setKey(p,s.target,s.property,Number(t.toFixed(6)),Number(v.toFixed(4)),'linear');return false;}
  case 'morph.apply':{const e=m.editable(op.id);if(e.localName!=='path')throw Error('Morph needs a path');const to=op.to.startsWith('#')?m.element(op.to.slice(1)).getAttribute('d')??'':op.to;const time=num(op.time,0,p.duration,'time'),from=num(op.from??0,0,p.duration,'from');if(from>=time)throw Error('Morph start must precede end');
   if(p.skins.some(s=>s.target===op.id)||(p.expression?.features??[]).some(f=>f.paths.includes(op.id)))throw Error('Morph target is rigged or part of an expression feature');
   const n=normalizePair(e.getAttribute('d')!,to);const existing=p.tracks.filter(t=>t.target===op.id&&t.property==='d');if(existing.some(t=>t.keys.some(k=>topology(String(k.value))!==topology(n.from))))throw Error('Existing path keyframes use another topology; delete them or morph from a keyframe value');
   e.setAttribute('d',n.from);if(p.baseAttributes[op.id])p.baseAttributes[op.id].d=n.from;const easing=op.easing??'ease-in-out';if(!isEasing(easing))throw Error('Unknown easing');setKey(p,op.id,'d',from,n.from,easing,op.layer);setKey(p,op.id,'d',time,n.to,easing,op.layer);touched.add(op.id);return false;}
  case 'state.input':{const i=op.input;if(!/^[a-zA-Z][\w-]{0,40}$/.test(i.name)||!['boolean','number','trigger','enum'].includes(i.type))throw Error('Invalid state input');if(i.type==='enum'&&(!Array.isArray(i.options)||!i.options.length||!i.options.includes(String(i.default))))throw Error('Enum input needs options including default');if(i.type==='number')num(i.default as number);const sm=machine(p);sm.inputs=[...sm.inputs.filter(x=>x.name!==i.name),{...i}];return false;}
  case 'state.add':{const s=op.state;safeId(s.id);if(typeof s.name!=='string'||s.name.length>80)throw Error('Invalid state');if(s.params)for(const [k,v]of Object.entries(s.params)){paramName(k);num(v,-1e4,1e4);ensureParam(p,k);}if(s.clip&&!(p.clips??[]).some(c=>c.id===s.clip))throw Error('State clip not found');if(s.speed!==undefined)num(s.speed,.05,20);const sm=machine(p);sm.states=[...sm.states.filter(x=>x.id!==s.id),{...s}];if(!sm.initial)sm.initial=s.id;return false;}
  case 'state.transition':{const t=op.transition,sm=machine(p);if(t.from!=='*'&&!sm.states.some(s=>s.id===t.from)||!sm.states.some(s=>s.id===t.to))throw Error('Transition states must exist (from may be *)');num(t.duration,0,30,'duration');if(t.exitTime!==undefined)num(t.exitTime,0,1,'exitTime');for(const c of t.conditions){const input=sm.inputs.find(i=>i.name===c.input);if(!input||!['==','!=','<','<=','>','>=','set'].includes(c.op))throw Error('Invalid transition condition');if(c.op==='set'&&input.type!=='trigger')throw Error('Only triggers use "set"');}if(sm.transitions.length>=256)throw Error('Too many transitions');sm.transitions.push(structuredClone(t));return false;}
  case 'state.listener':{const l=op.listener,sm=machine(p);if(!['pointerenter','pointerleave','pointerdown','pointerup','pointermove','click','scroll','keydown','custom'].includes(l.event)||!['set','fire','track-pointer'].includes(l.action.kind)||!sm.inputs.some(i=>i.name===l.action.input))throw Error('Invalid listener');if(l.target)m.element(l.target);if(sm.listeners.length>=64)throw Error('Too many listeners');sm.listeners.push(structuredClone(l));return false;}
  case 'state.initial':{const sm=machine(p);if(!sm.states.some(s=>s.id===op.id))throw Error('State not found');sm.initial=op.id;return false;}
  case 'state.remove':{const sm=machine(p);if(op.kind==='input')sm.inputs=sm.inputs.filter(i=>i.name!==op.id);else if(op.kind==='state'){sm.states=sm.states.filter(s=>s.id!==op.id);sm.transitions=sm.transitions.filter(t=>t.from!==op.id&&t.to!==op.id);}else if(op.kind==='transition')sm.transitions.splice(op.index??-1,1);else sm.listeners.splice(op.index??-1,1);return false;}
  case 'component.define':{safeId(op.id);if((p.components??[]).some(c=>c.id===op.id))throw Error('Component exists');const master=m.editable(op.master);const slots:Record<string,string[]>={};
   for(const [slot,ids]of Object.entries(op.slots??{})){safeId(slot);const paths=expandPaths(m,ids,false);if(!paths.length)throw Error(`Slot ${slot} has no paths`);for(const id of paths){const e=m.index.get(id)!;let a:Node|null=e;let inside=false;while(a){if(a===master as unknown as Node)inside=true;a=a.parentNode;}if(!inside)throw Error('Slot paths must be inside the master');
     // Instances override slots with CSS variables; the fallback keeps the master's exact color.
     const fill=e.getAttribute('fill')??'#000000';if(/^#[\da-f]{3,8}$/i.test(fill)){e.setAttribute('style',`${e.getAttribute('style')?e.getAttribute('style')+';':''}fill:var(--mai-${slot},${fill})`);}
    }const host=m.doc.createElementNS(SVG_NS,'g');host.setAttribute('id',freeId(m,`${op.id}-slot-${slot}`));host.setAttribute('style',`filter:var(--mai-${slot}-filter,none)`);const first=m.index.get(paths[0])!;first.parentNode!.insertBefore(host,first);for(const id of paths){const e=m.index.get(id)!;if(e.parentNode===first.parentNode)host.appendChild(e);}slots[slot]=paths;}
   master.setAttribute('data-mai-component',op.id);(p.components??=[]).push({id:op.id,name:String(op.name).slice(0,120),master:op.master,slots,variants:{}});return true;}
  case 'component.instance':{const c=(p.components??[]).find(x=>x.id===op.component);if(!c)throw Error('Component not found');const id=freeId(m,op.id);const parent=op.parent?m.editable(op.parent):m.doc.documentElement;const use=m.doc.createElementNS(SVG_NS,'use');use.setAttribute('id',id);use.setAttribute('href',`#${c.master}`);use.setAttribute('data-mai-instance',c.id);
   const x=num(op.x??0),y=num(op.y??0),s=num(op.scale??1,.01,100,'scale');use.setAttribute('transform',`translate(${x} ${y}) scale(${s})`);parent.appendChild(use);if(op.overrides)applyOverrides(m,use,c,op.overrides);return true;}
  case 'component.override':{const use=m.editable(op.instance);const c=(p.components??[]).find(x=>x.id===use.getAttribute('data-mai-instance'));if(!c)throw Error('Not a component instance');applyOverrides(m,use,c,op.overrides);touched.add(op.instance);return true;}
  case 'component.variant':{const c=(p.components??[]).find(x=>x.id===op.component);if(!c)throw Error('Component not found');safeId(op.variant);for(const [slot,o]of Object.entries(op.slots)){if(!c.slots[slot])throw Error(`Unknown slot ${slot}`);for(const v of Object.values(o))if(!/^(#[\da-f]{6}|hue\(-?\d{1,3}\))$/i.test(v))throw Error('Variant values: #RRGGBB or hue(deg)');}c.variants[op.variant]=structuredClone(op.slots);return false;}
  case 'viseme.define':{if(!Object.hasOwn(DEFAULT_VISEMES,op.viseme))throw Error('Unknown viseme');for(const [k,v]of Object.entries(op.params)){paramName(k);num(v,0,1);}(p.visemes??={})[op.viseme]={...op.params};return false;}
  case 'lipsync':{if(!Array.isArray(op.cues)||op.cues.length<1||op.cues.length>5000)throw Error('Lip sync needs 1–5000 cues');const strength=num(op.strength??1,0,1,'strength'),table={...DEFAULT_VISEMES,...(p.visemes??{})};const names=[...new Set(Object.values(table).flatMap(v=>Object.keys(v)))];
   const cues=[...op.cues].sort((a,b)=>a.time-b.time);for(const c of cues){num(c.time,0,p.duration,'cue time');if(!Object.hasOwn(table,c.viseme))throw Error(`Unknown viseme ${c.viseme}`);}
   for(const name of names)ensureParam(p,name);for(const c of cues){const v=table[c.viseme as Viseme]??{};for(const name of names)setKey(p,name,'param',c.time,Number(((v[name]??0)*strength).toFixed(3)),'ease-in-out',op.layer??'lipsync');}return false;}
  case 'filter.set':{const id=op.id;safeId(id);const existing=m.index.get(id);if(existing&&existing.localName!=='filter')throw Error('ID is not a filter');if(!Array.isArray(op.primitives)||!op.primitives.length||op.primitives.length>24)throw Error('Filter needs 1–24 primitives');
   const f=m.doc.createElementNS(SVG_NS,'filter');f.setAttribute('id',id);f.setAttribute('x','-50%');f.setAttribute('y','-50%');f.setAttribute('width','200%');f.setAttribute('height','200%');f.setAttribute('color-interpolation-filters','sRGB');
   op.primitives.forEach((pr,i)=>{const tag=FILTER_TAGS[pr.kind];if(!tag)throw Error('Unknown filter primitive');const e=m.doc.createElementNS(SVG_NS,tag);e.setAttribute('id',`${id}-${i}`);for(const [k,v]of Object.entries(pr.attrs)){if(!FILTER_ATTRS.has(k))throw Error(`Filter attribute not allowed: ${k}`);const s=String(v);if(s.length>400||/[<>"]|url\(|javascript:|data:/i.test(s))throw Error('Unsafe filter value');if(k==='stdDeviation'&&s.split(/[\s,]+/).some(x=>Number(x)>200))throw Error('Blur radius over 200 is a performance risk');e.setAttribute(k,s);}
    for(const k of ['result','in','in2'] as const){const v=pr[k];if(v!==undefined){if(!/^[A-Za-z][\w-]{0,40}$/.test(v))throw Error('Invalid filter reference');e.setAttribute(k,v);}}
    if(pr.kind==='lighting'){const light=m.doc.createElementNS(SVG_NS,'fePointLight');for(const k of ['x','y','z'])light.setAttribute(k,String(num(Number((pr.attrs as Record<string,unknown>)['light-'+k]??0))));e.appendChild(light);for(const k of ['light-x','light-y','light-z'])e.removeAttribute(k);}
    if(pr.kind==='merge'){for(const input of String((pr.attrs as Record<string,unknown>).inputs??'').split(/[\s,]+/).filter(Boolean)){if(!/^[A-Za-z][\w-]{0,40}$/.test(input))throw Error('Invalid merge input');const n=m.doc.createElementNS(SVG_NS,'feMergeNode');n.setAttribute('in',input);e.appendChild(n);}e.removeAttribute('inputs');}
    f.appendChild(e);});
   if(existing)existing.parentNode!.replaceChild(f,existing);else defs(m).appendChild(f);if(op.target){const t=m.editable(op.target);t.setAttribute('filter',`url(#${id})`);if(p.baseAttributes[op.target])p.baseAttributes[op.target].filter=`url(#${id})`;}return true;}
  case 'filter.remove':{const f=m.index.get(op.id);if(!f||f.localName!=='filter')throw Error('Filter not found');if((p.modifiers??[]).some(x=>filterId(x)===op.id))throw Error('Filter belongs to a modifier; remove the modifier');f.parentNode!.removeChild(f);for(const e of elements(m.doc))if(e.getAttribute('filter')===`url(#${op.id})`)e.removeAttribute('filter');return true;}
 }
 throw Error(`Unknown operation ${(op as {type:string}).type}`);
}
function machine(p:Project){return p.stateMachine??={inputs:[],states:[],transitions:[],initial:'',listeners:[]};}
function groupOf(m:VectorDocument,mod:Modifier){const first=m.index.get(mod.targets.find(id=>!m.inDefs(m.index.get(id)!))??'');let g=first?.parentNode as Element|null;while(g&&g.nodeType===1&&!g.getAttribute('data-mai-region')&&g.parentNode!==m.doc.documentElement)g=g.parentNode as Element|null;const id=g?.getAttribute('id');if(!id)throw Error('Filter technique needs targets inside one group');return id;}
function installFilter(m:VectorDocument,mod:Modifier,hosts:string[]){if(mod.kind!=='flow')throw Error('Filter technique is available for flow modifiers');if(hosts.length!==1)throw Error('Filter technique needs exactly one target group');const host=m.editable(hosts[0]);if(host.getAttribute('filter'))throw Error('Target already has a filter');
 const fid=filterId(mod);freeId(m,fid);const f=flowFilter(mod,fid,m.project.duration);const parsed=parseSvg(`<svg xmlns="http://www.w3.org/2000/svg">${f.xml}</svg>`).documentElement.firstChild as Element;defs(m).appendChild(m.doc.importNode(parsed,true));host.setAttribute('filter',`url(#${fid})`);mod.filter=fid;}
function removeFilter(m:VectorDocument,mod:Modifier){const f=m.index.get(filterId(mod));f?.parentNode?.removeChild(f);for(const e of elements(m.doc))if(e.getAttribute('filter')===`url(#${filterId(mod)})`)e.removeAttribute('filter');delete mod.filter;}
function applyOverrides(m:VectorDocument,use:Element,c:import('./model.js').ComponentDef,overrides:Record<string,string|null>){
 const style=new Map((use.getAttribute('style')??'').split(';').map(s=>s.trim()).filter(Boolean).map(s=>{const i=s.indexOf(':');return [s.slice(0,i).trim(),s.slice(i+1).trim()] as [string,string];}));
 for(const [slot,value]of Object.entries(overrides)){if(!c.slots[slot])throw Error(`Unknown slot ${slot}`);style.delete(`--mai-${slot}`);style.delete(`--mai-${slot}-filter`);if(value===null)continue;
  if(/^#[\da-f]{6}$/i.test(value))style.set(`--mai-${slot}`,value);
  else{const h=/^hue\((-?\d{1,3})\)$/i.exec(value);if(!h)throw Error('Override: #RRGGBB (flat) or hue(deg) (keeps shading)');const fid=`mai-hue-${(Number(h[1])%360+360)%360}`;if(!m.index.has(fid)){const f=m.doc.createElementNS(SVG_NS,'filter');f.setAttribute('id',fid);f.setAttribute('color-interpolation-filters','sRGB');const cm=m.doc.createElementNS(SVG_NS,'feColorMatrix');cm.setAttribute('type','hueRotate');cm.setAttribute('values',String((Number(h[1])%360+360)%360));f.appendChild(cm);defs(m).appendChild(f);m.index.set(fid,f);}style.set(`--mai-${slot}-filter`,`url(#${fid})`);}}
 const text=[...style].map(([k,v])=>`${k}:${v}`).join(';');if(text)use.setAttribute('style',text);else use.removeAttribute('style');}
// Metadata validation for everything this module stores in the project.
export function validateAuthoring(p:Project){
 const P=p.params??{};if(Object.keys(P).length>2000)throw Error('Too many parameters');for(const [k,d]of Object.entries(P)){paramName(k);num(d.min,-1e4,1e4);num(d.max,-1e4,1e4);num(d.default,-1e4,1e4);}
 for(const l of p.layers??[]){safeId(l.id);if(!['override','additive'].includes(l.blend))throw Error('Invalid layer blend');num(l.weight,0,1);}
 for(const t of p.tracks){if(!PROPERTIES.includes(t.property))throw Error('Unsupported animation property');if(t.layer!==undefined)safeId(t.layer);if(t.property==='param')paramName(t.target);for(const k of t.keys)if(!isEasing(k.easing))throw Error('Unknown easing');}
 const keys=new Set<string>();for(const t of p.tracks){const k=`${t.target}\u0000${t.property}\u0000${t.layer??'base'}`;if(keys.has(k))throw Error('Duplicate track for target/property/layer');keys.add(k);}
 for(const x of [...(p.markers??[]),...(p.regions??[]),...(p.clips??[])])safeId(x.id);
 const ex=p.expression;if(ex){if(!Array.isArray(ex.features)||!Array.isArray(ex.drivers)||typeof ex.presets!=='object'||ex.features.length>64||ex.drivers.length>512)throw Error('Invalid expression rig');let points=0;for(const f of ex.features){safeId(f.id);if(!Array.isArray(f.paths)||!Array.isArray(f.pins)||!f.landmarks||!f.keys||!f.rest)throw Error('Invalid expression feature');f.paths.forEach(safeId);num(f.size,0,1e5);for(const pt of [...f.pins,...Object.values(f.landmarks)]){num(pt.x);num(pt.y);}for(const [param,key]of Object.entries(f.keys)){paramName(param);for(const [lm,d]of Object.entries(key)){if(!f.landmarks[lm])throw Error('Key references unknown landmark');num(d.dx,-1e4,1e4);num(d.dy,-1e4,1e4);}}for(const id of f.paths){if(typeof f.rest[id]!=='string')throw Error('Feature rest geometry missing');points+=f.rest[id].length/8;}}if(points>400000)throw Error('Expression rig too large');
  for(const d of ex.drivers){safeId(d.id);paramName(d.param);safeId(d.target);if(!Array.isArray(d.points)||d.points.length<2)throw Error('Invalid driver');}for(const [name,set]of Object.entries(ex.presets)){if(name.length>60)throw Error('Invalid preset');for(const [k,v]of Object.entries(set)){paramName(k);num(v,-1e4,1e4);}}}
 let modPoints=0;for(const mod of p.modifiers??[]){safeId(mod.id);if(!MODIFIER_KINDS.includes(mod.kind)||!Array.isArray(mod.targets)||typeof mod.rest!=='object')throw Error('Invalid modifier');mod.targets.forEach(safeId);for(const [k,v]of Object.entries(mod.params)){safeId(k);num(v,-1e5,1e5);}for(const id of mod.targets){if(typeof mod.rest[id]!=='string')throw Error('Modifier rest geometry missing');modPoints+=mod.rest[id].length/8;}if(mod.preset&&!FLUID_PRESETS[mod.preset])throw Error('Unknown preset');}if(modPoints>600000)throw Error('Modifier stack too large');if((p.modifiers??[]).length>64)throw Error('Too many modifiers');
 for(const s of p.secondary??[]){safeId(s.id);safeId(s.target);num(s.stiffness,0,10000);num(s.damping,0,1000);num(s.gain,-1000,1000);num(s.delay,0,10);num(s.limit,0,360);}
 if(p.stateMachine){const sm=p.stateMachine;if(!Array.isArray(sm.inputs)||!Array.isArray(sm.states)||!Array.isArray(sm.transitions)||!Array.isArray(sm.listeners)||sm.states.length>128)throw Error('Invalid state machine');sm.states.forEach(s=>safeId(s.id));}
 for(const c of p.components??[]){safeId(c.id);safeId(c.master);for(const [slot,ids]of Object.entries(c.slots)){safeId(slot);ids.forEach(safeId);}}
 for(const d of p.decisions??[])if(typeof d.summary!=='string'||d.summary.length>2000)throw Error('Invalid decision log');
 if(p.preservation&&!['strict','balanced','free'].includes(p.preservation))throw Error('Invalid preservation mode');
 for(const b of p.baselines??[]){safeId(b.id);if(!/^[a-f0-9]{64}$/.test(b.sha256))throw Error('Invalid baseline hash');}if(p.documentId!==undefined&&!/^[A-Za-z0-9][\w.:-]{0,127}$/.test(p.documentId))throw Error('Invalid documentId');
 void LEVELS;
}
export function cleanupDeleted(p:Project,deleted:Set<string>){
 if(p.semantic)for(const n of p.semantic.nodes)n.targets=n.targets.filter(t=>!deleted.has(t));
 if(p.expression){for(const f of p.expression.features){f.paths=f.paths.filter(id=>!deleted.has(id));for(const id of deleted)delete f.rest[id];}p.expression.features=p.expression.features.filter(f=>f.paths.length);p.expression.drivers=p.expression.drivers.filter(d=>!deleted.has(d.target));}
 if(p.modifiers){for(const mod of p.modifiers){mod.targets=mod.targets.filter(id=>!deleted.has(id));for(const id of deleted)delete mod.rest[id];}p.modifiers=p.modifiers.filter(x=>x.targets.length);}
 if(p.secondary)p.secondary=p.secondary.filter(s=>!deleted.has(s.target)&&!deleted.has(s.driver));
}
export type {Point};
