import type {VectorDocument} from './document.js';import {safeId} from './document.js';import type {Operation,Project,Emotion,Sprite,Property} from './model.js';
const finite=(n:unknown)=>{if(typeof n!=='number'||!Number.isFinite(n)||Math.abs(n)>1e6)throw Error('Invalid character numeric value');};
export function validateLibraries(p:Project){if(!Array.isArray(p.emotions)||!Array.isArray(p.sprites)||p.emotions.length>100||p.sprites.length>100)throw Error('Invalid character library');const unique=(items:{id:string}[])=>{const ids=new Set<string>();for(const e of items){safeId(e.id);if(ids.has(e.id))throw Error('Duplicate library ID');ids.add(e.id);}};unique(p.emotions);unique(p.sprites);
for(const e of p.emotions){if(typeof e.name!=='string'||e.name.length>200||!e.targets||Object.keys(e.targets).length<1||Object.keys(e.targets).length>100)throw Error('Invalid emotion');for(const [id,t]of Object.entries(e.targets)){safeId(id);if(t.pose)for(const [k,v]of Object.entries(t.pose)){if(!['x','y','rotation','scaleX','scaleY'].includes(k))throw Error('Emotion pose property is not animatable');finite(v);}if(t.attrs)for(const [k,v]of Object.entries(t.attrs)){if(!['d','fill','stroke','opacity'].includes(k)||typeof v!=='string'||v.length>100000)throw Error('Invalid emotion attribute');if(k==='opacity'){finite(Number(v));if(Number(v)<0||Number(v)>1)throw Error('Opacity out of range');}else if(k!=='d'&&!/^#[0-9a-f]{6}$/i.test(v))throw Error('Emotion colors require #RRGGBB');}}}
for(const s of p.sprites){if(typeof s.name!=='string'||s.name.length>200||!s.variants||Object.keys(s.variants).length<2||Object.keys(s.variants).length>100||!Object.hasOwn(s.variants,s.initial))throw Error('Invalid sprite variants');const targets=new Set<string>();for(const [state,ids]of Object.entries(s.variants)){safeId(state);if(!Array.isArray(ids)||ids.length<1||ids.length>100)throw Error('Invalid sprite frame');for(const id of ids){safeId(id);if(targets.has(id))throw Error('Sprite variants must use disjoint targets');targets.add(id);}}}}
export function characterOperation(m:VectorDocument,op:Operation,touched:Set<string>){const emit=(next:Operation)=>m.operation(next,touched);
if(op.type==='emotion.define'||op.type==='emotion.update'){const emotion=structuredClone(op.emotion);const index=m.project.emotions.findIndex(e=>e.id===emotion.id);if(op.type==='emotion.define'&&index>=0)throw Error('Emotion exists; choose a new ID');if(op.type==='emotion.update'&&index<0)throw Error('Emotion not found');validateLibraries({...m.project,emotions:op.type==='emotion.update'?m.project.emotions.map(e=>e.id===emotion.id?emotion:e):[...m.project.emotions,emotion]});const draft=m.capture([{type:'emotion.apply',id:emotion.id}]);try{for(const [id,target]of Object.entries(emotion.targets)){m.editable(id);if(target.attrs?.d)m.guardTopology(id,target.attrs.d);}}catch(error){m.restore(draft);throw error;}if(op.type==='emotion.update')m.project.emotions[index]=emotion;else m.project.emotions.push(emotion);return;}
if(op.type==='emotion.apply'||op.type==='emotion.keyframe'){const e=m.project.emotions.find(e=>e.id===op.id);if(!e)throw Error('Emotion not found');for(const [target,state]of Object.entries(e.targets)){if(op.type==='emotion.apply'){if(m.project.tracks.some(t=>t.target===target&&(Object.hasOwn(state.pose??{},t.property)||Object.hasOwn(state.attrs??{},t.property))))throw Error('Emotion target is animated; use emotion.keyframe');if(state.pose)emit({type:'pose',id:target,pose:state.pose});if(state.attrs)emit({type:'attributes',id:target,attrs:state.attrs as Record<string,string>});}else{for(const [property,value]of Object.entries(state.pose??{}))emit({type:'keyframe',target,property:property as Property,time:op.time,value:value!,easing:op.easing});for(const [property,value]of Object.entries(state.attrs??{}))emit({type:'keyframe',target,property:property as Property,time:op.time,value:property==='opacity'?Number(value):value!,easing:op.easing});}}return;}
if(op.type==='sprite.define'){const sprite=structuredClone(op.sprite);if(m.project.sprites.some(s=>s.id===sprite.id))throw Error('Sprite exists');validateLibraries({...m.project,sprites:[...m.project.sprites,sprite]});const targets=Object.values(sprite.variants).flat().map(id=>m.editable(id));for(const a of targets)for(const b of targets)if(a!==b){let p:Node|null=b.parentNode;while(p){if(p===a)throw Error('Sprite variants cannot contain one another');p=p.parentNode;}}for(const id of Object.values(sprite.variants).flat())if(m.project.tracks.some(t=>t.target===id&&t.property==='opacity'))throw Error('Sprite opacity track already exists');m.project.sprites.push(sprite);for(const [state,ids]of Object.entries(sprite.variants))for(const id of ids)emit({type:'attributes',id,attrs:{opacity:state===sprite.initial?'1':'0'}});return;}
if(op.type==='sprite.state'||op.type==='sprite.keyframe'){const sprite=m.project.sprites.find(s=>s.id===op.id);if(!sprite||!Object.hasOwn(sprite.variants,op.state))throw Error('Sprite state not found');for(const [state,ids]of Object.entries(sprite.variants))for(const id of ids){const value=state===op.state?1:0;if(op.type==='sprite.state'){if(m.project.tracks.some(t=>t.target===id&&t.property==='opacity'))throw Error('Sprite has animation; use sprite.keyframe');emit({type:'attributes',id,attrs:{opacity:String(value)}});}else{const track=m.project.tracks.find(t=>t.target===id&&t.property==='opacity');if(track&&track.keys.some(k=>k.easing!=='step'))throw Error('Sprite track conflicts with continuous opacity');if(!track&&op.time>0)emit({type:'keyframe',target:id,property:'opacity',time:0,value:state===sprite.initial?1:0,easing:'step'});emit({type:'keyframe',target:id,property:'opacity',time:op.time,value,easing:'step'});}}return;}
throw Error('Unknown character operation');}
