import type {VectorDocument} from './document.js';
import {elements} from '../converter/svg.js';
// Export compatibility matrix: which scene features each target can represent. Unsupported features come with
// explicit options; MAI never degrades an animation silently.
export function sceneFeatures(m:VectorDocument){const p=m.project,all=elements(m.doc);const has=(tag:string)=>all.some(e=>e.localName===tag);
 const f:Record<string,boolean>={'pose-animation':p.tracks.some(t=>['x','y','rotation','scaleX','scaleY'].includes(t.property))||!!(p.secondary??[]).length,'path-morph':p.tracks.some(t=>t.property==='d')||!!p.skins.length||!!p.meshes.length,'expression-warp':!!(p.expression?.features??[]).length,'parameter-animation':p.tracks.some(t=>t.property==='param'),'flow-geometry':(p.modifiers??[]).some(x=>x.enabled&&x.technique!=='filter'),'flow-filter':(p.modifiers??[]).some(x=>x.enabled&&x.technique==='filter'),'color-animation':p.tracks.some(t=>['fill','stroke'].includes(t.property)),'opacity-animation':p.tracks.some(t=>t.property==='opacity'),filters:has('filter'),masks:has('mask'),clipPaths:has('clipPath'),gradients:has('linearGradient')||has('radialGradient'),'css-variables':all.some(e=>/var\(--mai-/.test(e.getAttribute('style')??'')),'state-machine':!!p.stateMachine?.states.length,'native-smil':all.some(e=>['animate','animateTransform','set'].includes(e.localName)&&!e.getAttribute('data-mai-generated')),text:has('text')};
 return Object.fromEntries(Object.entries(f).filter(([,v])=>v).map(([k])=>[k,true]));}
type Target={id:string;label:string;status:'available'|'partial'|'planned';supports:string[];options:Record<string,string>};
const ALL=['pose-animation','path-morph','expression-warp','parameter-animation','flow-geometry','flow-filter','color-animation','opacity-animation','filters','masks','clipPaths','gradients','css-variables','state-machine','native-smil','text'];
export const TARGETS:Target[]=[
 {id:'editable',label:'MAI SVG editable',status:'available',supports:ALL,options:{}},
 {id:'standalone',label:'SVG animado (SMIL, sin scripts)',status:'available',supports:ALL.filter(x=>x!=='state-machine'),options:{'state-machine':'A) exportar el estado inicial como loop, B) runtime interactivo (planned), C) sprites por estado'}},
 {id:'sprite-sheet',label:'Atlas SVG/PNG por fotogramas',status:'available',supports:ALL.filter(x=>x!=='state-machine'),options:{'state-machine':'Un atlas por estado: exportar cada estado como clip.'}},
 {id:'png-sequence',label:'Secuencia PNG / GIF',status:'available',supports:ALL.filter(x=>x!=='state-machine'),options:{'state-machine':'Renderiza cada estado por separado.'}},
 {id:'svg-static',label:'SVG estático (un fotograma)',status:'available',supports:ALL.filter(x=>!x.endsWith('animation')&&!['path-morph','flow-geometry','flow-filter','state-machine','native-smil','parameter-animation'].includes(x)),options:{'pose-animation':'Congela un tiempo concreto.','path-morph':'Congela un tiempo concreto.'}},
 {id:'css',label:'CSS animations',status:'planned',supports:['pose-animation','opacity-animation','color-animation','gradients','masks','clipPaths','filters'],options:{'path-morph':'A) standalone SMIL, B) hornear como sprites, C) CSS d:path() solo Chromium','expression-warp':'Igual que path-morph','flow-geometry':'Cambiar técnica a filter o hornear'}},
 {id:'lottie',label:'Lottie / dotLottie',status:'planned',supports:['pose-animation','opacity-animation','color-animation','path-morph','gradients','masks','state-machine'],options:{filters:'Lottie no representa filtros SVG: A) hornear como fotogramas, B) quitar el efecto, C) usar standalone SVG','flow-filter':'Cambiar técnica a geometry (morph de paths)','css-variables':'Aplanar overrides de componentes antes de exportar'}},
 {id:'react',label:'Componente React (SVG inline)',status:'partial',supports:ALL.filter(x=>x!=='state-machine'),options:{'state-machine':'Pendiente: runtime interactivo.'}},
];
export function exportCapabilities(m:VectorDocument,only?:string){const features=sceneFeatures(m),used=Object.keys(features);
 return {features:used,targets:TARGETS.filter(t=>!only||t.id===only).map(t=>{const unsupported=used.filter(f=>!t.supports.includes(f));return {id:t.id,label:t.label,status:t.status,fidelity:unsupported.length?'lossy':'faithful',unsupported:unsupported.map(f=>({feature:f,options:t.options[f]??'No representable: exportar standalone SVG o fotogramas.'}))};})};}
