import {parse,generate,walk,type CssNode,type WalkContext} from 'css-tree';
import {elements,prefixIds} from '../converter/svg.js';
// Namespace selectors, paint references and animation names structurally, never by CSS regex.
export function namespaceComponent(root:Element,id:string){
 const all=[root,...elements(root)],ids=new Map(all.filter(e=>e.hasAttribute('id')).map(e=>[e.getAttribute('id')!,id+'-'+e.getAttribute('id')!]));if(root.hasAttribute('id'))ids.set(root.getAttribute('id')!,id);
 const styles=all.filter(e=>e.localName==='style'),trees=styles.map(e=>parse(e.textContent??'')),names=new Map<string,string>();
 for(const tree of trees)walk(tree,{visit:'Atrule',enter(node){if(!['keyframes','-webkit-keyframes','media','supports'].includes(node.name))throw Error(`Unsupported composition CSS @${node.name}; prepare inline styles`);if(node.name.endsWith('keyframes')){if(!node.prelude)throw Error('Missing keyframe name');walk(node.prelude,n=>{if(n.type==='Identifier'||n.type==='String'){const name=n.type==='Identifier'?n.name:n.value;names.set(name,id+'-'+name);}});}}});
 const rewrite=(tree:CssNode)=>walk(tree,{enter(this:WalkContext,node:CssNode){if(node.type==='Raw')throw Error('Unsupported composition CSS syntax; prepare inline styles');if(node.type==='IdSelector')node.name=ids.get(node.name)??node.name;if(node.type==='Url'&&node.value.startsWith('#'))node.value='#'+(ids.get(node.value.slice(1))??node.value.slice(1));if(node.type==='PseudoClassSelector'&&node.name==='root')Object.assign(node,{type:'IdSelector',name:id});if((node.type==='Identifier'||node.type==='String')&&(this.atrule?.name.endsWith('keyframes')&&this.atrule.prelude===this.atrulePrelude||this.declaration&&/^(?:-webkit-)?animation(?:-name)?$/.test(this.declaration.property))){if(node.type==='Identifier')node.name=names.get(node.name)??node.name;else node.value=names.get(node.value)??node.value;}},leave(this:WalkContext,node:CssNode){if(node.type==='Rule'&&node.prelude&&!(this.atrule?.name.endsWith('keyframes'))){const selector=generate(node.prelude);node.prelude=parse(`:where(#${id}) :is(${selector}),:where(#${id}):is(${selector})`,{context:'selectorList'}) as typeof node.prelude;}}});
 for(const tree of trees)rewrite(tree);
 for(const e of all){const style=e.getAttribute('style');if(style){const ast=parse(style,{context:'declarationList'});rewrite(ast);e.setAttribute('style',generate(ast));}}
 styles.forEach(e=>e.parentNode!.removeChild(e));prefixIds(root,id+'-');root.setAttribute('id',id);styles.forEach((e,i)=>{e.textContent=generate(trees[i]);root.appendChild(e);});
}
