import type {VectorDocument} from './document.js';
import {frameState} from './animation.js';
import {segments} from './geometry.js';
import {featureDisplacements,PRESERVATION} from './expression.js';
import type {Finding} from './detectors.js';
// Animation craft, deterministic half: pops, teleports, jerk, loop seams, squash, stiff secondary motion, identity
// drift. The visual half (appeal, acting, readability) is the agent's judgement over rendered frames and must be
// reported separately — a metric is never artistic approval.
export function critique(model:VectorDocument,options:{samples?:number}={}){
 const p=model.project,n=Math.max(8,Math.min(options.samples??Math.round(p.duration*Math.min(p.fps,30)),600)),dt=p.duration/n,f:Finding[]=[];const add=(code:string,severity:Finding['severity'],message:string,repair:string,target?:string)=>f.push({code,severity,message,repair,...(target?{target}:{})});
 const vb=(model.doc.documentElement.getAttribute('viewBox')??'0 0 700 700').split(/[\s,]+/).map(Number),diag=Math.hypot(vb[2],vb[3]);
 const frames=Array.from({length:n+1},(_,i)=>frameState(p,i*dt));
 const poseTargets=[...new Set(p.tracks.filter(t=>['x','y','rotation','scaleX','scaleY'].includes(t.property)).map(t=>t.target).concat((p.secondary??[]).map(s=>s.target)))];
 const scores={smoothness:4,loop:4,identity:4,timing:4,secondary:4};const dock=(k:keyof typeof scores,v:number)=>{scores[k]=Math.max(0,scores[k]-v);};
 for(const id of poseTargets){const series=frames.map(fr=>fr.poses[id]);if(series.some(s=>!s))continue;
  const pos=series.map(s=>({x:s.x,y:s.y,r:s.rotation}));const vel=pos.slice(1).map((q,i)=>Math.hypot(q.x-pos[i].x,q.y-pos[i].y)+Math.abs(q.r-pos[i].r)*diag/720);const median=[...vel].sort((a,b)=>a-b)[Math.floor(vel.length/2)]||0;
  const pops=vel.map((v,i)=>({v,i})).filter(({v})=>v>diag*.04&&v>8*Math.max(median,1e-3));if(pops.length){add('MAI_POP','warning',`${id}: salto de ${pops[0].v.toFixed(1)} px en un fotograma (t≈${(pops[0].i*dt).toFixed(2)} s).`,'Suaviza con keyframes intermedios o easing; si es intencional (corte), usa step.',id);dock('smoothness',1);}
  const acc=vel.slice(1).map((v,i)=>v-vel[i]),mean=acc.reduce((a,b)=>a+Math.abs(b),0)/Math.max(1,acc.length),spikes=acc.filter(a=>Math.abs(a)>Math.max(6*mean,diag*.01)).length;if(spikes>2){add('MAI_JERK','info',`${id}: ${spikes} cambios bruscos de velocidad.`,'Usa ease-in-out u overshoot en los keyframes con aceleración brusca.',id);dock('smoothness',.5);}
  if(p.loop){const a=series[0],b=series.at(-1)!;const gap=Math.hypot(a.x-b.x,a.y-b.y)+Math.abs(a.rotation-b.rotation)*diag/720+Math.abs(a.scaleX-b.scaleX)*100+Math.abs(a.scaleY-b.scaleY)*100;if(gap>1){add('MAI_LOOP_POP','warning',`${id}: el loop salta ${gap.toFixed(1)} px al reiniciar.`,'Iguala el primer y último keyframe.',id);dock('loop',1);}
   const v0=vel[0],v1=vel.at(-1)!;if(Math.abs(v0-v1)>Math.max(2,(v0+v1)))add('MAI_LOOP_VELOCITY','info',`${id}: la velocidad al final del loop no coincide con el inicio.`,'Usa la misma curva de easing en los extremos.',id);}
  const squash=series.map(s=>s.scaleX/Math.max(1e-6,s.scaleY));if(squash.some(r=>r<.6||r>1.65)){add('MAI_SQUASH','warning',`${id}: squash/stretch supera 1.65× y puede romper el volumen.`,'Limita la escala o compensa ambos ejes (volumen constante).',id);dock('identity',.5);}
  const keyTimes=p.tracks.filter(t=>t.target===id).flatMap(t=>t.keys.map(k=>k.time)).sort((a,b)=>a-b);const sub=keyTimes.slice(1).filter((t,i)=>t-keyTimes[i]>0&&t-keyTimes[i]<1/p.fps).length;if(sub){add('MAI_SUBFRAME_KEYS','info',`${id}: ${sub} keyframes separados por menos de un fotograma.`,'Alinea a la rejilla de fps o fusiónalos.',id);dock('timing',.5);}}
 for(const s of p.secondary??[]){const offsets=frames.map(fr=>fr.poses[s.target]?.[s.property]??0),base=p.poses[s.target]?.[s.property]??0,range=Math.max(...offsets)-Math.min(...offsets);if(range<.5&&s.kind!=='look-at'){add('MAI_STIFF_SECONDARY','info',`${s.id}: movimiento secundario casi nulo (${range.toFixed(2)}).`,'Aumenta gain o reduce damping; verifica que el driver se mueva.',s.target);dock('secondary',1);}void base;}
 // Identity: expression landmarks stay within the preservation budget; protected geometry never changes per frame.
 const mode=p.preservation??'balanced';for(const x of p.expression?.features??[]){const budget=PRESERVATION[mode].maxDisplacement*x.size;let worst=0,at=0;frames.forEach((fr,i)=>{const d=featureDisplacements(x,fr.params,mode);for(const v of Object.values(d)){const m=Math.hypot(v.dx,v.dy);if(m>worst){worst=m;at=i*dt;}}});if(worst>budget*1.001){add('MAI_IDENTITY_DRIFT','error',`${x.id}: landmarks se desplazan ${worst.toFixed(2)} px (límite ${budget.toFixed(2)}) en t=${at.toFixed(2)}.`,'Reduce la expresión o cambia el modo de preservación con el usuario.',x.id);dock('identity',2);}}
 const protectedIds=new Set([...(p.identity?.ids??[]),...(p.semantic?.nodes??[]).filter(n=>n.protection?.some(l=>l==='locked'||l==='protected')).flatMap(n=>n.targets)]);
 for(const id of protectedIds){const changed=frames.some(fr=>fr.attrs[id]?.d||fr.attrs[id]?.fill);if(changed){add('MAI_IDENTITY_DRIFT','error',`${id} está protegido pero su geometría/color cambia durante la animación.`,'Elimina la pista o libera la protección explícitamente.',id);dock('identity',2);}}
 for(const n of (p.semantic?.nodes??[]).filter(n=>n.protection?.includes('silhouette-preserved'))){const ids=n.targets.filter(t=>model.index.get(t)?.localName==='path');if(!ids.length)continue;const area=(fr:ReturnType<typeof frameState>)=>ids.reduce((s,id)=>{const d=fr.attrs[id]?.d??model.index.get(id)!.getAttribute('d')!;const pts=segments(d).flatMap(q=>q.points);const xs=pts.map(q=>q.x),ys=pts.map(q=>q.y);return s+(Math.max(...xs)-Math.min(...xs))*(Math.max(...ys)-Math.min(...ys));},0);const a0=area(frames[0]),worst=Math.max(...frames.map(fr=>Math.abs(area(fr)-a0)/Math.max(1,a0)));if(worst>.1){add('MAI_SILHOUETTE_BBOX','warning',`${n.label}: el área de las cajas envolventes de sus trazos cambia ${(worst*100).toFixed(0)} % (aproximación geométrica, no IoU).`,'Mide la silueta real con identity.check (IoU de máscara renderizada) y reduce la deformación o confirma con el usuario.',n.id);dock('identity',1);}}
 return {schemaVersion:1,revision:p.revision,samples:n+1,deterministic:{findings:f,scores},visual:{status:'not evaluated',rubric:['¿Se lee la emoción a tamaño real y a 50 %?','¿Las facciones siguen siendo de este personaje en la pose extrema?','¿El timing tiene anticipación y asentamiento, o se siente mecánico?','¿El movimiento secundario sigue al principal con retraso creíble?','¿El fluido conserva su silueta original y fluye desde su fuente?','¿El loop es invisible?'],instruction:'Renderiza tiempos clave (mai preview --times …), míralos y registra tu juicio visual por separado de estas métricas.'}};
}
