import {fluidOperations}from './fluid.js';
import {guardIdentity} from './identity-guard.js';
import {characterOperation,validateLibraries} from './character.js';
import {namespaceComponent} from './composition-css.js';
import {simplifyPath,booleanPaths} from './geometry-paper.js';
import {randomUUID} from 'node:crypto';
import {assertSvg,parseSvg,serialize,elements,SVG_NS,prefixIds} from '../converter/svg.js';
import {newProject,defaultPose,type Project,type Operation,type Attributes,type Patch,type Pose} from './model.js';
import {pathData,segments,topology,movePoint,addPoint,removePoint,splitPath,joinPaths,transformPath} from './geometry.js';
import {frameState,poseTransform,boneMatrices,autoWeights,solveIK} from './animation.js';
const shapeTags=['svg','g','path','rect','circle','ellipse','polygon','polyline','line','text'];
const reserved=new Set(['__proto__','constructor','prototype','mai-project']);
export const safeId=(id:string)=>{if(!/^[A-Za-z_][\w.-]{0,100}$/.test(id)||reserved.has(id))throw Error('Invalid or reserved object ID');return id;};
const numeric=(n:number,min=-1e6,max=1e6)=>{if(typeof n!=='number'||!Number.isFinite(n)||n<min||n>max)throw Error('Invalid numeric value');return n;};
export type Snapshot={kind:'svg';svg:string}|{kind:'attributes';project:Project;attrs:Record<string,Attributes>};
const structural=new Set(['fluid.add','identity.protect','identity.release','create','delete','group','ungroup','order','path.split','path.join','path.boolean','gradient','part.prepare','scene.insert','canvas','emotion.define','emotion.update','emotion.apply','emotion.keyframe','sprite.define','sprite.state','sprite.keyframe']);
export class VectorDocument {
 doc:Document;project:Project;index=new Map<string,Element>();count=0;
 constructor(source:string,name='Sin título'){
  assertSvg(source);this.doc=parseSvg(source);const metadata=elements(this.doc).find(e=>e.localName==='metadata'&&e.getAttribute('id')==='mai-project');
  this.project=metadata?JSON.parse(metadata.textContent||'null'):newProject(name);if(!this.project||this.project.version!==1)throw Error('Unsupported MAI metadata version');
  this.project.emotions??=[];this.project.sprites??=[];this.project.baseTransforms??={};this.project.baseAttributes??={};this.checkProject();
  // Compiled SVG retains authoring data; remove only MAI-owned export wrappers/animations.
  for(const e of elements(this.doc).filter(e=>metadata&&e.getAttribute('data-mai-generated')).reverse()){
   if(e.localName==='g'){while(e.firstChild)e.parentNode!.insertBefore(e.firstChild,e);e.parentNode!.removeChild(e);}else e.parentNode!.removeChild(e);
  }
  if(!metadata)for(const e of elements(this.doc))e.removeAttribute('data-mai-generated');
  metadata?.parentNode?.removeChild(metadata);
  for(const canvas of elements(this.doc).filter(e=>e.localName==='svg'&&/mai-alpha/.test(e.getAttribute('mask')??''))){const artwork=this.doc.createElementNS(SVG_NS,'g');artwork.setAttribute('id',this.unique('artwork'));artwork.setAttribute('data-mai-name','Personaje · alfa preservado');artwork.setAttribute('data-mai-alpha-group','true');artwork.setAttribute('mask',canvas.getAttribute('mask')!);canvas.removeAttribute('mask');const shapes=Array.from(canvas.childNodes).filter(n=>n.nodeType===1&&shapeTags.includes((n as Element).localName));if(shapes.length){canvas.insertBefore(artwork,shapes[0]);for(const shape of shapes)artwork.appendChild(shape);}}
  for(const g of elements(this.doc).filter(e=>e.localName==='g'&&/mai-alpha/.test(e.getAttribute('mask')??''))){g.setAttribute('data-mai-alpha-group','true');if(!g.hasAttribute('data-mai-name'))g.setAttribute('data-mai-name','Personaje · alfa preservado');}
  this.reindex();
  for(const [id,attrs]of Object.entries(this.project.baseAttributes)){const e=this.index.get(id);if(e)for(const [name,value]of Object.entries(attrs)){if(name==='id'&&value!==id)throw Error('Metadata cannot change object identity');e.setAttribute(name,value);}}
  for(const [id,p]of Object.entries(this.project.poses))if(this.index.has(id))this.applyPose(id,p);
  assertSvg(serialize(this.doc));
 }
 reindex(){this.index.clear();for(const e of elements(this.doc)){let id=e.getAttribute('id');if(!id&&shapeTags.includes(e.localName)&&!this.inDefs(e)){id=this.unique('mai-object');e.setAttribute('id',id);}if(id){safeIdExceptMetadata(id);if(this.index.has(id))throw Error(`Duplicate ID ${id}`);this.index.set(id,e);}}this.count=this.index.size;}
 unique(prefix='shape'){let id:string;do{id=`${prefix}-${randomUUID().slice(0,8)}`;}while(this.index.has(id));return id;}
 inDefs(e:Element){let p:Node|null=e;while(p&&p.nodeType===1){if(['defs','mask','clipPath','filter','metadata'].includes((p as Element).localName))return true;p=p.parentNode;}return false;}
 element(id:string){safeId(id);const e=this.index.get(id);if(!e||this.inDefs(e))throw Error('Editable object not found');return e;}
 editable(id:string){const e=this.element(id);if(e===this.doc.documentElement)throw Error('Canvas cannot be edited as a shape');let p:Node|null=e;while(p?.nodeType===1){if((p as Element).getAttribute('data-mai-locked')==='true')throw Error('Object or parent is locked');p=p.parentNode;}return e;}
 attrs(e:Element):Attributes{return Object.fromEntries(Array.from(e.attributes).map(a=>[a.name,a.value]));}
 list(filter='',offset=0,limit=80){const all=[...this.index.values()].filter(e=>e!==this.doc.documentElement&&!this.inDefs(e)&&shapeTags.includes(e.localName));const filtered=all.filter(e=>`${e.getAttribute('id')} ${e.getAttribute('data-mai-name')??''} ${e.localName}`.toLowerCase().includes(filter.toLowerCase()));return {total:filtered.length,items:filtered.slice(offset,offset+Math.min(200,limit)).map(e=>this.info(e))};}
 info(e:Element){let depth=0,p=e.parentNode;while(p?.nodeType===1){depth++;p=p.parentNode;}return {id:e.getAttribute('id')!,tag:e.localName,name:e.getAttribute('data-mai-name')||e.getAttribute('id'),parent:(e.parentNode as Element)?.getAttribute?.('id'),depth,locked:e.getAttribute('data-mai-locked')==='true',attrs:this.attrs(e),pose:this.project.poses[e.getAttribute('id')!]??defaultPose()};}
 remember(id:string){const e=this.element(id);this.project.baseAttributes[id]??=this.attrs(e);this.project.baseTransforms[id]??=e.getAttribute('transform')||'';}
 applyPose(id:string,p:Pose){const e=this.element(id);e.setAttribute('transform',`${poseTransform(p)} ${this.project.baseTransforms[id]??''}`.trim());}
 guardTopology(id:string,next:string){const e=this.editable(id),d=e.getAttribute('d')||'';if(topology(d)!==topology(next)&&(this.project.tracks.some(t=>t.target===id&&t.property==='d')||this.project.skins.some(s=>s.target===id)))throw Error('Remove path keyframes or unbind rig before changing topology');}
 setPath(id:string,d:string){const e=this.editable(id);if(e.localName!=='path')throw Error('Select a path');segments(d);this.guardTopology(id,d);e.setAttribute('d',d);if(this.project.baseAttributes[id])this.project.baseAttributes[id].d=d;const skin=this.project.skins.find(s=>s.target===id);if(skin)skin.rest=segments(d);}
 normalizeForRig(id:string){const e=this.editable(id);if(e.localName!=='path')throw Error('Rig binding requires paths');let parent=e.parentNode;while(parent?.nodeType===1){const p=parent as Element;if(p!==this.doc.documentElement&&(p.localName==='svg'||p.hasAttribute('transform')||(p.hasAttribute('mask')&&p.getAttribute('mask')!=='none')))throw Error('Rig requires untransformed document coordinates without an ancestor alpha mask. Prepare the part, then rebuild opacity/gradients or explicitly remove its mask before deformation.');parent=p.parentNode;}
  const base=this.project.baseTransforms[id]??e.getAttribute('transform')??'';for(const t of this.project.tracks.filter(t=>t.target===id&&t.property==='d'))for(const key of t.keys)key.value=base?transformPath(String(key.value),base):pathData(segments(String(key.value)));
  const d=base?transformPath(e.getAttribute('d')!,base):pathData(segments(e.getAttribute('d')!));e.setAttribute('d',d);e.removeAttribute('transform');this.project.baseTransforms[id]='';this.project.baseAttributes[id]=this.attrs(e);if(this.project.poses[id])this.applyPose(id,this.project.poses[id]);return segments(d);
 }
 capture(ops:Operation[]):Snapshot{
  if(ops.some(op=>structural.has(op.type)))return {kind:'svg',svg:this.toSVG()};
  const ids=new Set<string>();for(const op of ops){if('id'in op)ids.add(op.id!);if('ids'in op)op.ids.forEach(id=>ids.add(id));if('target'in op&&typeof op.target==='string')ids.add(op.target);}
  return {kind:'attributes',project:structuredClone(this.project),attrs:Object.fromEntries([...ids].filter(id=>this.index.has(id)).map(id=>[id,this.attrs(this.index.get(id)!)]))};
 }
 restore(snapshot:Snapshot){
  if(snapshot.kind==='svg'){const restored=new VectorDocument(snapshot.svg);this.doc=restored.doc;this.project=restored.project;this.index=restored.index;this.count=restored.count;return;}
  this.project=structuredClone(snapshot.project);for(const [id,attrs]of Object.entries(snapshot.attrs)){const e=this.index.get(id);if(!e)throw Error('History target missing');for(const a of Array.from(e.attributes))e.removeAttribute(a.name);for(const [name,value]of Object.entries(attrs))e.setAttribute(name,value);}
 }
 apply(ops:Operation[]){if(!Array.isArray(ops)||ops.length<1||ops.length>500)throw Error('A transaction needs 1–500 operations');const before=this.capture(ops);const touched=new Set<string>();let reload=false;
  try{for(const op of ops){const result=this.operation(op,touched);reload ||= result;}this.checkProject();if(reload){this.reindex();assertSvg(this.toSVG());}}
  catch(error){this.restore(before);throw error;}
  const patches:Patch[]=[...touched].filter(id=>this.index.has(id)).map(id=>({id,attrs:this.attrs(this.index.get(id)!)}));return {reload,patches};
 }
 operation(op:Operation,touched:Set<string>):boolean{
  guardIdentity(this,op);
  if(op.type.startsWith('emotion.')||op.type.startsWith('sprite.')){characterOperation(this,op,touched);return false;}
  const touch=(id:string)=>{touched.add(id);return this.editable(id);};
  switch(op.type){
   case 'identity.protect':{if(!Array.isArray(op.ids)||!op.ids.length||op.ids.length>500)throw Error('Select 1–500 identity objects');for(const id of op.ids)this.editable(id);this.project.identity={ids:[...new Set([...(this.project.identity?.ids??[]),...op.ids])]};return false;}
   case 'identity.release':{for(const id of op.ids)safeId(id);this.project.identity={ids:(this.project.identity?.ids??[]).filter(id=>!op.ids.includes(id))};return false;}
   case 'canvas':{const width=numeric(op.width,1,4096),height=numeric(op.height,1,4096);this.doc.documentElement.setAttribute('viewBox',`0 0 ${width} ${height}`);this.doc.documentElement.setAttribute('width',String(width));this.doc.documentElement.setAttribute('height',String(height));return true;}
   case 'scene.insert':{assertSvg(op.svg);const source=parseSvg(op.svg);if(elements(source).some(e=>e.localName==='metadata'&&e.getAttribute('id')==='mai-project'))throw Error('Insert requires standalone SVG; export authored projects first.');const id=op.id?safeId(op.id):this.unique('component');if(this.index.has(id))throw Error('Component ID exists');const node=source.documentElement;namespaceComponent(node,id);for(const e of [node,...elements(node)])e.removeAttribute('data-mai-generated');node.setAttribute('id',id);node.setAttribute('data-mai-name',String(op.name).slice(0,200));node.setAttribute('x',String(numeric(op.x??0)));node.setAttribute('y',String(numeric(op.y??0)));const vb=(node.getAttribute('viewBox')??'0 0 700 700').split(/[ ,]+/).map(Number);node.setAttribute('width',String(numeric(op.width??vb[2],1,4096)));node.setAttribute('height',String(numeric(op.height??vb[3],1,4096)));this.doc.documentElement.appendChild(this.doc.importNode(node,true));return true;}
   case 'track.edit':{const track=this.project.tracks.find(t=>t.target===op.target&&t.property===op.property);if(!track)throw Error('Track not found');if(!op.property.startsWith('bone')&&!op.property.startsWith('mesh'))this.editable(op.target);if(op.action==='delete'){this.project.tracks=this.project.tracks.filter(t=>t!==track);return false;}if(op.action==='reverse'&&track.keys.some(k=>k.easing==='step'))throw Error('Reverse discrete tracks explicitly with new keyframes');const start=track.keys[0].time,end=track.keys.at(-1)!.time;for(const key of track.keys){if(op.action==='shift')key.time+=numeric(op.amount!,-300,300);else if(op.action==='stretch')key.time=start+(key.time-start)*numeric(op.amount!,.01,100);else if(op.action==='reverse')key.time=start+end-key.time;else throw Error('Unknown track action');}track.keys.sort((a,b)=>a.time-b.time);return false;}
   case 'track.copy':{const track=this.project.tracks.find(t=>t.target===op.target&&t.property===op.property);if(!track)throw Error('Track not found');if(this.project.tracks.some(t=>t.target===op.to&&t.property===op.property))throw Error('Destination track exists; delete it explicitly first');for(const key of structuredClone(track.keys))this.operation({type:'keyframe',target:op.to,property:op.property,time:key.time+numeric(op.offset??0,-300,300),value:key.value,easing:key.easing},touched);return false;}
   case 'motion.preset':{this.editable(op.id);const p=this.project.poses[op.id]??defaultPose(),duration=this.project.duration,amplitude=numeric(op.amplitude??(op.kind==='spin'?360:op.kind==='pulse'?.08:op.kind==='fade'?1:12),0,1000);const property=op.kind==='float'?'y':op.kind==='spin'?'rotation':op.kind==='pulse'?'scaleX':op.kind==='fade'?'opacity':null;if(!property)throw Error('Unknown motion preset');const properties=op.kind==='pulse'?['scaleX','scaleY']as const:[property];for(const prop of properties){if(this.project.tracks.some(t=>t.target===op.id&&t.property===prop))throw Error('Preset would overwrite a track; delete it explicitly');const base=prop==='opacity'?Number(this.element(op.id).getAttribute('opacity')??1):p[prop as keyof Pose];const values=op.kind==='spin'?[base,base+amplitude]:op.kind==='fade'?[0,Math.min(1,amplitude),0]:[base,base+(op.kind==='float'?-amplitude:amplitude),base];values.forEach((value,i)=>this.operation({type:'keyframe',target:op.id,property:prop as import("./model.js").Property,time:duration*i/(values.length-1),value,easing:op.kind==='spin'?'linear':'ease-in-out'},touched));}return false;}
   case 'fluid.add':{for(const generated of fluidOperations(op.config,this.project.duration))this.operation(generated,touched);return true;}
   case 'attributes':{const e=touch(op.id);for(const [name,value]of Object.entries(op.attrs)){if(!['d','fill','stroke','stroke-width','stroke-opacity','fill-opacity','stroke-dasharray','stroke-linecap','stroke-linejoin','fill-rule','opacity','x','y','cx','cy','r','rx','ry','width','height','x1','x2','y1','y2','points','transform','filter','mask','clip-path','display','data-mai-name'].includes(name)||typeof value!=='string')throw Error('Forbidden attribute');if(value.length>1024*1024)throw Error('Attribute too large');if(/data:|https?:|javascript:|expression\s*\(/i.test(value))throw Error('External or unsafe attribute');for(const m of value.matchAll(/url\(([^)]+)\)/g)){const ref=m[1].trim().replace(/^['"]|['"]$/g,'');if(!ref.startsWith('#')||!this.index.has(ref.slice(1)))throw Error('Invalid local reference');}if(name==='transform')transformPath('M0 0 L1 1',value);if(name==='d'){this.setPath(op.id,value);continue;}if(name==='transform'&&this.project.poses[op.id])throw Error('Use pose for an animated transform');e.setAttribute(name,value);if(this.project.baseAttributes[op.id])this.project.baseAttributes[op.id][name]=value;}return false;}
   case 'gradient':{const e=touch(op.id),defs=elements(this.doc).find(e=>e.localName==='defs')??this.doc.createElementNS(SVG_NS,'defs');if(!defs.parentNode)this.doc.documentElement.insertBefore(defs,this.doc.documentElement.firstChild);const id=this.unique('gradient'),g=this.doc.createElementNS(SVG_NS,op.kind==='radial'?'radialGradient':'linearGradient');g.setAttribute('id',id);if(op.axis==='vertical'){g.setAttribute('x1','0');g.setAttribute('x2','0');g.setAttribute('y1','0');g.setAttribute('y2','1');}for(const [offset,color]of [['0%',op.start],['100%',op.end]]){if(!/^#[0-9a-f]{6}$/i.test(color))throw Error('Gradient color must be #RRGGBB');const stop=this.doc.createElementNS(SVG_NS,'stop');stop.setAttribute('offset',offset);stop.setAttribute('stop-color',color);stop.setAttribute('stop-opacity',String(numeric(offset==='0%'?op.startOpacity??1:op.endOpacity??1,0,1)));g.appendChild(stop);}defs.appendChild(g);e.setAttribute('fill',`url(#${id})`);if(this.project.baseAttributes[op.id])this.project.baseAttributes[op.id].fill=`url(#${id})`;return true;}
   case 'create':{if(!['path','rect','circle','ellipse','line','polygon','g'].includes(op.tag))throw Error('Unsupported shape');const parent=op.parent?this.editable(op.parent):this.doc.documentElement;if(!['g','svg'].includes(parent.localName))throw Error('Invalid shape parent');const id=op.id?safeId(op.id):this.unique(op.tag);if(this.index.has(id))throw Error('ID already exists');const e=this.doc.createElementNS(SVG_NS,op.tag);e.setAttribute('id',id);parent.appendChild(e);this.index.set(id,e);this.operation({type:'attributes',id,attrs:op.attrs},touched);return true;}
   case 'delete':{for(const id of op.ids){const e=this.editable(id);if(e===this.doc.documentElement)throw Error('Cannot delete canvas');const ids=[e,...elements(e)].map(e=>e.getAttribute('id')).filter(Boolean) as string[];e.parentNode!.removeChild(e);for(const target of ids){delete this.project.poses[target];delete this.project.baseTransforms[target];delete this.project.baseAttributes[target];this.project.tracks=this.project.tracks.filter(t=>t.target!==target);this.project.skins=this.project.skins.filter(s=>s.target!==target);this.project.meshes=this.project.meshes.filter(m=>m.target!==target);}}return true;}
   case 'part.prepare':{const nodes=op.ids.map(id=>this.editable(id));if(!nodes.length||nodes.length>500)throw Error('Select 1–500 prepared shapes');const parent=nodes[0].parentNode as Element;if(nodes.some(e=>e.parentNode!==parent)||parent.getAttribute('data-mai-alpha-group')!=='true')throw Error('Select sibling regions inside the preserved-alpha artwork group');if(nodes.some(e=>this.project.tracks.some(t=>t.target===e.getAttribute('id'))||this.project.skins.some(s=>s.target===e.getAttribute('id'))))throw Error('Prepare parts before binding or animation');const part=this.doc.createElementNS(SVG_NS,'g');part.setAttribute('id',this.unique('part'));part.setAttribute('data-mai-name',String(op.name).slice(0,200));part.setAttribute('mask',parent.getAttribute('mask')!);parent.parentNode!.insertBefore(part,parent.nextSibling);for(const e of nodes){if(e.localName==='path'){e.setAttribute('d',transformPath(e.getAttribute('d')!,e.getAttribute('transform')??''));e.removeAttribute('transform');}part.appendChild(e);}return true;}
   case 'group':{const nodes=op.ids.map(id=>this.editable(id));if(!nodes.length||nodes.some(e=>e===this.doc.documentElement))throw Error('Select objects to group');const parent=nodes[0].parentNode;if(nodes.some(e=>e.parentNode!==parent))throw Error('Group objects with the same parent');const id=op.id?safeId(op.id):this.unique('part');if(this.index.has(id))throw Error('Group ID exists');const e=this.doc.createElementNS(SVG_NS,'g');e.setAttribute('id',id);e.setAttribute('data-mai-name',op.name);parent!.insertBefore(e,nodes[0]);for(const node of nodes.sort((a,b)=>Array.from(parent!.childNodes).indexOf(a)-Array.from(parent!.childNodes).indexOf(b)))e.appendChild(node);return true;}
   case 'ungroup':{const e=this.editable(op.id);if(e.localName!=='g'||e.hasAttribute('transform')||e.hasAttribute('filter')||e.hasAttribute('mask')||Array.from(e.attributes).some(a=>!['id','data-mai-name','data-mai-locked'].includes(a.name))||this.project.tracks.some(t=>t.target===op.id))throw Error('Only plain, unanimated groups can be ungrouped without changing appearance');while(e.firstChild)e.parentNode!.insertBefore(e.firstChild,e);e.parentNode!.removeChild(e);return true;}
   case 'order':{const e=this.editable(op.id),p=e.parentNode!;if(e===this.doc.documentElement)throw Error('Cannot reorder canvas');if(op.direction==='front')p.appendChild(e);else if(op.direction==='back')p.insertBefore(e,p.firstChild);else if(op.direction==='forward'&&e.nextSibling)p.insertBefore(e,e.nextSibling.nextSibling);else if(op.direction==='backward'&&e.previousSibling)p.insertBefore(e,e.previousSibling);return true;}
   case 'rename':{const name=String(op.name).slice(0,200);touch(op.id).setAttribute('data-mai-name',name);if(this.project.baseAttributes[op.id])this.project.baseAttributes[op.id]['data-mai-name']=name;return false;}
   case 'lock':{const e=this.element(op.id);e.setAttribute('data-mai-locked',String(!!op.locked));if(this.project.baseAttributes[op.id])this.project.baseAttributes[op.id]['data-mai-locked']=String(!!op.locked);touched.add(op.id);return false;}
   case 'pose':{touch(op.id);this.remember(op.id);const p=this.project.poses[op.id]??defaultPose();for(const [key,value]of Object.entries(op.pose)){if(!(key in p))throw Error('Unknown pose property');numeric(value!);(p as unknown as Record<string,number>)[key]=value!;}this.project.poses[op.id]=p;this.applyPose(op.id,p);return false;}
   case 'point.move':this.setPath(op.id,movePoint(touch(op.id).getAttribute('d')!,op.segment,op.point,numeric(op.x),numeric(op.y)));return false;
   case 'point.add':this.setPath(op.id,addPoint(touch(op.id).getAttribute('d')!,op.segment));return false;
   case 'point.remove':this.setPath(op.id,removePoint(touch(op.id).getAttribute('d')!,op.segment));return false;
   case 'path.curve':{const e=touch(op.id),data=segments(e.getAttribute('d')!);const segment=data[op.segment],start=data[op.segment-1]?.points.at(-1);if(segment?.kind!=='L'||!start)throw Error('Select a line segment to convert to a curve');const end=segment.points[0];segment.kind='C';segment.points=[{x:start.x+(end.x-start.x)/3,y:start.y+(end.y-start.y)/3},{x:start.x+(end.x-start.x)*2/3,y:start.y+(end.y-start.y)*2/3},end];this.setPath(op.id,pathData(data));return false;}
   case 'path.close':{const e=touch(op.id),data=segments(e.getAttribute('d')!);if(data.at(-1)?.kind!=='Z')data.push({kind:'Z',points:[]});this.setPath(op.id,pathData(data));return false;}
   case 'path.split':{const e=touch(op.id);if(this.project.tracks.some(t=>t.target===op.id)||this.project.skins.some(s=>s.target===op.id))throw Error('Unbind and remove path keyframes before splitting');const [a,b]=splitPath(e.getAttribute('d')!,op.segment);this.setPath(op.id,a);const next=e.cloneNode(true) as Element;next.setAttribute('id',this.unique('path'));next.setAttribute('d',b);e.parentNode!.insertBefore(next,e.nextSibling);return true;}
   case 'path.join':case 'path.boolean':{const [a,b]=op.ids.map(id=>this.editable(id));if(a===b||a.localName!=='path'||b.localName!=='path'||a.parentNode!==b.parentNode)throw Error('Select two sibling paths');if(this.project.skins.some(s=>op.ids.includes(s.target))||this.project.tracks.some(t=>op.ids.includes(t.target)))throw Error('Unbind rig and remove animation before combining paths');const d1=transformPath(a.getAttribute('d')!,a.getAttribute('transform')||''),d2=transformPath(b.getAttribute('d')!,b.getAttribute('transform')||'');const d=op.type==='path.join'?joinPaths(d1,d2):booleanPaths(d1,d2,op.operation);a.removeAttribute('transform');delete this.project.poses[op.ids[0]];delete this.project.baseTransforms[op.ids[0]];delete this.project.baseAttributes[op.ids[0]];this.setPath(op.ids[0],d);this.operation({type:'delete',ids:[op.ids[1]]},touched);return true;}
   case 'path.simplify':{const d=touch(op.id).getAttribute('d')!;this.setPath(op.id,simplifyPath(d,numeric(op.tolerance,0.01,100)));return false;}
   case 'keyframe':{numeric(op.time,0,this.project.duration);const string=['d','fill','stroke'].includes(op.property);if(string){if(typeof op.value!=='string')throw Error('Keyframe value must be a string');if(op.property==='d'){const e=this.element(op.target);if(topology(e.getAttribute('d')!)!==topology(op.value))throw Error('Path keyframes require matching topology');}else if(!/^#[0-9a-f]{6}$/i.test(op.value))throw Error('Color animation requires #RRGGBB');}else numeric(op.value as number);
    if(op.property.startsWith('bone')){if(!this.project.bones.some(b=>b.id===op.target))throw Error('Bone does not exist');}
    else if(op.property.startsWith('mesh')){const [id,index]=op.target.split('::');if(!this.project.meshes.find(m=>m.target===id)?.controls[Number(index)])throw Error('Mesh point does not exist');}
    else{this.editable(op.target);this.remember(op.target);}
    if(!['x','y','rotation','scaleX','scaleY','opacity','fill','stroke','d','boneRotation','boneX','boneY','meshX','meshY'].includes(op.property))throw Error('Unsupported animation property');
    let track=this.project.tracks.find(t=>t.target===op.target&&t.property===op.property);if(!track){track={target:op.target,property:op.property,keys:[]};this.project.tracks.push(track);}const easing=op.easing??'linear';if(!['linear','ease-in-out','step'].includes(easing))throw Error('Unknown easing');track.keys=track.keys.filter(k=>k.time!==op.time);track.keys.push({time:op.time,value:op.value,easing});track.keys.sort((a,b)=>a.time-b.time);return false;}
   case 'keyframe.delete':{this.project.tracks=this.project.tracks.map(t=>t.target===op.target&&t.property===op.property?{...t,keys:t.keys.filter(k=>k.time!==op.time)}:t).filter(t=>t.keys.length);return false;}
   case 'timeline':if(op.duration!==undefined){numeric(op.duration,.1,300);if(this.project.tracks.some(t=>t.keys.some(k=>k.time>op.duration!)))throw Error('Duration would cut existing keyframes');this.project.duration=op.duration;}if(op.fps!==undefined)this.project.fps=numeric(op.fps,1,60);if(op.loop!==undefined)this.project.loop=!!op.loop;return false;
   case 'bone.add':{const b=structuredClone(op.bone);safeId(b.id);if(this.index.has(b.id)||this.project.bones.some(p=>p.id===b.id))throw Error('Bone ID exists');numeric(b.rest.x);numeric(b.rest.y);numeric(b.rest.length,1,1e5);numeric(b.rest.angle,-360,360);this.project.bones.push(b);boneMatrices(this.project.bones);return false;}
   case 'bone.pose':{const b=this.project.bones.find(b=>b.id===op.id);if(!b)throw Error('Bone not found');for(const field of ['rotation','x','y','minRotation','maxRotation']as const)if(op[field]!==undefined)b[field]=numeric(op[field]!);if(b.minRotation>b.maxRotation)throw Error('Invalid rotation limits');b.rotation=Math.max(b.minRotation,Math.min(b.maxRotation,b.rotation));return false;}
   case 'bone.ik':solveIK(this.project.bones,op.tip,{x:numeric(op.target.x),y:numeric(op.target.y)},!!op.flip);return false;
   case 'skin.bind':{const bones=op.bones.map(id=>this.project.bones.find(b=>b.id===id));if(!bones.length||bones.some(b=>!b))throw Error('Select existing bones');if(op.ids.length>500)throw Error('Bind prepared parts, not an entire fragmented raster trace');for(const id of op.ids){const rest=this.normalizeForRig(id),points=rest.flatMap(s=>s.points);if(points.length>10000)throw Error('Simplify this part before binding');this.project.skins=this.project.skins.filter(s=>s.target!==id);this.project.skins.push({target:id,rest,weights:points.map(p=>autoWeights(p,bones as typeof this.project.bones))});touched.add(id);}return false;}
   case 'skin.unbind':for(const id of op.ids){this.project.skins=this.project.skins.filter(s=>s.target!==id);this.project.meshes=this.project.meshes.filter(m=>m.target!==id);this.project.tracks=this.project.tracks.filter(t=>!t.target.startsWith(id+'::'));}return false;
   case 'skin.weight':{const skin=this.project.skins.find(s=>s.target===op.id);if(!skin||!skin.weights[op.index]||!this.project.bones.some(b=>b.id===op.bone))throw Error('Weight target does not exist');const w=numeric(op.weight,0,1),weights=skin.weights[op.index],others=Object.entries(weights).filter(([id])=>id!==op.bone);const total=others.reduce((s,[,v])=>s+v,0);skin.weights[op.index]=total?Object.fromEntries([...others.map(([id,v])=>[id,v/total*(1-w)]),[op.bone,w]]):{[op.bone]:1};return false;}
   case 'mesh.add':{const rows=numeric(op.rows,2,8),cols=numeric(op.cols,2,8);if(!Number.isInteger(rows)||!Number.isInteger(cols))throw Error('Mesh rows and cols must be integers');let skin=this.project.skins.find(s=>s.target===op.id);if(!skin){const rest=this.normalizeForRig(op.id);skin={target:op.id,rest,weights:rest.flatMap(s=>s.points).map(()=>({}))};this.project.skins.push(skin);}const points=skin.rest.flatMap(s=>s.points);if(!points.length)throw Error('Empty path');const x=Math.min(...points.map(p=>p.x)),y=Math.min(...points.map(p=>p.y)),width=Math.max(...points.map(p=>p.x))-x,height=Math.max(...points.map(p=>p.y))-y;const rest=Array.from({length:rows*cols},(_,i)=>({x:x+(i%cols)/(cols-1)*width,y:y+Math.floor(i/cols)/(rows-1)*height}));this.project.meshes=this.project.meshes.filter(m=>m.target!==op.id);this.project.meshes.push({target:op.id,rows,cols,rest,controls:structuredClone(rest),bounds:{x,y,width,height}});touched.add(op.id);return false;}
   case 'mesh.move':{const mesh=this.project.meshes.find(m=>m.target===op.id);if(!mesh?.controls[op.index])throw Error('Mesh point not found');mesh.controls[op.index]={x:numeric(op.x),y:numeric(op.y)};return false;}
   default:throw Error(`Unknown operation ${(op as {type:string}).type}`);
  }
 }
 checkProject(){const p=this.project;if(p.identity){if(!Array.isArray(p.identity.ids)||p.identity.ids.length>500)throw Error('Invalid identity protection');p.identity.ids.forEach(safeId);}validateLibraries(p);numeric(p.duration,.1,300);numeric(p.fps,1,60);if(!Array.isArray(p.tracks)||!Array.isArray(p.bones)||!Array.isArray(p.skins)||!Array.isArray(p.meshes)||!p.poses)throw Error('Invalid project metadata');if(p.bones.length>128||p.tracks.length>5000||p.skins.length>500||p.meshes.length>500)throw Error('Project complexity limit');for(const b of p.bones){safeId(b.id);numeric(b.rest.length,1,1e5);numeric(b.rest.x);numeric(b.rest.y);numeric(b.rest.angle,-360,360);numeric(b.x);numeric(b.y);numeric(b.rotation);numeric(b.minRotation);numeric(b.maxRotation);}for(const [id,pose] of Object.entries(p.poses)){safeId(id);for(const key of Object.keys(defaultPose()))numeric(pose[key as keyof Pose]);}boneMatrices(p.bones);if(p.skins.reduce((n,s)=>n+s.rest.reduce((n,s)=>n+s.points.length,0),0)>100000)throw Error('Rig exceeds 100,000 control points');for(const t of p.tracks){if(!t.keys.length||t.keys.length>2000)throw Error('Invalid keyframe count');for(const k of t.keys)numeric(k.time,0,p.duration);}}
 toSVG(embed=true){const root=this.doc.documentElement;const old=elements(this.doc).find(e=>e.localName==='metadata'&&e.getAttribute('id')==='mai-project');old?.parentNode?.removeChild(old);if(embed){const metadata=this.doc.createElementNS(SVG_NS,'metadata');metadata.setAttribute('id','mai-project');metadata.textContent=JSON.stringify(this.project);root.insertBefore(metadata,root.firstChild);}const result=serialize(this.doc);if(embed){const metadata=elements(this.doc).find(e=>e.localName==='metadata'&&e.getAttribute('id')==='mai-project');metadata?.parentNode?.removeChild(metadata);}return result;}
 frame(time:number){const doc=parseSvg(this.toSVG(false)),frame=frameState(this.project,time);const byId=new Map(elements(doc).map(e=>[e.getAttribute('id'),e]));for(const [id,p]of Object.entries(frame.poses)){const e=byId.get(id);if(e)e.setAttribute('transform',`${poseTransform(p)} ${this.project.baseTransforms[id]??''}`.trim());}for(const [id,attrs]of Object.entries(frame.attrs)){const e=byId.get(id);if(e)for(const [name,value]of Object.entries(attrs))e.setAttribute(name,value);}return serialize(doc);}
}
function safeIdExceptMetadata(id:string){if(id==='mai-project')return;safeId(id);}
export const starterSvg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 700 700"><title>MAI SVG · primer movimiento</title><g id="character" data-mai-name="Gato de práctica"><path id="body" data-mai-name="Cuerpo" d="M240 420 C190 320 205 230 270 185 L255 95 L335 160 L415 95 L430 190 C505 245 505 345 450 420 L450 540 L245 540 Z" fill="#dfad78"/><path id="tail" data-mai-name="Cola" d="M450 480 C570 515 610 380 530 350 C565 445 500 440 450 440 Z" fill="#c38253"/><path id="eye-left" data-mai-name="Ojo izquierdo" d="M275 265 C275 235 310 235 310 265 C310 295 275 295 275 265 Z" fill="#222838"/><path id="eye-right" data-mai-name="Ojo derecho" d="M375 265 C375 235 410 235 410 265 C410 295 375 295 375 265 Z" fill="#222838"/><path id="nose" d="M325 302 L360 302 L343 322 Z" fill="#c66e7d"/></g></svg>`;
