// Delivery budgets. There is no single optimal SVG: pick the profile from the destination, not from taste.
export type Profile={id:string;label:string;maxPaths:number;maxPoints:number;maxBytes:number;maxFilters:number;maxMasks:number;targetFps:number;technologies:string[];when:string;cleanup:{minArea:number;simplify:number;precision:number;keepProtected:boolean}};
const MB=1024*1024;
export const PROFILES:Record<string,Profile>={
 editable:{id:'editable',label:'Editable',maxPaths:100000,maxPoints:5e6,maxBytes:32*MB,maxFilters:64,maxMasks:64,targetFps:30,technologies:['mai-metadata','smil','filters','masks'],when:'Seguir editando en MAI; conserva rig, expresiones y modificadores.',cleanup:{minArea:0,simplify:0,precision:4,keepProtected:true}},
 archive:{id:'archive',label:'Archivo',maxPaths:100000,maxPoints:5e6,maxBytes:32*MB,maxFilters:64,maxMasks:64,targetFps:30,technologies:['mai-metadata','smil','filters','masks'],when:'Conservar el máster aprobado sin pérdidas.',cleanup:{minArea:0,simplify:0,precision:4,keepProtected:true}},
 'high-quality':{id:'high-quality',label:'Alta calidad',maxPaths:60000,maxPoints:3e6,maxBytes:16*MB,maxFilters:32,maxMasks:32,targetFps:30,technologies:['smil','filters','masks'],when:'Póster, render final o hero: fidelidad sobre peso.',cleanup:{minArea:.05,simplify:0,precision:3,keepProtected:true}},
 web:{id:'web',label:'Web',maxPaths:20000,maxPoints:6e5,maxBytes:4*MB,maxFilters:8,maxMasks:8,targetFps:60,technologies:['smil','css','filters','masks'],when:'Página web con animación SMIL; Chromium/Firefox/WebKit.',cleanup:{minArea:.25,simplify:.15,precision:2,keepProtected:true}},
 'web-light':{id:'web-light',label:'Web ligera',maxPaths:4000,maxPoints:1.2e5,maxBytes:MB,maxFilters:2,maxMasks:2,targetFps:60,technologies:['smil','css'],when:'Ilustración secundaria o móvil lento; acepta pérdida de microdetalle.',cleanup:{minArea:2,simplify:.4,precision:1,keepProtected:true}},
 animation:{id:'animation',label:'Animación',maxPaths:15000,maxPoints:4e5,maxBytes:6*MB,maxFilters:6,maxMasks:6,targetFps:60,technologies:['smil','filters','masks'],when:'Personaje animado en navegador; prioriza fps estables.',cleanup:{minArea:.5,simplify:.2,precision:2,keepProtected:true}},
 mobile:{id:'mobile',label:'Móvil',maxPaths:6000,maxPoints:1.5e5,maxBytes:1.5*MB,maxFilters:2,maxMasks:4,targetFps:60,technologies:['smil','css'],when:'Apps/web móvil: CPU y memoria limitadas.',cleanup:{minArea:1,simplify:.3,precision:2,keepProtected:true}},
 game:{id:'game',label:'Videojuego',maxPaths:8000,maxPoints:2e5,maxBytes:2*MB,maxFilters:0,maxMasks:2,targetFps:60,technologies:['svg-static','sprite-sheet','png-sequence'],when:'Motor de juego: sprites/atlas renderizados; sin filtros en tiempo real.',cleanup:{minArea:.75,simplify:.25,precision:2,keepProtected:true}},
 sprite:{id:'sprite',label:'Sprite',maxPaths:10000,maxPoints:2.5e5,maxBytes:4*MB,maxFilters:4,maxMasks:4,targetFps:30,technologies:['svg-static','sprite-sheet','png-sequence'],when:'Fotogramas congelados para atlas.',cleanup:{minArea:.5,simplify:.2,precision:2,keepProtected:true}},
 icon:{id:'icon',label:'Icono',maxPaths:200,maxPoints:5000,maxBytes:50*1024,maxFilters:0,maxMasks:0,targetFps:60,technologies:['svg-static','css'],when:'Icono/UI a 16–128 px: formas mínimas.',cleanup:{minArea:8,simplify:1,precision:1,keepProtected:false}},
};
