import type {VectorDocument} from './document.js';
import {safeId} from './document.js';
import {segments,type Point} from './geometry.js';
import {elements} from '../converter/svg.js';
import {regionBounds,insideRegion} from './warp.js';
import type {Operation,Project,SemanticNode,ProtectionLevel,Region,SemanticRelation} from './model.js';
export const ROLES=['character','head','face','eye-left','eye-right','iris','pupil','eyelid','brow-left','brow-right','nose','muzzle','mouth','ear-left','ear-right','body','torso','arm','hand','leg','foot','paw','tail','hair','clothing','accessory','bottle','flask','liquid','smoke','steam','fire','water','shadow','highlight','background','particle','effect','prop','other'];
export const LEVELS:ProtectionLevel[]=['locked','protected','deformable','style-preserved','topology-preserved','color-preserved','silhouette-preserved','free'];
// What each level allows. Categories are derived from operations in identity-guard.ts.
export const ALLOWED:Record<ProtectionLevel,string[]>={
 locked:[],protected:['rigid','extract'],deformable:['rigid','scale','geometry','visibility','extract'],
 'topology-preserved':['rigid','scale','geometry','style','visibility','extract'],'color-preserved':['rigid','scale','geometry','topology','visibility','structure','extract'],
 'style-preserved':['rigid','scale','geometry','topology','visibility','structure','extract'],'silhouette-preserved':['rigid','geometry','style','visibility','extract'],
 free:['rigid','scale','geometry','topology','style','visibility','structure','extract'],
};
export const LEVEL_MEANING:Record<ProtectionLevel,string>={
 locked:'Nada puede cambiar, ni siquiera la pose.',protected:'Solo movimiento rígido (posición/rotación).',deformable:'Puede deformarse por expresiones/warps; sin recolorear, borrar ni cambiar topología.',
 'style-preserved':'Geometría libre; colores, gradientes y trazos intactos.','topology-preserved':'Puntos móviles y estilo editable; sin añadir/quitar nodos ni dividir.','color-preserved':'Cualquier cambio salvo color/gradiente/trazo.',
 'silhouette-preserved':'Deformaciones permitidas si la silueta se mantiene: identity.check mide IoU de la máscara renderizada contra una referencia (≥ 0.9).',free:'Sin restricciones de identidad.',
};
const finite=(n:unknown,min=-1e6,max=1e6)=>{if(typeof n!=='number'||!Number.isFinite(n)||n<min||n>max)throw Error('Invalid semantic numeric value');return n;};
export function validateRegion(r:Region){if(!r||typeof r!=='object')throw Error('Invalid region');if(r.kind==='ellipse'){finite(r.cx);finite(r.cy);finite(r.rx,.1);finite(r.ry,.1);}else if(r.kind==='rect'){finite(r.x);finite(r.y);finite(r.width,.1);finite(r.height,.1);}else if(r.kind==='polygon'){if(!Array.isArray(r.points)||r.points.length<3||r.points.length>2000)throw Error('Polygon needs 3–2000 points');for(const p of r.points){finite(p.x);finite(p.y);}}else throw Error('Unknown region kind');return r;}
export function validateNode(n:SemanticNode){safeId(n.id);if(typeof n.role!=='string'||!/^[a-z][a-z0-9-]{0,59}$/.test(n.role))throw Error('Semantic role must be lowercase kebab-case');if(typeof n.label!=='string'||n.label.length>200)throw Error('Invalid semantic label');
 if(!Array.isArray(n.targets)||n.targets.length>5000)throw Error('Semantic node targets: 0–5000 IDs');n.targets.forEach(safeId);if(n.parent)safeId(n.parent);if(!['proposed','confirmed','rejected'].includes(n.status)||!['user','agent','heuristic'].includes(n.source))throw Error('Invalid semantic status/source');
 if(n.confidence!==undefined)finite(n.confidence,0,1);if(n.protection&&(!Array.isArray(n.protection)||n.protection.some(l=>!LEVELS.includes(l))))throw Error('Unknown protection level');if(n.landmarks){if(Object.keys(n.landmarks).length>64)throw Error('Too many landmarks');for(const [k,p]of Object.entries(n.landmarks)){safeId(k);finite(p.x);finite(p.y);}}if(n.region)validateRegion(n.region);if(n.reference&&(!['snapshot','baseline'].includes(n.reference.kind)||typeof n.reference.id!=='string'||!/^[A-Za-z0-9][\w.:-]{0,127}$/.test(n.reference.id)))throw Error('Invalid identity reference');if(n.notes!==undefined&&(typeof n.notes!=='string'||n.notes.length>2000))throw Error('Invalid notes');}
export function validateSemantic(p:Project){const s=p.semantic;if(!s)return;if(!Array.isArray(s.nodes)||!Array.isArray(s.relations)||s.nodes.length>2000||s.relations.length>5000)throw Error('Invalid semantic graph');const ids=new Set<string>();for(const n of s.nodes){validateNode(n);if(ids.has(n.id))throw Error('Duplicate semantic node');ids.add(n.id);}for(const n of s.nodes)if(n.parent&&!ids.has(n.parent))throw Error(`Semantic parent missing: ${n.parent}`);
 for(const r of s.relations){if(!ids.has(r.from)||!ids.has(r.to)||!['part-of','attached-to','emits','mirrors','left-of','right-of','above','below','follows'].includes(r.kind))throw Error('Invalid semantic relation');}
 const seen=new Set<string>();for(const n of s.nodes){let c:SemanticNode|undefined=n;const path=new Set<string>();while(c?.parent){if(path.has(c.id))throw Error('Semantic hierarchy cycle');path.add(c.id);c=s.nodes.find(x=>x.id===c!.parent);}seen.add(n.id);}}
const graph=(m:VectorDocument)=>m.project.semantic??={nodes:[],relations:[]};
const node=(m:VectorDocument,id:string)=>{const n=graph(m).nodes.find(n=>n.id===id);if(!n)throw Error(`Semantic node not found: ${id}`);return n;};
export function semanticOperation(m:VectorDocument,op:Operation){const g=graph(m);
 switch(op.type){
  case 'semantic.label':{const n:SemanticNode={status:'confirmed',source:'agent',...structuredClone(op.node)} as SemanticNode;for(const id of n.targets)m.element(id);validateNode(n);const i=g.nodes.findIndex(x=>x.id===n.id);if(i>=0)g.nodes[i]={...g.nodes[i],...n};else g.nodes.push(n);return;}
  case 'semantic.group':{safeId(op.id);if(g.nodes.some(n=>n.id===op.id))throw Error('Semantic node exists');for(const c of op.children)node(m,c);g.nodes.push({id:op.id,role:op.role,label:op.label,targets:[],status:'confirmed',source:'agent'});validateNode(g.nodes.at(-1)!);for(const c of op.children)node(m,c).parent=op.id;return;}
  case 'semantic.relate':{node(m,op.relation.from);node(m,op.relation.to);if(!g.relations.some(r=>r.from===op.relation.from&&r.to===op.relation.to&&r.kind===op.relation.kind))g.relations.push({...op.relation});return;}
  case 'semantic.unrelate':{g.relations=g.relations.filter(r=>!(r.from===op.relation.from&&r.to===op.relation.to&&r.kind===op.relation.kind));return;}
  case 'semantic.protect':{const n=node(m,op.id);if(!Array.isArray(op.protection)||op.protection.some(l=>!LEVELS.includes(l)))throw Error('Unknown protection level');n.protection=[...new Set(op.protection)];return;}
  case 'semantic.merge':{const nodes=op.ids.map(id=>node(m,id));safeId(op.into);const target=g.nodes.find(n=>n.id===op.into)??nodes[0];const merged={...target,id:op.into,label:op.label??target.label,targets:[...new Set(nodes.flatMap(n=>n.targets))],landmarks:Object.assign({},...nodes.map(n=>n.landmarks??{}))};g.nodes=g.nodes.filter(n=>!op.ids.includes(n.id)&&n.id!==op.into);g.nodes.push(merged);for(const n of g.nodes)if(n.parent&&op.ids.includes(n.parent))n.parent=op.into;for(const r of g.relations){if(op.ids.includes(r.from))r.from=op.into;if(op.ids.includes(r.to))r.to=op.into;}g.relations=g.relations.filter(r=>r.from!==r.to);return;}
  case 'semantic.split':{const n=node(m,op.id);if(!op.parts.length||op.parts.length>32)throw Error('Split needs 1–32 parts');for(const part of op.parts){safeId(part.id);if(g.nodes.some(x=>x.id===part.id))throw Error('Part ID exists');for(const t of part.targets)m.element(t);g.nodes.push({id:part.id,role:part.role??n.role,label:part.label,targets:part.targets,parent:n.id,status:'proposed',source:'agent',protection:n.protection});}n.targets=n.targets.filter(t=>!op.parts.some(p=>p.targets.includes(t)));return;}
  case 'semantic.confirm':node(m,op.id).status='confirmed';node(m,op.id).source='user';return;
  case 'semantic.reject':node(m,op.id).status='rejected';return;
  case 'semantic.remove':{node(m,op.id);g.nodes=g.nodes.filter(n=>n.id!==op.id);for(const n of g.nodes)if(n.parent===op.id)delete n.parent;g.relations=g.relations.filter(r=>r.from!==op.id&&r.to!==op.id);return;}
  case 'landmark.set':{const n=node(m,op.node);safeId(op.name);n.landmarks={...(n.landmarks??{}),[op.name]:{x:finite(op.x),y:finite(op.y)}};return;}
  case 'landmark.delete':{const n=node(m,op.node);if(n.landmarks)delete n.landmarks[op.name];return;}
 }
 throw Error('Unknown semantic operation');
}
// Path bounding boxes are cached per document instance; they are the basis for prompts, IR and audits.
const boxCache=new WeakMap<VectorDocument,Map<string,{x0:number;y0:number;x1:number;y1:number;n:number;fill:string}>>();
export function pathBoxes(m:VectorDocument){let cache=boxCache.get(m);if(cache&&cache.size)return cache;cache=new Map();
 for(const e of elements(m.doc)){if(e.localName!=='path')continue;const id=e.getAttribute('id');if(!id)continue;try{let x0=Infinity,y0=Infinity,x1=-Infinity,y1=-Infinity,n=0;for(const s of segments(e.getAttribute('d')??''))for(const p of s.points){n++;if(p.x<x0)x0=p.x;if(p.y<y0)y0=p.y;if(p.x>x1)x1=p.x;if(p.y>y1)y1=p.y;}if(n)cache.set(id,{x0,y0,x1,y1,n,fill:e.getAttribute('fill')??''});}catch{}}
 boxCache.set(m,cache);return cache;}
export const invalidateBoxes=(m:VectorDocument)=>boxCache.delete(m);
const rgb=(c:string)=>{const m=/^#?([\da-f]{2})([\da-f]{2})([\da-f]{2})$/i.exec(c.trim());return m?[1,2,3].map(i=>parseInt(m[i],16)):null;};
export function lab(c:string){const v=rgb(c);if(!v)return null;const [r,g,b]=v.map(x=>{x/=255;return x>.04045?Math.pow((x+.055)/1.055,2.4):x/12.92;});const X=(r*.4124+g*.3576+b*.1805)/.95047,Y=r*.2126+g*.7152+b*.0722,Z=(r*.0193+g*.1192+b*.9505)/1.08883;const f=(t:number)=>t>.008856?Math.cbrt(t):7.787*t+16/116;return [116*f(Y)-16,500*(f(X)-f(Y)),200*(f(Y)-f(Z))];}
export const deltaE=(a:string,b:string)=>{const x=lab(a),y=lab(b);return x&&y?Math.hypot(x[0]-y[0],x[1]-y[1],x[2]-y[2]):Infinity;};
export type Candidate={id:string;label:string;method:string;targets:string[];bounds:{x:number;y:number;width:number;height:number};paths:number;meanColor?:string;confidence:number;reason:string};
// Promptable segmentation over vector geometry (point / box / negative points), SAM-style multi-granularity output.
export function candidates(m:VectorDocument,prompt:{point?:Point;box?:{x:number;y:number;width:number;height:number};negative?:Point[];scope?:string;region?:Region}):Candidate[]{
 const boxes=pathBoxes(m),scope=prompt.scope?new Set([prompt.scope,...elements(m.element(prompt.scope)).map(e=>e.getAttribute('id')).filter(Boolean) as string[]]):null;
 const box=prompt.box??(prompt.region?regionBounds(prompt.region):prompt.point?{x:prompt.point.x-24,y:prompt.point.y-24,width:48,height:48}:undefined);if(!box)throw Error('Prompt needs point, box or region');
 const inScope=(id:string)=>!scope||scope.has(id);const hits=[...boxes].filter(([id,b])=>inScope(id)&&!(b.x1<box.x||b.x0>box.x+box.width||b.y1<box.y||b.y0>box.y+box.height));
 const area=(b:{x0:number;y0:number;x1:number;y1:number})=>Math.max(0,b.x1-b.x0)*Math.max(0,b.y1-b.y0);
 const inside=hits.filter(([,b])=>b.x0>=box.x&&b.x1<=box.x+box.width&&b.y0>=box.y&&b.y1<=box.y+box.height&&(!prompt.region||insideRegion(prompt.region,{x:(b.x0+b.x1)/2,y:(b.y0+b.y1)/2})));
 const negative=(b:{x0:number;y0:number;x1:number;y1:number})=>(prompt.negative??[]).some(p=>p.x>=b.x0&&p.x<=b.x1&&p.y>=b.y0&&p.y<=b.y1&&area(b)<box.width*box.height);
 const seedColor=(()=>{if(!prompt.point)return undefined;const under=hits.filter(([,b])=>prompt.point!.x>=b.x0&&prompt.point!.x<=b.x1&&prompt.point!.y>=b.y0&&prompt.point!.y<=b.y1).sort((a,b)=>area(a[1])-area(b[1]));return under[0]?.[1].fill;})();
 const out:Candidate[]=[];const push=(id:string,label:string,method:string,ids:string[],confidence:number,reason:string)=>{const sel=ids.filter(i=>!negative(boxes.get(i)!));if(!sel.length||out.some(c=>c.targets.length===sel.length&&c.targets.every((t,i)=>t===sel[i])))return;const bs=sel.map(i=>boxes.get(i)!),x0=Math.min(...bs.map(b=>b.x0)),y0=Math.min(...bs.map(b=>b.y0)),x1=Math.max(...bs.map(b=>b.x1)),y1=Math.max(...bs.map(b=>b.y1));out.push({id,label,method,targets:sel,bounds:{x:x0,y:y0,width:x1-x0,height:y1-y0},paths:sel.length,meanColor:meanColor(bs.map(b=>b.fill)),confidence,reason});};
 if(seedColor){const near=inside.filter(([,b])=>deltaE(b.fill,seedColor)<18).map(([id])=>id);push('A','Mismo color','color',near,.55,`Formas dentro de la región con color cercano a ${seedColor} (ΔE<18).`);
  // Connected growth: neighbours whose boxes touch and colors stay within ΔE 28.
  const pool=new Map(hits),seeds=hits.filter(([,b])=>prompt.point!.x>=b.x0&&prompt.point!.x<=b.x1&&prompt.point!.y>=b.y0&&prompt.point!.y<=b.y1&&area(b)<box.width*box.height*2).map(([id])=>id);const grown=new Set(seeds),queue=[...seeds];
  while(queue.length&&grown.size<4000){const b=pool.get(queue.shift()!)!;for(const [id,c]of pool){if(grown.has(id)||c.x1<b.x0-1||c.x0>b.x1+1||c.y1<b.y0-1||c.y0>b.y1+1||deltaE(c.fill,seedColor)>28)continue;grown.add(id);queue.push(id);}}
  push('B','Región conectada','connected',[...grown],.6,'Crecimiento por vecindad desde el punto, color dentro de ΔE 28 y límite de la caja.');}
 push(out.length===0?'A':out.length===1?'B':'C','Todo dentro de la región','inside',inside.map(([id])=>id),.45,'Todas las formas completamente contenidas; incluye detalles vecinos.');
 return out.slice(0,6).map((c,i)=>({...c,id:String.fromCharCode(65+i)}));
}
function meanColor(fills:string[]){const v=fills.map(rgb).filter(Boolean) as number[][];if(!v.length)return undefined;return '#'+[0,1,2].map(i=>Math.round(v.reduce((s,c)=>s+c[i],0)/v.length).toString(16).padStart(2,'0')).join('');}
// Heuristic face proposals inside a head region. Always `proposed`: confirm with the user.
export function suggestFace(m:VectorDocument,head:{x:number;y:number;width:number;height:number},scope?:string):SemanticNode[]{
 const boxes=pathBoxes(m);const scopeIds=scope?new Set(elements(m.element(scope)).map(e=>e.getAttribute('id'))):null;
 const items=[...boxes].filter(([id,b])=>(!scopeIds||scopeIds.has(id))&&b.x0>=head.x&&b.x1<=head.x+head.width&&b.y0>=head.y&&b.y1<=head.y+head.height).map(([id,b])=>{const c=rgb(b.fill)??[0,0,0],max=Math.max(...c),min=Math.min(...c),sat=max?(max-min)/max:0;return {id,b,sat,v:max/255,cx:(b.x0+b.x1)/2,cy:(b.y0+b.y1)/2,a:(b.x1-b.x0)*(b.y1-b.y0)};});
 const cells=new Map<string,typeof items>();const cell=Math.max(8,head.width/12);for(const it of items.filter(i=>i.sat>.45&&i.v>.25)){const k=`${Math.floor(it.cx/cell)}:${Math.floor(it.cy/cell)}`;const list=cells.get(k)??[];list.push(it);cells.set(k,list);}
 const clusters=[...cells.values()].map(list=>({list,weight:list.reduce((s,i)=>s+i.a,0),cx:list.reduce((s,i)=>s+i.cx*i.a,0)/Math.max(1e-9,list.reduce((s,i)=>s+i.a,0)),cy:list.reduce((s,i)=>s+i.cy*i.a,0)/Math.max(1e-9,list.reduce((s,i)=>s+i.a,0))})).filter(c=>c.cy<head.y+head.height*.75).sort((a,b)=>b.weight-a.weight);
 const out:SemanticNode[]=[];const [a,b]=clusters;if(a&&b&&Math.abs(a.cx-b.cx)>head.width*.15){const [left,right]=a.cx<b.cx?[a,b]:[b,a];for(const [side,c]of [['left',left],['right',right]] as const){const r=cell*1.2;out.push({id:`eye-${side}-proposal`,role:`eye-${side}`,label:`Ojo ${side==='left'?'izquierdo':'derecho'} (propuesta)`,targets:items.filter(i=>Math.hypot(i.cx-c.cx,i.cy-c.cy)<r&&i.sat>.3).map(i=>i.id).slice(0,2000),status:'proposed',confidence:.5,source:'heuristic',region:{kind:'ellipse',cx:Number(c.cx.toFixed(1)),cy:Number(c.cy.toFixed(1)),rx:Number(r.toFixed(1)),ry:Number(r.toFixed(1))},landmarks:{center:{x:Number(c.cx.toFixed(1)),y:Number(c.cy.toFixed(1))}}});}
  const mid={x:(left.cx+right.cx)/2,y:Math.max(left.cy,right.cy)},span=Math.abs(right.cx-left.cx);const pink=items.filter(i=>{const c=rgb(boxes.get(i.id)!.fill)??[0,0,0];return c[0]>c[1]+25&&c[0]>c[2]&&Math.abs(i.cx-mid.x)<span*.25&&i.cy>mid.y&&i.cy<mid.y+span*.5;});
  if(pink.length){const cx=pink.reduce((s,i)=>s+i.cx,0)/pink.length,cy=pink.reduce((s,i)=>s+i.cy,0)/pink.length;out.push({id:'nose-proposal',role:'nose',label:'Nariz (propuesta)',targets:pink.map(i=>i.id).slice(0,500),status:'proposed',confidence:.35,source:'heuristic',landmarks:{center:{x:Number(cx.toFixed(1)),y:Number(cy.toFixed(1))}}});
   out.push({id:'mouth-proposal',role:'mouth',label:'Boca (propuesta: debajo de la nariz)',targets:[],status:'proposed',confidence:.25,source:'heuristic',region:{kind:'ellipse',cx:Number(cx.toFixed(1)),cy:Number((cy+span*.22).toFixed(1)),rx:Number((span*.35).toFixed(1)),ry:Number((span*.17).toFixed(1))},notes:'Región aproximada; confirma o marca las comisuras como landmarks.'});}}
 return out;
}
export type IRNode={id:string;role:string;label:string;status:string;protection:ProtectionLevel[];targets:number;bounds?:{x:number;y:number;width:number;height:number};landmarks:string[];animated:string[];expression?:string;modifiers:string[];relations:string[];children:IRNode[]};
// Agent-readable intermediate representation: never contains path data.
export function buildIR(m:VectorDocument){const p=m.project,s=p.semantic??{nodes:[],relations:[]},boxes=pathBoxes(m);
 const descendantPaths=(id:string)=>{const e=m.index.get(id);if(!e)return [];return [e,...elements(e)].filter(x=>x.localName==='path').map(x=>x.getAttribute('id')!).filter(Boolean);};
 const bounds=(n:SemanticNode)=>{const ids=n.targets.flatMap(descendantPaths).filter(id=>boxes.has(id));if(!ids.length)return n.region?regionBounds(n.region):undefined;const bs=ids.map(id=>boxes.get(id)!);const x=Math.min(...bs.map(b=>b.x0)),y=Math.min(...bs.map(b=>b.y0));return {x:Number(x.toFixed(1)),y:Number(y.toFixed(1)),width:Number((Math.max(...bs.map(b=>b.x1))-x).toFixed(1)),height:Number((Math.max(...bs.map(b=>b.y1))-y).toFixed(1))};};
 const to=(n:SemanticNode):IRNode=>{const t=new Set(n.targets.flatMap(id=>[id,...descendantPaths(id)]));return {id:n.id,role:n.role,label:n.label,status:n.status,protection:n.protection??[],targets:n.targets.length,bounds:bounds(n),landmarks:Object.keys(n.landmarks??{}),animated:[...new Set(p.tracks.filter(tr=>t.has(tr.target)).map(tr=>`${tr.target}.${tr.property}${tr.layer?'@'+tr.layer:''}`))].slice(0,40),expression:p.expression?.features.find(f=>f.node===n.id||f.paths.some(x=>t.has(x)))?.id,modifiers:(p.modifiers??[]).filter(mod=>mod.targets.some(x=>t.has(x))).map(mod=>`${mod.id}:${mod.kind}${mod.preset?'/'+mod.preset:''}${mod.enabled?'':' (off)'}`),relations:s.relations.filter(r=>r.from===n.id).map(r=>`${r.kind} → ${r.to}`),children:s.nodes.filter(c=>c.parent===n.id&&c.status!=='rejected').map(to)};};
 const labeled=new Set(s.nodes.flatMap(n=>n.targets.flatMap(id=>[id,...descendantPaths(id)])));
 return {asset:p.name,revision:p.revision,canvas:m.doc.documentElement.getAttribute('viewBox'),duration:p.duration,preservation:p.preservation??'balanced',params:Object.keys(p.params??{}),layers:(p.layers??[]).map(l=>`${l.id}:${l.blend}${l.mute?' muted':''}${l.solo?' solo':''}`),roots:s.nodes.filter(n=>!n.parent&&n.status!=='rejected').map(to),proposed:s.nodes.filter(n=>n.status==='proposed').map(n=>n.id),unlabeledPaths:[...boxes.keys()].filter(id=>!labeled.has(id)).length,expressions:(p.expression?.features??[]).map(f=>({id:f.id,role:f.role,paths:f.paths.length,landmarks:Object.keys(f.landmarks),params:Object.keys(f.keys)})),drivers:(p.expression?.drivers??[]).map(d=>`${d.param} → ${d.target}.${d.property}`),modifiers:(p.modifiers??[]).map(x=>({id:x.id,kind:x.kind,preset:x.preset,technique:x.technique??'geometry',enabled:x.enabled,targets:x.targets.length})),secondary:(p.secondary??[]).map(x=>`${x.id}: ${x.target}.${x.property} ${x.kind} ← ${x.driver}`),stateMachine:p.stateMachine?{states:p.stateMachine.states.map(s=>s.id),inputs:p.stateMachine.inputs.map(i=>i.name)}:null};
}
export function irText(ir:ReturnType<typeof buildIR>){const lines=[`${ir.asset} (rev ${ir.revision}, ${ir.duration}s, preservación ${ir.preservation})`];const walk=(n:IRNode,prefix:string,last:boolean)=>{lines.push(`${prefix}${last?'└':'├'} ${n.label} [${n.role}${n.status!=='confirmed'?', '+n.status:''}]${n.protection.length?' 🔒'+n.protection.join('+'):''}${n.expression?' ☺'+n.expression:''}${n.modifiers.length?' ≈'+n.modifiers.join(','):''}${n.animated.length?` ▶${n.animated.length}`:''}`);n.children.forEach((c,i)=>walk(c,prefix+(last?'  ':'│ '),i===n.children.length-1));};ir.roots.forEach((r,i)=>walk(r,'',i===ir.roots.length-1));lines.push(`Sin etiquetar: ${ir.unlabeledPaths} paths`);if(ir.proposed.length)lines.push(`Propuestas pendientes de confirmar: ${ir.proposed.join(', ')}`);return lines.join('\n');}
export type {SemanticRelation};
