import {Choices}from './choices.js';
import {Comments}from './comments.js';
import {Inbox,inboxFile}from './inbox.js';
import {Snapshots}from './snapshots.js';
import {PlanExecutor,readUndoToken,type Receipt}from '../agent/plan.js';
import {metrics as perceptualMetrics,raw as rawPixels}from './perceptual.js';
import {AgentService}from '../agent/service.js';
import {AgentError}from '../agent/address.js';
import {TOOLS,CONVENTIONS}from '../agent/registry.js';
import {detect}from '../core/detectors.js';
import {createServer,type IncomingMessage,type ServerResponse} from 'node:http';
import {readFile,writeFile,mkdir,rename,readdir,realpath,stat} from 'node:fs/promises';
import {resolve,join,extname,relative,sep} from 'node:path';
import {randomBytes,randomUUID} from 'node:crypto';
import {gzipSync,gunzipSync} from 'node:zlib';
import {WebSocketServer,WebSocket} from 'ws';
import {VectorDocument,starterSvg,type Snapshot} from '../core/document.js';
import type {Operation} from '../core/model.js';
import {exportSvg,type ExportOptions} from '../core/export.js';
import {convertFile,PRESETS,vectorizeRaster,vectorizeSvg} from '../converter/index.js';
import {renderSvg,closeRenderer} from './render.js';
const HISTORY_LIMIT=40;
export async function startEditorServer(port=4318,root=process.cwd()){
 if(!Number.isInteger(port)||port<1024||port>65535)throw Error('Invalid port');
 const cache=join(root,'.cache');await mkdir(cache,{recursive:true});await mkdir(join(cache,'events'),{recursive:true});
 let model=new VectorDocument(starterSvg,'demo'),asset='demo',revision=0;
 try{model=new VectorDocument(await readFile(join(cache,'current.svg'),'utf8'));revision=model.project.revision;asset=model.project.name;}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}
 const token=randomBytes(32).toString('hex'),origin=`http://127.0.0.1:${port}`,sessionId=`session-${randomUUID()}`;
 // documentId is the persistent identity of the asset (metadata), unlike its file name.
 const ensureDocument=(doc:VectorDocument)=>{doc.project.documentId??=`doc-${randomUUID()}`;return doc;};ensureDocument(model);
 const snapshots=new Snapshots(join(cache,'snapshots'));
 type Entry={revision:number;id:string;label:string;time:string;before:Buffer;after:Buffer};let undo:Entry[]=[],redo:Entry[]=[],entries:Omit<Entry,'before'|'after'>[]=[],selection:string[]=[];
 const pack=(s:Snapshot)=>gzipSync(JSON.stringify(s),{level:1}),unpack=(s:Buffer)=>JSON.parse(gunzipSync(s).toString()) as Snapshot;
 const files=(await readdir(join(cache,'events'))).filter(f=>f.endsWith('.json.gz')).sort();
 const receipts=new Map<string,Receipt>();
 for(const file of files){const event=JSON.parse(gunzipSync(await readFile(join(cache,'events',file))).toString());entries.push(event.info);if(event.receipt)receipts.set(event.receipt.requestId,event.receipt);if(event.info.revision>revision){model.restore(event.after);revision=event.info.revision;model.project.revision=revision;}if(event.kind==='apply'){undo.push({...event.info,before:pack(event.before),after:pack(event.after)});undo=undo.slice(-HISTORY_LIMIT);redo=[];}else if(event.kind==='undo'){const e=undo.pop();if(e)redo.push(e);}else if(event.kind==='redo'){const e=redo.pop();if(e)undo.push(e);}}
 let timer:ReturnType<typeof setTimeout>|undefined,saving=false,dirty=false;
 async function checkpoint(){if(saving){dirty=true;return;}saving=true;dirty=false;const source=model.toSVG();const path=join(cache,`current-${randomUUID()}.tmp`);try{await writeFile(path,source);await rename(path,join(cache,'current.svg'));}finally{saving=false;if(dirty)timer=setTimeout(()=>void checkpoint(),500);}}
 const save=()=>{dirty=true;if(timer)clearTimeout(timer);timer=setTimeout(()=>void checkpoint().catch(console.error),500);};
 const choices=new Choices(join(cache,'choices'));await choices.restore();
 const comments=new Comments(join(cache,'comments'));await comments.load(asset);
 const inbox=new Inbox(inboxFile(cache));await inbox.restore();
 const ws=new WebSocketServer({noServer:true});
 const summary=()=>({sessionId,documentId:model.project.documentId,revision,asset,inboxSeq:inbox.seq,openComments:comments.list.filter(c=>c.status==='open').length,choice:choices.public(),project:structuredClone(model.project),objects:model.count,canUndo:undo.length>0,canRedo:redo.length>0});
 // Agent/human events reach open editors immediately (activity feed); the inbox remains the durable source.
 inbox.onPush=event=>{const payload=JSON.stringify({type:'event',event});for(const socket of ws.clients)if(socket.readyState===WebSocket.OPEN)socket.send(payload);};
 const broadcast=(change:Record<string,unknown>)=>{const payload=JSON.stringify({type:'change',sentAt:Date.now(),...summary(),...change});for(const socket of ws.clients)if(socket.readyState===WebSocket.OPEN)socket.send(payload);};
 // The journal event is the commit point: document state, decisions (project metadata) and the plan receipt together.
 async function record(kind:string,label:string,before:Snapshot,after:Snapshot,receiptFn?:(tx:{revision:number;id:string})=>Receipt){const next=revision+1,info={revision:next,id:randomUUID(),label,time:new Date().toISOString()};model.project.revision=next;if(after.kind==='attributes')after.project.revision=next;else after.svg=model.toSVG();
  const receipt=receiptFn?.(info);const path=join(cache,'events',`${String(next).padStart(10,'0')}.json.gz`),temp=path+'.tmp';try{if(process.env.MAI_FAIL_PERSISTENCE==='1'&&receipt)throw Error('Injected persistence failure');await writeFile(temp,gzipSync(JSON.stringify({kind,info,before,after,...(receipt?{receipt}:{})}),{level:1}));await rename(temp,path);}catch(error){model.restore(before);model.project.revision=revision;throw Object.assign(Error(`Persistence failed before commit: ${String((error as Error).message)}`),{code:'PERSISTENCE_FAILED',status:500,detail:{committed:false}});}revision=next;entries.push(info);if(receipt)receipts.set(receipt.requestId,receipt);save();return {info,receipt};}
 let queue=Promise.resolve<unknown>(undefined);
 const queued=<T>(work:()=>Promise<T>):Promise<T>=>{const task=queue.then(work,work);queue=task.catch(()=>{});return task;};
 const expected=(value:unknown)=>{if(value!==revision)throw Object.assign(Error(`Revision conflict: expected ${value}, current ${revision}`),{status:409});};
 // Board state is a projection of journaled acceptances: after any apply/undo/redo/open re-derive it.
 async function syncChoices(){if(choices.sync(model.project)){await choices.save();return true;}return false;}
 async function apply(ops:Operation[],expectedRevision:number,label='Edición',source='cli',opts:{precondition?:()=>void;receipt?:(tx:{revision:number;id:string})=>Receipt}={}){return queued(async()=>{expected(expectedRevision);opts.precondition?.();const before=model.capture(ops);const started=performance.now();const change=model.apply(ops);const after=model.capture(ops);const {info,receipt}=await record('apply',label,before,after,opts.receipt);undo.push({...info,before:pack(before),after:pack(after)});undo=undo.slice(-HISTORY_LIMIT);redo=[];await syncChoices();const result={...summary(),...change,elapsedMs:Number((performance.now()-started).toFixed(2)),transaction:info,receipt};broadcast({...change,elapsedMs:result.elapsedMs});if(source==='editor')await inbox.push('edit.user',{revision,label,ops:ops.length,types:[...new Set(ops.map(o=>o.type))]},'El usuario editó la escena en el editor: relee IDs/estado antes de tu próxima transacción.');return result;});}
 async function open(svg:string,name:string,expectedRevision:number){return queued(async()=>{expected(expectedRevision);const next=ensureDocument(new VectorDocument(svg,name)),before:Snapshot={kind:'svg',svg:model.toSVG()};model=next;asset=name;model.project.name=name;await comments.load(name);const after:Snapshot={kind:'svg',svg:model.toSVG()};const {info}=await record('apply',`Abrir ${name}`,before,after);undo.push({...info,before:pack(before),after:pack(after)});undo=undo.slice(-HISTORY_LIMIT);redo=[];broadcast({reload:true,patches:[]});return summary();});}
 async function historyAction(kind:'undo'|'redo',expectedRevision:number,token?:string){return queued(async()=>{expected(expectedRevision);const from=kind==='undo'?undo:redo,to=kind==='undo'?redo:undo,entry=from.at(-1);if(!entry)throw Error(`Nothing to ${kind}`);if(token){const t=readUndoToken(token);const ok=t?t.d===model.project.documentId&&t.t===entry.id:token===`rev:${entry.revision}`;if(!ok)throw new AgentError('UNDO_NOT_LATEST',`${token} is not the latest undoable transaction of this document (latest: ${entry.label})`,{latest:{revision:entry.revision,label:entry.label}},409);}const before:Snapshot={kind:'svg',svg:model.toSVG()},after=unpack(kind==='undo'?entry.before:entry.after);model.restore(after);asset=model.project.name;await record(kind,`${kind}: ${entry.label}`,before,after);from.pop();to.push(entry);await syncChoices();broadcast({reload:true,patches:[]});return summary();});}
 const previous=()=>{const entry=undo.at(-1);if(!entry)return undefined;const snap=unpack(entry.before);if(snap.kind==='svg')return new VectorDocument(snap.svg);const draft=new VectorDocument(model.toSVG());draft.restore(snap);return draft;};
 const agent:AgentService=new AgentService({plans:()=>plans,model:()=>model,revision:()=>revision,asset:()=>asset,sessionId:()=>sessionId,documentId:()=>model.project.documentId!,snapshots,cache,root,selection:()=>selection,apply:(ops,expectedRevision,label,source)=>apply(ops,expectedRevision,label,source),undo:(r,token)=>historyAction('undo',r,token),redo:r=>historyAction('redo',r),history:()=>({revision,entries:entries.slice(-100),canUndo:undo.length>0,canRedo:redo.length>0}),previous,queued,broadcast,choices,comments,inbox,
  exportFile:async(profile,expectedRevision)=>{expected(expectedRevision);const result=exportSvg(model,{profile});const filename=`${asset.replace(/[^a-zA-Z0-9_.-]/g,'_').slice(0,80)}-r${revision}-${profile}-${randomUUID().slice(0,8)}.svg`,directory=join(root,'exports');await mkdir(directory,{recursive:true});await writeFile(join(directory,filename),result.svg);await writeFile(join(directory,filename+'.json'),JSON.stringify({...result.report,revision},null,2));return {savedFile:join(directory,filename),report:result.report};}});
 const plans=new PlanExecutor({model:()=>model,revision:()=>revision,sessionId:()=>sessionId,documentId:()=>model.project.documentId!,board:()=>choices.current,reference:ref=>agent.reference(ref),saveSnapshot:async(doc,label)=>(await snapshots.save(doc,model.project.documentId!,label)).id,
  render:async(doc,time,region)=>{const r=await renderSvg(doc.frame(time),0);if(!region)return r.png;const sharp=(await import('sharp')).default;const left=Math.max(0,Math.floor(region.x)),top=Math.max(0,Math.floor(region.y));return sharp(r.png).extract({left,top,width:Math.max(1,Math.min(r.width-left,Math.ceil(region.width))),height:Math.max(1,Math.min(r.height-top,Math.ceil(region.height)))}).png().toBuffer();},
  metrics:async(a,b,region)=>perceptualMetrics(await rawPixels(a),await rawPixels(b),region),writeArtifact:async(name,png)=>{const dir=join(cache,'artifacts');await mkdir(dir,{recursive:true});const file=join(dir,name.replace(/[^\w.-]/g,'_'));await writeFile(file,png);return file;},
  commit:async(ops,expectedRevision,label,precondition,receipt)=>{const r=await apply(ops,expectedRevision,label,'agent',{precondition,receipt});await inbox.push('plan.committed',{requestId:r.receipt!.requestId,revision:r.transaction.revision,label},'Plan confirmado: muestra al humano previews y cambios del recibo.');return r.receipt!;},receipts});
 const json=(res:ServerResponse,value:unknown,status=200)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(value));};
 async function body(req:IncomingMessage){const buffers=[];let bytes=0;for await(const chunk of req){bytes+=chunk.length;if(bytes>44*1024*1024)throw Error('Request exceeds 44 MiB');buffers.push(chunk);}return JSON.parse(Buffer.concat(buffers).toString()||'{}');}
 const server=createServer(async(req,res)=>{try{
  if(![`127.0.0.1:${port}`,`localhost:${port}`].includes(req.headers.host??'')){json(res,{error:'Invalid host'},403);return;}
  const url=new URL(req.url!,origin),path=url.pathname;
  if(path.startsWith('/api/')){
   if(req.headers.origin&&req.headers.origin!==origin&&req.headers.origin!==`http://localhost:${port}`){json(res,{error:'Invalid origin'},403);return;}
   if(req.method!=='GET'&&req.headers['x-mai-token']!==token){json(res,{error:'Invalid session token'},403);return;}
   if(req.method==='GET'&&path==='/api/bootstrap'){json(res,{...summary(),token});return;}
   if(req.method==='GET'&&path==='/api/choices'){json(res,choices.public());return;}
   if(req.method==='GET'&&path==='/api/comments'){json(res,{asset,comments:comments.public()});return;}
   if(req.method==='GET'&&path==='/api/comment-shot'){const png=await comments.shot(url.searchParams.get('id')??'');res.writeHead(200,{'Content-Type':'image/png','Cache-Control':'no-store'});res.end(png);return;}
   if(req.method==='GET'&&path==='/api/inbox'){const after=Math.max(0,Number(url.searchParams.get('after')??0)),wait=Math.max(0,Math.min(600000,Number(url.searchParams.get('wait')??0))),types=url.searchParams.get('types')?.split(',').filter(Boolean);const events=await inbox.wait(after,wait,types);json(res,{cursor:events.at(-1)?.seq??after,latest:inbox.seq,events});return;}
   if(req.method==='GET'&&path==='/api/selection'){json(res,{ids:selection});return;}
   if(req.method==='GET'&&path==='/api/agent/capabilities'){json(res,{ok:true,tool:'capabilities',revision,tools:TOOLS,conventions:CONVENTIONS});return;}
   if(req.method==='GET'&&path==='/api/choice-preview'){const png=await choices.preview(url.searchParams.get('id')??'',url.searchParams.get('option')??'');res.writeHead(200,{'Content-Type':'image/png','Cache-Control':'no-store'});res.end(png);return;}
   if(req.method==='GET'&&path==='/api/state'){json(res,summary());return;}
   if(req.method==='GET'&&path==='/api/download'){const name=url.searchParams.get('file')??'';if(!/^[a-zA-Z0-9_.-]+\.svg$/.test(name))throw Error('Invalid export filename');const directory=await realpath(join(root,'exports')),file=await realpath(join(directory,name)),rel=relative(directory,file);if(rel==='..'||rel.startsWith(`..${sep}`))throw Error('Invalid export path');res.writeHead(200,{'Content-Type':'image/svg+xml','Content-Disposition':`attachment; filename="${name}"`,'Cache-Control':'no-store'});res.end(await readFile(file));return;}
   if(req.method==='GET'&&path==='/api/svg'){res.writeHead(200,{'Content-Type':'image/svg+xml','Cache-Control':'no-store'});res.end(model.toSVG());return;}
   if(req.method==='GET'&&path==='/api/objects'){json(res,model.list(url.searchParams.get('filter')??'',Math.max(0,Number(url.searchParams.get('offset')??0)),Math.min(200,Number(url.searchParams.get('limit')??80))));return;}
   if(req.method==='GET'&&path==='/api/object'){json(res,model.info(model.element(url.searchParams.get('id')!)));return;}
   if(req.method==='GET'&&path==='/api/history'){json(res,{revision,entries:entries.slice(-100),canUndo:undo.length>0,canRedo:redo.length>0});return;}
   if(req.method==='GET'&&path==='/api/assets'){let records=[];try{records=JSON.parse(await readFile(join(root,'assets/manifest.json'),'utf8')).records;}catch{}json(res,{records});return;}
   if(req.method==='POST'){
    const data=await body(req);
    if(path==='/api/choices/propose'){json(res,await queued(async()=>{expected(data.expectedRevision);const result=await choices.propose(data.request,model,revision);broadcast({patches:[]});await inbox.push('choice.proposed',{id:result!.id,options:result!.options.map(o=>o.id)},'Espera la elección o el comentario del usuario (mai inbox --wait 600).');return result;}));return;}
    // Agent surface: one entry point for every structured tool (the CLI and the MCP server call this).
    if(path==='/api/agent/call'){try{json(res,await agent.call(String(data.tool),data.args??{}));}catch(error){const e=error as {status?:number;code?:string;message?:string;extra?:Record<string,unknown>};const code=error instanceof AgentError?e.code:e.status===409?(e.code??'REVISION_CONFLICT'):e.code??(/Protected identity/.test(String(e.message))?'IDENTITY_BLOCKED':'OPERATION_FAILED');json(res,{ok:false,tool:data.tool,revision,...(data.tool==='plan.execute'?{requestId:data.args?.plan?.requestId,committed:false}:{}),error:{code,message:String(e.message??e),...(error instanceof AgentError?error.extra:(error as {detail?:Record<string,unknown>}).detail??{})}},error instanceof AgentError?error.status:e.status??422);}return;}
    if(path==='/api/selection'){selection=(Array.isArray(data.ids)?data.ids:[]).filter((id:unknown)=>typeof id==='string'&&model.index.has(id)).slice(0,500);json(res,{ids:selection});return;}
    if(path==='/api/choices/note'){const note=await choices.note(String(data.id),String(data.text),data.author==='agent'?'agent':'user');broadcast({patches:[]});if(note.author==='user')await inbox.push('choice.note',{id:data.id,text:note.text},'El usuario escribió sobre el tablero: interprétalo (choices.inspect) y responde con herramientas (variant.combine, choice.regenerate, animation.adjust…).');json(res,note);return;}
    if(path==='/api/comments'){json(res,await queued(async()=>{expected(data.expectedRevision);const c=await comments.add(model,data,revision);broadcast({patches:[]});await inbox.push('comment.created',{id:c.id,text:c.text,time:c.time,targets:c.targets.slice(0,20),parts:c.parts,region:c.region,screenshot:c.screenshot?comments.shotPath(c.id):undefined},`Interpreta el comentario (partes: ${c.parts.map(x=>x.id).join(', ')||'región sin etiquetar'}); actúa con herramientas o propone opciones, y responde con comments.reply ${c.id}.`);return c;}));return;}
    if(path==='/api/comments/reply'){const c=await comments.reply(String(data.id),data);broadcast({patches:[]});if(data.author==='user')await inbox.push('comment.replied',{id:c.id,text:data.text},'El usuario respondió al comentario; vuelve a leerlo.');json(res,c);return;}
    if(path==='/api/comments/resolve'){const c=await comments.resolve(String(data.id));broadcast({patches:[]});json(res,c);return;}
    // Editor/legacy choice: the acceptance is part of the same journaled transaction as the option's operations.
    if(path==='/api/choices/choose'){expected(data.expectedRevision);const option=choices.selected(data.id,data.option,revision,model);const c=choices.current!;const result=await apply([...option.ops,{type:'choice.accept',acceptance:{boardId:c.id,version:c.version,option:option.id,label:option.label,source:'editor-choice',...(data.text?{text:String(data.text).slice(0,4000)}:{})}},{type:'decision.log',decision:{kind:c.kind??'choice',summary:`${c.prompt} → ${option.id} (${option.label})`,source:data.source==='agent'?'agent':'user'}}],data.expectedRevision,'Elegir: '+option.label,data.source??'editor');broadcast({patches:[]});await inbox.push('choice.chosen',{id:data.id,option:option.id,label:option.label},'Opción aplicada como transacción; verifica (render/critique) y continúa.');json(res,{...result,choice:choices.public()});return;}
    if(path==='/api/choices/dismiss'){json(res,await queued(async()=>{expected(data.expectedRevision);if(choices.current?.id!==data.id||choices.current?.status!=='pending')throw Error('Unknown pending choice');choices.current!.status='dismissed';await choices.save();broadcast({patches:[]});await inbox.push('choice.dismissed',{id:data.id},'El usuario pospuso la decisión; no elijas por él.');return choices.public();}));return;}
    if(path==='/api/preview'){expected(data.expectedRevision);const draft=new VectorDocument(model.toSVG());const change=draft.apply(data.ops);json(res,{revision,committed:false,...change,project:draft.project,audit:detect(draft).summary});return;}
    if(path==='/api/insert'){expected(data.expectedRevision);const source=new VectorDocument(data.svg,String(data.name??'SVG'));const svg=exportSvg(source,{profile:'standalone'}).svg;json(res,await apply([{type:'scene.insert',svg,name:String(data.name??'SVG'),x:data.placement?.x,y:data.placement?.y,width:data.placement?.width,height:data.placement?.height}],data.expectedRevision,'Agregar SVG'));return;}
    if(path==='/api/apply'){json(res,await apply(data.ops,data.expectedRevision,data.label,data.source==='editor'?'editor':'cli'));return;}
    if(path==='/api/undo'||path==='/api/redo'){json(res,await historyAction(path.slice(5) as 'undo'|'redo',data.expectedRevision));return;}
    if(path==='/api/open'){if(data.name==='demo'){json(res,await open(starterSvg,'demo',data.expectedRevision));return;}if(!/^[a-z0-9_]+$/.test(data.name)||!['vector','animated'].includes(data.kind??'vector'))throw Error('Invalid asset');const svg=await readFile(join(root,`assets/${data.kind??'vector'}`,`${data.name}.svg`),'utf8');json(res,await open(svg,data.name,data.expectedRevision));return;}
    if(path==='/api/import'){expected(data.expectedRevision);const buffer=Buffer.from(data.base64,'base64');if(buffer.length>32*1024*1024)throw Error('Import exceeds 32 MiB');let svg:string;if(/\.svg$/i.test(data.name)){const source=buffer.toString('utf8');svg=data.vectorize?(await vectorizeSvg(source,PRESETS.find(p=>p.id==='high-color-preserved')!)).svg:source;}else svg=(await vectorizeRaster(buffer,PRESETS.find(p=>p.id==='high-color-preserved')!)).svg;json(res,data.append?await apply([{type:'scene.insert',svg:exportSvg(new VectorDocument(svg),{profile:'standalone'}).svg,name:String(data.name).slice(0,200)}],data.expectedRevision,'Agregar SVG'):await open(svg,String(data.name).slice(0,200),data.expectedRevision));return;}
    if(path==='/api/export'){expected(data.expectedRevision);const result=exportSvg(model,data as ExportOptions),exportRevision=revision;const filename=`${asset.replace(/[^a-zA-Z0-9_.-]/g,'_').slice(0,80)}-r${exportRevision}-${data.profile}-${randomUUID().slice(0,8)}.svg`,directory=join(root,'exports');await mkdir(directory,{recursive:true});await writeFile(join(directory,filename),result.svg);await writeFile(join(directory,filename+'.json'),JSON.stringify({...result.report,revision:exportRevision},null,2));json(res,{...result,savedFile:'exports/'+filename,downloadUrl:'/api/download?file='+encodeURIComponent(filename)});return;}
    if(path==='/api/render'){expected(data.expectedRevision);const result=exportSvg(model,{profile:'standalone',tolerance:.25});const image=await renderSvg(result.svg,Number(data.time??0));json(res,{...image,png:undefined,base64:image.png.toString('base64'),exportReport:result.report});return;}
   }
   json(res,{error:'Unknown API route'},404);return;
  }
  if(req.method!=='GET'){res.writeHead(405);res.end();return;}
  const directory=await realpath(join(root,'apps/editor/dist'));const file=await realpath(resolve(directory,`.${path==='/'?'/index.html':decodeURIComponent(path)}`));const rel=relative(directory,file);if(rel==='..'||rel.startsWith(`..${sep}`)){res.writeHead(403);res.end();return;}
  const mime:Record<string,string>={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml'};if(!mime[extname(file)]){res.writeHead(404);res.end();return;}res.writeHead(200,{'Content-Type':mime[extname(file)],'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' blob: data:; connect-src 'self'; object-src 'none'; base-uri 'none'"});res.end(await readFile(file));
 }catch(error){json(res,{error:String(error),revision},(error as {status?:number}).status??422);}});
 server.on('upgrade',(req,socket,head)=>{const url=new URL(req.url!,origin);if(req.headers.host!==`127.0.0.1:${port}`||req.headers.origin!==origin||url.pathname!=='/events'||url.searchParams.get('token')!==token){socket.destroy();return;}ws.handleUpgrade(req,socket,head,s=>ws.emit('connection',s,req));});
 ws.on('connection',socket=>socket.send(JSON.stringify({type:'hello',...summary()})));
 await new Promise<void>((yes,no)=>{server.once('error',no);server.listen(port,'127.0.0.1',yes);});await writeFile(join(cache,'session.json'),JSON.stringify({url:origin,token,sessionId}),{mode:0o600});save();
 console.log(`MAI SVG editor: ${origin}`);
 return {server,model:()=>model,close:async()=>{inbox.close();if(timer)clearTimeout(timer);await queue;await checkpoint();for(const socket of ws.clients)socket.terminate();ws.close();server.closeAllConnections();await new Promise<void>(yes=>server.close(()=>yes()));await closeRenderer();}};
}
