// Verifies the state an external agent left in the S4 workspace. Uses only the public agent API + renders.
// Usage: npx tsx scripts/s4-verify.ts --dir DIR --out experiments/evidence/s4-candy-run.json [--transcript FILE]
import {readFile,writeFile,mkdir,copyFile} from 'node:fs/promises';import {join,resolve,dirname} from 'node:path';import {createHash} from 'node:crypto';
import sharp from 'sharp';import {VectorDocument} from '../packages/core/document.js';import {renderSvg,closeRenderer} from '../packages/server/render.js';import {metrics,raw} from '../packages/server/perceptual.js';
const arg=(n:string,d?:string)=>{const i=process.argv.indexOf(n);return i>0?process.argv[i+1]:d;};
const dir=resolve(arg('--dir')!),out=resolve(arg('--out','experiments/evidence/s4-candy-run.json')!);const prepared=JSON.parse(await readFile(join(dir,'prepared.json'),'utf8'));
const cfg=JSON.parse(await readFile(join(dir,'.cache/session.json'),'utf8'));const sha=(b:Buffer|string)=>createHash('sha256').update(b).digest('hex');
const call=async(tool:string,args:Record<string,unknown>={})=>{const r=await fetch(`${cfg.url}/api/agent/call`,{method:'POST',headers:{'Content-Type':'application/json','x-mai-token':cfg.token},body:JSON.stringify({tool,args})});return await r.json() as Record<string,any>;};
const times=[0,.66,1.6,2.8,4.1,5.2,6.5];const report:Record<string,unknown>={verifiedAt:new Date().toISOString(),workspace:dir,prepared};
try{
 report.sources={approvedUnchanged:sha(await readFile(join(dir,'approved/candy_alchemist_cat.svg')))===prepared.approvedSha256,projectAssetUnchanged:sha(await readFile('assets/vector/candy_alchemist_cat.svg'))===prepared.projectSourceSha256};
 const history=await call('scene.history',{limit:40});report.history=history.entries.filter((e:{revision:number})=>e.revision>prepared.revision);
 const state=await (await fetch(`${cfg.url}/api/state`)).json();const p=state.project;
 report.state={revision:state.revision,choice:state.choice?{id:state.choice.id,status:state.choice.status,selected:state.choice.selected,version:state.choice.version}:null,acceptances:p.acceptances,smokeSpeedFactor:p.modifiers?.find((m:{id:string})=>m.id==='smoke-flow')?.params.speedFactor??1,params:Object.fromEntries(Object.entries(p.params??{}).filter(([,d])=>(d as {default:number}).default!==0).map(([k,d])=>[k,(d as {default:number}).default])),paramTracks:p.tracks.filter((t:{property:string})=>t.property==='param').map((t:{target:string;layer?:string})=>`${t.target}@${t.layer??'base'}`),protections:p.semantic.nodes.filter((n:{protection?:string[]})=>n.protection?.length).map((n:{id:string;protection:string[]})=>({id:n.id,protection:n.protection}))};
 const identity=await call('identity.check',{reference:{kind:'baseline',id:'approved'},parts:['nose','mouth','candy.eyes'],times});report.identityVsApproved={status:identity.status,evaluatedParts:identity.evaluatedParts,skipped:identity.skipped,perPart:Object.values((identity.evaluated??[]).reduce((acc:Record<string,{part:string;expectation:string;maxMae:number;minSsim:number;statuses:string[]}>,e:Record<string,any>)=>{const a=acc[e.part]??={part:e.part,expectation:e.expectation,maxMae:0,minSsim:1,statuses:[]};a.maxMae=Math.max(a.maxMae,e.mae);a.minSsim=Math.min(a.minSsim,e.ssim);a.statuses.push(e.status);return acc;},{}))};
 // Smoke: the ORIGINAL smoke is present (rest frame equals the approved art in the smoke region) and it flows over time.
 const svg=await (await fetch(`${cfg.url}/api/svg`)).text();const doc=new VectorDocument(svg);const still=new VectorDocument(svg);for(const m of still.project.modifiers??[])m.enabled=false;still.project.tracks=still.project.tracks.filter(t=>t.property!=='param');for(const k of Object.keys(still.project.params??{}))still.project.params![k].default=0;
 const approved=await renderSvg(await readFile(join(dir,'approved/candy_alchemist_cat.svg'),'utf8'));const smokeBox={x:482,y:76,width:148,height:138};
 const stillFrame=await renderSvg(still.frame(0));report.smokeOriginal={maeVsApprovedAtRest:metrics(await raw(approved.png),await raw(stillFrame.png),smokeBox).mae,note:'Smoke modifier disabled, expression neutral: compares the extracted original smoke to the approved conversion.'};
 // Whole-frame fidelity at rest (expression neutral, modifiers off) against the approved conversion, alpha included.
 { const A=await raw(approved.png),B=await raw(stillFrame.png);let maxAlpha=0,alphaDiff=0,partialA=0,partialB=0;for(let i=3;i<A.data.length;i+=4){const d=Math.abs(A.data[i]-B.data[i]);maxAlpha=Math.max(maxAlpha,d);if(d>2)alphaDiff++;if(A.data[i]>0&&A.data[i]<255)partialA++;if(B.data[i]>0&&B.data[i]<255)partialB++;}
  report.restFidelity={...metrics(A,B),maxAlphaDiff:maxAlpha,pixelsAlphaDiffOver2:alphaDiff,partialAlphaPixels:{approved:partialA,rest:partialB},note:'Full frame at rest vs approved/candy_alchemist_cat.svg; partial alpha must survive (no flattening).'}; }
 const frames:Record<string,unknown>[]=[];let prev:Buffer|undefined;await mkdir(join(dirname(out),'s4-frames'),{recursive:true});
 for(const t of times){const r=await renderSvg(doc.frame(t));const file=join(dirname(out),'s4-frames',`candy-t${t}.png`);await writeFile(file,await sharp(r.png).png().toBuffer());const m=prev?metrics(await raw(prev),await raw(r.png),smokeBox):undefined;frames.push({time:t,file:file.replace(resolve('.')+'/',''),sha256:sha(r.png).slice(0,16),...(m?{smokeChangeVsPreviousMae:m.mae}:{})});prev=r.png;}
 report.frames=frames;
 // Save/reopen roundtrip of the editable export keeps the authoring state.
 const reopened=new VectorDocument(svg);report.roundtrip={paramsEqual:JSON.stringify(reopened.project.params)===JSON.stringify(p.params),modifiersEqual:JSON.stringify(reopened.project.modifiers?.map(m=>m.params))===JSON.stringify(p.modifiers?.map((m:{params:unknown})=>m.params)),acceptances:reopened.project.acceptances?.length??0};
 // Delivery: both export profiles through the same agent API (files land in the isolated workspace).
 const rev=Number(state.revision);const exports:Record<string,unknown>={};
 for(const profile of ['editable','standalone']){const t0=Date.now();const r=await call('export',{profile,expectedRevision:rev});if(!r.ok){exports[profile]={ok:false,error:r.error,ms:Date.now()-t0};continue;}
  const file=String(r.savedFile??'');const text=file?await readFile(resolve(dir,file),'utf8').catch(()=>''):'';const reopen=profile==='editable'&&text?new VectorDocument(text):undefined;
  exports[profile]={ok:true,ms:Date.now()-t0,file,bytes:Buffer.byteLength(text),rasterImages:(text.match(/<image\b/g)??[]).length,scripts:(text.match(/<script\b/g)??[]).length,report:r.report,compatibility:r.compatibility,...(reopen?{reopened:{paramsEqual:JSON.stringify(reopen.project.params)===JSON.stringify(p.params),modifiersEqual:JSON.stringify(reopen.project.modifiers?.map(m=>m.params))===JSON.stringify(p.modifiers?.map((m:{params:unknown})=>m.params)),acceptances:reopen.project.acceptances?.length??0,semanticNodes:reopen.project.semantic?.nodes.length??0}}:{})};}
 report.exports=exports;
 const transcript=arg('--transcript');if(transcript){await copyFile(transcript,out.replace(/\.json$/,'.transcript.jsonl'));report.transcript=out.replace(/\.json$/,'.transcript.jsonl').replace(resolve('.')+'/','');}
}finally{await closeRenderer();}
await mkdir(dirname(out),{recursive:true});await writeFile(out,JSON.stringify(report,null,1));console.log(JSON.stringify(report,null,1));
