import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
export interface GalleryEntry { name:string; candidates:{id:string; report:Record<string,unknown>}[]; }
export async function writeGallery(output:string,entries:GalleryEntry[]) {
  const escape=(v:unknown)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
  const cards=entries.map(entry=>`<section><h2>${escape(entry.name.replaceAll('_',' '))}</h2><div class="grid"><article><h3>Original</h3><div class="preview"><img src="${encodeURIComponent(entry.name)}/original.png" alt="Original"></div><p>Referencia raster · no se modifica</p></article>${entry.candidates.map(({id,report:r})=>`<article data-preset="${escape(id)}"><h3>${escape(id)}</h3><div class="preview"><img class="vector" src="${encodeURIComponent(entry.name)}/${encodeURIComponent(id)}.svg" alt="${escape(id)}"><img class="overlay" src="${encodeURIComponent(entry.name)}/original.png" alt="Referencia superpuesta"></div><label>Original superpuesto <input aria-label="Opacidad del original ${escape(id)}" type="range" min="0" max="100" value="0" oninput="this.closest('article').querySelector('.overlay').style.opacity=this.value/100"></label><dl><dt>Trazos</dt><dd>${escape(r.paths)}</dd><dt>Comandos</dt><dd>${escape(r.commands)}</dd><dt>Tamaño</dt><dd>${(Number(r.bytes)/1024).toFixed(0)} KiB</dd><dt>Colores de relleno*</dt><dd>${escape(r.colors)}</dd><dt>IoU silueta</dt><dd>${escape(r.silhouetteIoU)}</dd><dt>Error RGB**</dt><dd>${escape(r.premultipliedRgbMae)}</dd><dt>Error alfa**</dt><dd>${escape(r.alphaMae)}</dd><dt>Tiempo total</dt><dd>${(Number(r.elapsedMs)/1000).toFixed(1)} s</dd></dl><nav><a href="${encodeURIComponent(entry.name)}/${encodeURIComponent(id)}.svg" target="_blank" rel="noopener">Abrir SVG</a><a href="${encodeURIComponent(entry.name)}/${encodeURIComponent(id)}.json">Reporte</a></nav><span class="badge">Pendiente de revisión visual</span></article>`).join('')}</div></section>`).join('');
  await writeFile(join(output,'index.html'),`<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MAI SVG — laboratorio de conversión</title><style>
  :root{font-family:system-ui,sans-serif;color:#e9edf2;background:#101318}*{box-sizing:border-box}body{margin:0}header{padding:32px 36px;border-bottom:1px solid #303843;position:relative}small{letter-spacing:.18em;color:#96e0c1}h1{font-size:38px;margin:12px 0}header p{max-width:850px;line-height:1.7;color:#b9c5d2}main{padding:24px 36px}.controls{display:flex;gap:24px;align-items:center;flex-wrap:wrap}button,select{color:inherit;background:#222a33;padding:10px;border:1px solid #4a5868;border-radius:6px}h2{text-transform:capitalize;font-size:24px;margin:30px 0 18px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:16px}article[hidden]{display:none}article{min-width:0;background:#1a2028;border:1px solid #353f4b;border-radius:12px;overflow:hidden;padding:16px}h3{font-size:14px;margin:0 0 16px}.preview{position:relative;aspect-ratio:1;overflow:auto;background-color:#ddd;background-image:linear-gradient(45deg,#bbb 25%,transparent 25%),linear-gradient(-45deg,#bbb 25%,transparent 25%),linear-gradient(45deg,transparent 75%,#bbb 75%),linear-gradient(-45deg,transparent 75%,#bbb 75%);background-size:24px 24px;background-position:0 0,0 12px,12px -12px,-12px 0}.preview img{display:block;width:calc(100% * var(--zoom,1));max-width:none}.overlay{position:absolute;top:0;left:0;opacity:0;pointer-events:none}label{font-size:12px;color:#bfccd8;display:block;margin-top:14px}input{width:100%}dl{font-size:13px;display:grid;grid-template-columns:1fr auto;line-height:1.8;color:#bfccd8}dd{margin:0;color:#fff;font-variant-numeric:tabular-nums}nav{display:flex;gap:16px}a{color:#96e0c1}p{font-size:13px;line-height:1.6}.badge{display:block;margin-top:16px;color:#eac98e;font-size:12px}footer{padding:36px;color:#a7b5c6;font-size:13px;line-height:1.8}.detail{color:#c6d2de}.preview.light{background:#fff}.preview.dark{background:#171717}
  </style><header><small>MAI SVG / EXPERIMENTO A</small><h1>Del píxel al trazo.</h1><p>Compara identidad, ojos, contornos, accesorios y transparencias antes de elegir un preset. Todos los candidatos contienen geometría SVG y una máscara vectorial de alfa; ningún PNG está incrustado.</p><div class="controls"><label>Candidato <select id="candidate"><option value="high-color-preserved">Alta fidelidad</option><option value="balanced-color-preserved">Equilibrado</option><option value="high-spline-stacked">Alta fidelidad inicial</option><option value="all">Todos</option></select></label><label>Zoom <select id="zoom"><option value="1">100%</option><option value="2">200%</option><option value="4">400%</option></select></label><label>Fondo <select id="background"><option value="checker">Transparencia</option><option value="light">Blanco</option><option value="dark">Negro</option></select></label><button id="sync">Sincronizar desplazamiento: no</button></div><p class="detail">Con zoom, desplaza los cuadros para inspeccionar detalles. El deslizador de cada candidato superpone el original en la misma posición.</p></header><main>${cards}</main><footer>* Incluye rellenos de la máscara de alfa; no representa la cantidad de colores percibidos.<br>** Error absoluto medio en escala 0–255 sobre la unión de píxeles visibles. RGB premultiplicado por alfa. Menor es mejor. IoU mayor es mejor. Estas métricas no aprueban la calidad estética.<br>El tiempo incluye decodificación, workers, optimización y render de comparación. RSS del reporte corresponde al proceso principal; no es memoria pico del trabajo.<br>Para confirmar tu elección, indica el nombre del gato y el preset. El editor y la conversión de los 32 esperan esta validación.</footer><script>
  const previews=[...document.querySelectorAll('.preview')];let sync=false,locked=false;
  const filterCandidates=value=>document.querySelectorAll('article[data-preset]').forEach(card=>card.hidden=value!=='all'&&card.dataset.preset!==value);
  document.querySelector('#candidate').onchange=e=>filterCandidates(e.target.value);filterCandidates('high-color-preserved');
  document.querySelector('#zoom').onchange=e=>document.documentElement.style.setProperty('--zoom',e.target.value);
  document.querySelector('#background').onchange=e=>previews.forEach(p=>p.className='preview '+e.target.value);
  document.querySelector('#sync').onclick=e=>{sync=!sync;e.target.textContent='Sincronizar desplazamiento: '+(sync?'sí':'no')};
  previews.forEach(p=>p.addEventListener('scroll',()=>{if(!sync||locked)return;locked=true;const x=p.scrollLeft/Math.max(1,p.scrollWidth-p.clientWidth),y=p.scrollTop/Math.max(1,p.scrollHeight-p.clientHeight);previews.forEach(q=>{if(q!==p){q.scrollLeft=x*(q.scrollWidth-q.clientWidth);q.scrollTop=y*(q.scrollHeight-q.clientHeight)}});requestAnimationFrame(()=>locked=false)}));
  </script></html>`);
}
