import sharp from 'sharp';import {elements}from '../converter/svg.js';import {frameState,poseTransform}from '../core/animation.js';import {readFile,writeFile,mkdir}from 'node:fs/promises';import {createHash}from 'node:crypto';import {resolve}from 'node:path';import {renderSvg,closeRenderer}from '../server/render.js';import {VectorDocument}from '../core/document.js';
export type IdentityConfig={width:number;height:number;regions:{name:string;x:number;y:number;width:number;height:number;maxMae?:number}[];canonicalize?:string[]};
export async function identityCheck(reference:string,candidate:string,config:IdentityConfig,times:number[],output:string){
 const w=config.width,h=config.height;if(!Number.isInteger(w)||!Number.isInteger(h)||w<1||h<1||w*h>4e6||!Array.isArray(config.regions)||!config.regions.length||config.regions.length>32||!times.length||times.length>24||times.some(t=>!Number.isFinite(t)||t<0||t>300))throw Error('Invalid identity comparison configuration');
 for(const r of config.regions)if(!r.name||![r.x,r.y,r.width,r.height].every(Number.isInteger)||r.x<0||r.y<0||r.width<1||r.height<1||r.x+r.width>w||r.y+r.height>h||!Number.isFinite(r.maxMae??6)||(r.maxMae??6)<0||(r.maxMae??6)>255)throw Error('Invalid identity region');
 const input=await readFile(reference),svg=await readFile(candidate,'utf8');const model=new VectorDocument(svg);if(elements(model.doc).some(e=>['animate','animateTransform','animateMotion','set'].includes(e.localName)||e.localName==='style'&&/animation|@keyframes/.test(e.textContent??'')))throw Error('Identity check requires MAI editable animation; import native animation first');if(times.some(t=>t>model.project.duration))throw Error('Time exceeds project duration');
 const sourceMeta=await sharp(input).metadata();if(sourceMeta.width!==w||sourceMeta.height!==h)throw Error('Reference dimensions differ from profile');const base=await sharp(input).ensureAlpha().raw().toBuffer();
 await mkdir(output,{recursive:true});const frames=[];
 try{for(const time of times){const frame=model.frame(time);const canonical=new VectorDocument(frame);for(const id of config.canonicalize??[]){const original=model.project.poses[id];if(!original)throw Error('Canonicalization ID lacks authored rest pose: '+id);const current=frameState(model.project,time).poses[id]??original;canonical.element(id).setAttribute('transform',`${poseTransform({...current,x:original.x,y:original.y,rotation:original.rotation})} ${model.project.baseTransforms[id]??''}`);}
 const rendered=await renderSvg(canonical.toSVG(false));if(rendered.width!==w||rendered.height!==h)throw Error('Candidate canvas dimensions differ');const image=await sharp(rendered.png).ensureAlpha().raw().toBuffer();const regions=config.regions.map(r=>{let error=0;for(let y=r.y;y<r.y+r.height;y++)for(let x=r.x;x<r.x+r.width;x++){const i=(y*w+x)*4;for(let c=0;c<3;c++)error+=Math.abs(base[i+c]*base[i+3]/255-image[i+c]*image[i+3]/255);error+=Math.abs(base[i+3]-image[i+3]);}const mae=error/(r.width*r.height*4);return{name:r.name,mae:Number(mae.toFixed(4)),maxMae:r.maxMae??6,pass:mae<=(r.maxMae??6)};});await writeFile(resolve(output,`frame-${time}.png`),rendered.png);frames.push({time,regions,pass:regions.every(r=>r.pass)});}
 }finally{await closeRenderer();}
 const report={schemaVersion:1,reference:resolve(reference),referenceSha256:createHash('sha256').update(input).digest('hex'),candidate:resolve(candidate),canonicalizedRigidParts:config.canonicalize??[],metric:'premultiplied RGBA MAE by feature, 0–255; not semantic identity recognition',visualReviewRequired:true,pass:frames.every(f=>f.pass),frames};await writeFile(resolve(output,'identity.json'),JSON.stringify(report,null,2));return report;
}
