import React,{useEffect,useRef,useState} from 'react';
import type {Project} from '../../../packages/core/model.js';
// Human ↔ agent collaboration surfaces. MAI shows and records; the agent (Claude/Codex) interprets the words.
type Post=(path:string,data?:Record<string,unknown>)=>Promise<any>;
export type Board={id:string;version:number;prompt:string;reason:string;recommended:string;revision:number;status:string;selected?:string;contentHash?:string;notes?:{at:string;author:string;text:string}[];history?:{at:string;event:string}[];options:{id:string;label:string;description:string;preview:string;derivedFrom?:{base:string;take:Record<string,string>;preserve:string[]}}[]};
export type InboxEvent={seq:number;at:string;type:string;data:Record<string,unknown>};
export type CommentItem={id:string;text:string;time:number;status:string;parts:{id:string;role:string;label:string}[];targets:string[];replies:{at:string;author:string;text:string}[];screenshot?:{url:string};revision:number;author:string};
const EVENT_LABEL:Record<string,string>={'plan.committed':'Plan aplicado','choice.proposed':'Opciones propuestas','choice.chosen':'Opción elegida','choice.dismissed':'Opciones pospuestas','choice.note':'Nota sobre opciones','comment.created':'Comentario','comment.replied':'Respuesta','edit.user':'Edición en el editor'};
// Selection is shared with agents (scene.selection) so "esto" resolves to what the human sees selected.
export function useSelectionSync(selected:string[],revision:number|undefined,post:Post){const last=useRef('');useEffect(()=>{const key=selected.join(',')+'@'+revision;if(key===last.current)return;const t=setTimeout(()=>{last.current=key;void post('selection',{ids:selected.slice(0,500),revision});},250);return()=>clearTimeout(t);},[selected,revision,post]);}
export function ChoiceBoard({board,revision,busy,post,onChanged}:{board:Board;revision:number;busy:boolean;post:Post;onChanged:()=>void}){
 const [note,setNote]=useState(''),[min,setMin]=useState(false),[sent,setSent]=useState('');const stale=board.revision!==revision;
 if(min)return <button className="choice-pill" onClick={()=>setMin(false)}>◆ {board.prompt} · {board.options.length} opciones</button>;
 return <section className="choice-panel" aria-label="Opciones del asistente"><header><div><h2>{board.prompt}</h2><small>Tablero {board.id} · versión {board.version} · {board.status==='pending'?'esperando tu decisión':board.status}</small></div><div className="button-row"><button onClick={()=>setMin(true)}>Minimizar</button><button disabled={busy} onClick={async()=>{await post('choices/dismiss',{id:board.id});onChanged();}}>Decidir después</button></div></header>
  <p className="recommend">El asistente recomienda <b>{board.recommended}</b>: {board.reason} <i>(recomendar no es elegir)</i></p>
  {stale&&<p role="alert" className="stale">La escena cambió desde que se generaron estas vistas (rev {board.revision} → {revision}). Si el contenido es el mismo siguen siendo válidas; si no, pide nuevas.</p>}
  <div className="choice-options">{board.options.map((o,i)=><article key={o.id+board.version} className={board.selected===o.id?'chosen':''}><img src={`${o.preview}&v=${board.version}`} alt={'Vista previa: '+o.label}/><h3><span className="ordinal">{i+1}</span> {o.id} · {o.label}{o.id===board.recommended?' · recomendada':''}</h3><p>{o.description}</p>
   {o.derivedFrom&&<p className="derived">Derivada de {o.derivedFrom.base}{Object.entries(o.derivedFrom.take??{}).map(([s,f])=>` + ${s} de ${f}`).join('')}{(o.derivedFrom.preserve??[]).length?` · conserva ${o.derivedFrom.preserve.join(', ')}`:''}</p>}
   <button disabled={busy||board.status!=='pending'} onClick={async()=>{await post('choices/choose',{id:board.id,option:o.id,source:'editor'});onChanged();}}>Elegir {o.id}</button></article>)}</div>
  <div className="note-box"><label>Dile al asistente qué te gusta o qué cambiar<textarea value={note} placeholder="Ej.: me gusta la primera pero con los ojos de la tercera; el humo más lento" onChange={e=>setNote(e.target.value)}/></label><button className="primary" disabled={!note.trim()||busy} onClick={async()=>{const v=await post('choices/note',{id:board.id,text:note,author:'user'});if(v){setSent(note);setNote('');onChanged();}}}>Enviar al asistente</button>{sent&&<small>Enviado: «{sent}». El asistente lo interpretará y propondrá o aplicará cambios.</small>}</div>
  {(board.notes??[]).length>0&&<ul className="notes">{board.notes!.slice(-6).map(n=><li key={n.at}><b>{n.author==='user'?'Tú':'Asistente'}:</b> {n.text}</li>)}</ul>}
 </section>;}
export function CommentComposer({at,onSubmit,onCancel}:{at:{x:number;y:number;time:number;targets:string[];parts:string[]};onSubmit:(text:string)=>void;onCancel:()=>void}){const [text,setText]=useState('');
 return <div className="comment-composer" style={{left:at.x,top:at.y}} onPointerDown={e=>e.stopPropagation()}><small>t={at.time.toFixed(2)} s · {at.parts.length?at.parts.join(', '):at.targets.slice(0,2).join(', ')||'región'}</small><textarea autoFocus value={text} placeholder="¿Qué no te gusta o qué quieres aquí?" onChange={e=>setText(e.target.value)}/><div className="button-row"><button onClick={onCancel}>Cancelar</button><button className="primary" disabled={!text.trim()} onClick={()=>onSubmit(text)}>Comentar</button></div></div>;}
export function CommentsPanel({comments,post,onSeek,onChanged}:{comments:CommentItem[];post:Post;onSeek:(t:number)=>void;onChanged:()=>void}){const [reply,setReply]=useState<Record<string,string>>({});
 const open=comments.filter(c=>c.status!=='resolved');if(!comments.length)return <p className="hint">Usa la herramienta ❝ y haz clic en el dibujo para comentar una parte en el tiempo actual. El asistente recibe el texto, las partes, el tiempo y una captura.</p>;
 return <div className="comments">{open.slice(-12).reverse().map(c=><article key={c.id} className={'comment '+c.status}><header><button className="link" onClick={()=>onSeek(c.time)}>⏱ {c.time.toFixed(2)} s</button><span>{c.parts.map(p=>p.label).join(', ')||'región'}</span><span className="status">{c.status==='open'?'pendiente':c.status==='answered'?'respondido':'resuelto'}</span></header>{c.screenshot&&<img src={c.screenshot.url} alt="Captura del comentario"/>}<p>{c.text}</p>{c.replies.map(r=><p key={r.at} className={'reply '+r.author}><b>{r.author==='agent'?'Asistente':'Tú'}:</b> {r.text}</p>)}
  <div className="button-row"><input value={reply[c.id]??''} placeholder="Responder…" onChange={e=>setReply({...reply,[c.id]:e.target.value})}/><button disabled={!(reply[c.id]??'').trim()} onClick={async()=>{await post('comments/reply',{id:c.id,text:reply[c.id],author:'user'});setReply({...reply,[c.id]:''});onChanged();}}>↵</button><button onClick={async()=>{await post('comments/resolve',{id:c.id});onChanged();}}>Resolver</button></div></article>)}</div>;}
export function ActivityFeed({events}:{events:InboxEvent[]}){if(!events.length)return null;return <ul className="activity">{events.slice(-8).reverse().map(e=><li key={e.seq} className={e.type.replace('.','-')}><b>{EVENT_LABEL[e.type]??e.type}</b> {summary(e)}</li>)}</ul>;}
function summary(e:InboxEvent){const d=e.data;if(e.type==='plan.committed')return `rev ${d.revision}: ${d.label??''}`;if(e.type==='comment.created'||e.type==='choice.note')return `«${String(d.text??'').slice(0,60)}»`;if(e.type==='choice.chosen')return `${d.option} (${d.label??''})`;if(e.type==='edit.user')return String(d.label??'');return '';}
// Expression parameters: drag for a live local preview, release to commit one transaction.
export function ParamSliders({project,onPreview,onCommit}:{project:Project;onPreview:(p:Record<string,number>|undefined)=>void;onCommit:(p:Record<string,number>)=>void}){
 const defs=Object.entries(project.params??{}).filter(([k])=>!k.includes('.'));const [draft,setDraft]=useState<Record<string,number>>({});if(!defs.length)return null;
 const groups=new Map<string,[string,{min:number;max:number;default:number}][]>();for(const d of defs){const g=d[0].includes('@')?d[0].split('@')[1]:'global';groups.set(g,[...(groups.get(g)??[]),d]);}
 return <div className="params">{[...groups].map(([g,list])=><details key={g} open={g!=='global'}><summary>{g}</summary>{list.map(([k,d])=>{const v=draft[k]??d.default;return <label key={k} className="slider"><span>{k.split('@')[0]}</span><input type="range" min={d.min} max={d.max} step=".01" value={v} onChange={e=>{const next={...draft,[k]:+e.target.value};setDraft(next);onPreview(Object.fromEntries(defs.map(([n,x])=>[n,next[n]??x.default])));}} onPointerUp={()=>{if(draft[k]!==undefined){onCommit({[k]:draft[k]});const {[k]:_,...rest}=draft;void _;setDraft(rest);onPreview(undefined);}}}/><output>{v.toFixed(2)}</output></label>;})}</details>)}</div>;}
export function PartsList({project,onSelect}:{project:Project;onSelect:(ids:string[])=>void}){const nodes=(project.semantic?.nodes??[]).filter(n=>n.status!=='rejected');if(!nodes.length)return null;
 const depth=(id?:string,n=0):number=>{const p=nodes.find(x=>x.id===id);return p?.parent?depth(p.parent,n+1):n;};
 return <div className="parts">{nodes.map(n=><button key={n.id} className="layer" style={{paddingLeft:7+depth(n.id)*10}} title={n.targets.join(', ')} onClick={()=>n.targets.length&&onSelect(n.targets)}><span>{n.protection?.length?'🔒':'◆'}</span><span>{n.label}</span><small>{n.role}{n.status==='proposed'?' · propuesta':''}</small></button>)}</div>;}
